//! proptest scaffolding for `compile` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// The real element types and strategies are `verify`'s domain.
pub mod spec_gen {
    use super::*;

    pub fn file_that_has_not_passed_lint() -> impl Strategy<Value = GenVal> {
        Just(GenVal("file_that_has_not_passed_lint".into()))
    }

    pub fn arbitrary_constraint_row() -> impl Strategy<Value = GenVal> {
        Just(GenVal("arbitrary_constraint_row".into()))
    }

    pub fn arbitrary_model_section() -> impl Strategy<Value = GenVal> {
        Just(GenVal("arbitrary_model_section".into()))
    }

    pub fn arbitrary_property_row() -> impl Strategy<Value = GenVal> {
        Just(GenVal("arbitrary_property_row".into()))
    }

    pub fn law_property_row_with() -> impl Strategy<Value = GenVal> {
        Just(GenVal("law_property_row_with".into()))
    }

    pub fn arbitrary_linted_and_covered_file() -> impl Strategy<Value = GenVal> {
        Just(GenVal("arbitrary_linted_and_covered_file".into()))
    }

}

proptest! {
    // id: precondition_violation_rejected
    // generator: `file_that_has_not_passed_lint()`
    // predicate: `check(file) == failed`
    #[test]
    fn precondition_violation_rejected(v0 in spec_gen::file_that_has_not_passed_lint()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: toml_roundtrips
    // generator: `arbitrary_constraint_row()`
    // predicate: `parse_toml(compile(row)) == row`
    #[test]
    fn toml_roundtrips(v0 in spec_gen::arbitrary_constraint_row()) {
        todo_predicate!("`parse_toml(compile(row)) == row`");
    }
}

proptest! {
    // id: tla_disjunct_count_matches
    // generator: `arbitrary_model_section(n_transitions)`
    // predicate: `count(disjuncts(compile(model).Next)) == n_transitions`
    #[test]
    fn tla_disjunct_count_matches(v0 in spec_gen::arbitrary_model_section()) {
        todo_predicate!("`count(disjuncts(compile(model).Next)) == n_transitions`");
    }
}

proptest! {
    // id: output_function_covers_emitting_states_only
    // generator: `arbitrary_model_section(n_states_with_emits, n_states_without)`
    // predicate: `domain(compile(model).Output) == the_states_with_emits` — no entry for the rest
    #[test]
    fn output_function_covers_emitting_states_only(v0 in spec_gen::arbitrary_model_section()) {
        todo_predicate!("`domain(compile(model).Output) == the_states_with_emits` — no entry for the rest");
    }
}

proptest! {
    // id: proptest_block_per_property
    // generator: `arbitrary_property_row()`
    // predicate: `count(compile(row).blocks) ≥ 1`
    #[test]
    fn proptest_block_per_property(v0 in spec_gen::arbitrary_property_row()) {
        todo_predicate!("`count(compile(row).blocks) ≥ 1`");
    }
}

proptest! {
    // id: law_property_compiles_required_cases
    // generator: `law_property_row_with(cases: ["identity", "associativity"])`
    // predicate: `count(compile(row).blocks) == 2`
    #[test]
    fn law_property_compiles_required_cases(v0 in spec_gen::law_property_row_with()) {
        todo_predicate!("`count(compile(row).blocks) == 2`");
    }
}

proptest! {
    // id: compile_completes_or_fails_cleanly
    // generator: `arbitrary_linted_and_covered_file()`
    // predicate: `compile(file) ∈ {all_three_artifacts, single_labeled_failure}` — never partial
    #[test]
    fn compile_completes_or_fails_cleanly(v0 in spec_gen::arbitrary_linted_and_covered_file()) {
        todo_predicate!("`compile(file) ∈ {all_three_artifacts, single_labeled_failure}` — never partial");
    }
}

proptest! {
    // id: id_preservation_holds
    // generator: `arbitrary_linted_and_covered_file()`
    // predicate: `ids_in(file) ⊆ ids_in(compile(file))`
    #[test]
    fn id_preservation_holds(v0 in spec_gen::arbitrary_linted_and_covered_file()) {
        todo_predicate!("`ids_in(file) ⊆ ids_in(compile(file))`");
    }
}

proptest! {
    // id: roundtrip_stable
    // generator: `arbitrary_linted_and_covered_file()`
    // predicate: `compile(file) == compile(parse(compile(file)))`
    #[test]
    fn roundtrip_stable(v0 in spec_gen::arbitrary_linted_and_covered_file()) {
        todo_predicate!("`compile(file) == compile(parse(compile(file)))`");
    }
}

