---- MODULE compile ----
\* Generated by `spk compile` from spec `compile` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Executable invariant fragments — id + verbatim **rust:** fragment;
\* carried in the module so the artifact hash covers fragment edits.
\* INVARIANT properties_to_proptest **rust:** fragment when the row opts in ([[compile.predicate_fragment_opt_in]]), else the un-translated todo_predicate! placeholder that compiles here and fails only at execution; a law-kind property compiles to one block per case enumerated in its predicate's **name:** case labels (the identity and associativity floor is lint-enforced ahead of compile, specodelic.md Revision 13)
\* INVARIANT predicate_fragment_opt_in **rust:** marker and a non-empty fragment after it — the fragment is a Rust boolean expression emitted verbatim as the block's assertion body, the cell text after the marker — to the cell's end or the code span's closing backtick — is the fragment, binding the block's generated values (v0…, one per generator named in the generator cell, each a String); a cell with no marker compiles exactly as before (the placeholder) — pure widening, nothing valid before this Revision is invalidated
\* INVARIANT invariant_fragment_opt_in **rust:** fragment when the row's kind is invariant — the fragment becomes an executable invariant model_check's native backend executes (model_check.md Revision 15); a fragment on a Constraint of any other kind (effect, advisory, a pack fiber kind) is a labeled extraction failure, never a silently ignored marker
\* INVARIANT fragment_law_rejected **rust:** fragment — each required case needs its own assertion body and one fragment cannot honestly serve several named cases; violation is a labeled extraction failure
\* INVARIANT fragment_guard_rejected **rust:** fragment in this Revision — the program-counter model has no data binding a guard could constrain, so executable guards have no defined semantics; violation is a labeled extraction failure, never a silently ignored marker (decision of record: deferred to a future Revision alongside a data-carrying state space)

\* Each State becomes a value in the state variable's range.
StateValues == {"not_started", "extracting", "emitting", "compiled", "extract_failed", "emit_failed"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "not_started"

Next ==
  \* begin: not_started -> extracting (guard: [[compile.precondition_satisfied]])
  \/ vpc = "not_started" /\ vpc' = "extracting"
  \* extract_ok: extracting -> emitting (guard: [[compile.constraint_table_to_toml]] ∧ [[compile.model_to_tla]] ∧ [[compile.properties_to_proptest]])
  \/ vpc = "extracting" /\ vpc' = "emitting"
  \* extract_fail: extracting -> extract_failed (guard: `¬([[compile.constraint_table_to_toml]] ∧ [[compile.model_to_tla]] ∧ [[compile.properties_to_proptest]])`)
  \/ vpc = "extracting" /\ vpc' = "extract_failed"
  \* accept: emitting -> compiled (guard: [[compile.compile_preserves_ids]] ∧ [[compile.no_semantic_drift]])
  \/ vpc = "emitting" /\ vpc' = "compiled"
  \* reject: emitting -> emit_failed (guard: `¬([[compile.compile_preserves_ids]] ∧ [[compile.no_semantic_drift]])`)
  \/ vpc = "emitting" /\ vpc' = "emit_failed"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* One entry per state with an `emits` field — domain is exactly
\* the emitting states; each value is the effect-Constraint's expr.
Output ==
"emit_failed" :> "`compile.emission_failure(detail) — the emission stage failed because detail`" @@
"extract_failed" :> "`compile.extraction_failure(row_id, reason) — the extraction stage failed on row row_id because reason`"

============================================================================
