//! proptest scaffolding for `compile` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// Each yields a String (the generator's name; executable
/// fragments bind these directly — Revision 15).
pub mod spec_gen {
    use super::*;

    pub fn file_that_has_not_passed_lint() -> impl Strategy<Value = String> {
        Just("file_that_has_not_passed_lint".into())
    }

    pub fn arbitrary_constraint_row() -> impl Strategy<Value = String> {
        Just("arbitrary_constraint_row".into())
    }

    pub fn arbitrary_model_section() -> impl Strategy<Value = String> {
        Just("arbitrary_model_section".into())
    }

    pub fn arbitrary_property_row() -> impl Strategy<Value = String> {
        Just("arbitrary_property_row".into())
    }

    pub fn law_property_row_with() -> impl Strategy<Value = String> {
        Just("law_property_row_with".into())
    }

    pub fn arbitrary_linted_and_covered_file() -> impl Strategy<Value = String> {
        Just("arbitrary_linted_and_covered_file".into())
    }

    pub fn extraction_stage_fails_on_row() -> impl Strategy<Value = String> {
        Just("extraction_stage_fails_on_row".into())
    }

    pub fn emission_stage_fails() -> impl Strategy<Value = String> {
        Just("emission_stage_fails".into())
    }

    pub fn property_row_with_rust_fragment() -> impl Strategy<Value = String> {
        Just("property_row_with_rust_fragment".into())
    }

    pub fn property_row_without_fragment() -> impl Strategy<Value = String> {
        Just("property_row_without_fragment".into())
    }

    pub fn property_row_with_two_generators() -> impl Strategy<Value = String> {
        Just("property_row_with_two_generators".into())
    }

    pub fn law_row_with_fragment() -> impl Strategy<Value = String> {
        Just("law_row_with_fragment".into())
    }

    pub fn fragment_with() -> impl Strategy<Value = String> {
        Just("fragment_with".into())
    }

    pub fn transition_row_with_fragment_guard() -> impl Strategy<Value = String> {
        Just("transition_row_with_fragment_guard".into())
    }

    pub fn effect_row_with_fragment() -> impl Strategy<Value = String> {
        Just("effect_row_with_fragment".into())
    }

}

proptest! {
    // id: precondition_violation_rejected
    // generator: `file_that_has_not_passed_lint()`
    // predicate: `check(file) == failed`
    #[test]
    fn precondition_violation_rejected(v0 in spec_gen::file_that_has_not_passed_lint()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: toml_roundtrips
    // generator: `arbitrary_constraint_row()`
    // predicate: `parse_toml(compile(row)) == row`
    #[test]
    fn toml_roundtrips(v0 in spec_gen::arbitrary_constraint_row()) {
        todo_predicate!("`parse_toml(compile(row)) == row`");
    }
}

proptest! {
    // id: tla_disjunct_count_matches
    // generator: `arbitrary_model_section(n_transitions)`
    // predicate: `count(disjuncts(compile(model).Next)) == n_transitions + 1` — the closing stuttering disjunct
    #[test]
    fn tla_disjunct_count_matches(v0 in spec_gen::arbitrary_model_section()) {
        todo_predicate!("`count(disjuncts(compile(model).Next)) == n_transitions + 1` — the closing stuttering disjunct");
    }
}

proptest! {
    // id: output_function_covers_emitting_states_only
    // generator: `arbitrary_model_section(n_states_with_emits, n_states_without)`
    // predicate: `domain(compile(model).Output) == the_states_with_emits` — no entry for the rest
    #[test]
    fn output_function_covers_emitting_states_only(v0 in spec_gen::arbitrary_model_section()) {
        todo_predicate!("`domain(compile(model).Output) == the_states_with_emits` — no entry for the rest");
    }
}

proptest! {
    // id: proptest_block_per_property
    // generator: `arbitrary_property_row()`
    // predicate: `count(compile(row).blocks) ≥ 1`
    #[test]
    fn proptest_block_per_property(v0 in spec_gen::arbitrary_property_row()) {
        todo_predicate!("`count(compile(row).blocks) ≥ 1`");
    }
}

proptest! {
    // id: law_property_compiles_required_cases
    // generator: `law_property_row_with(cases: ["identity", "associativity"])`
    // predicate: `count(compile(row).blocks) == 2`
    #[test]
    fn law_property_compiles_required_cases(v0 in spec_gen::law_property_row_with()) {
        todo_predicate!("`count(compile(row).blocks) == 2`");
    }
}

proptest! {
    // id: compile_completes_or_fails_cleanly
    // generator: `arbitrary_linted_and_covered_file()`
    // predicate: `compile(file) ∈ {all_three_artifacts, single_labeled_failure}` — never partial
    #[test]
    fn compile_completes_or_fails_cleanly(v0 in spec_gen::arbitrary_linted_and_covered_file()) {
        todo_predicate!("`compile(file) ∈ {all_three_artifacts, single_labeled_failure}` — never partial");
    }
}

proptest! {
    // id: id_preservation_holds
    // generator: `arbitrary_linted_and_covered_file()`
    // predicate: `ids_in(file) ⊆ ids_in(compile(file))`
    #[test]
    fn id_preservation_holds(v0 in spec_gen::arbitrary_linted_and_covered_file()) {
        todo_predicate!("`ids_in(file) ⊆ ids_in(compile(file))`");
    }
}

proptest! {
    // id: roundtrip_stable
    // generator: `arbitrary_linted_and_covered_file()`
    // predicate: `compile(file) == compile(parse(compile(file)))`
    #[test]
    fn roundtrip_stable(v0 in spec_gen::arbitrary_linted_and_covered_file()) {
        todo_predicate!("`compile(file) == compile(parse(compile(file)))`");
    }
}

proptest! {
    // id: extraction_failure_label_asserted
    // generator: `extraction_stage_fails_on_row()`
    // predicate: `error_label == "compile.extraction_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn extraction_failure_label_asserted(v0 in spec_gen::extraction_stage_fails_on_row()) {
        todo_predicate!("`error_label == \"compile.extraction_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
}

proptest! {
    // id: emission_failure_label_asserted
    // generator: `emission_stage_fails()`
    // predicate: `error_label == "compile.emission_failure"` — same three-site rename rule (EDGE-002)
    #[test]
    fn emission_failure_label_asserted(v0 in spec_gen::emission_stage_fails()) {
        todo_predicate!("`error_label == \"compile.emission_failure\"` — same three-site rename rule (EDGE-002)");
    }
}

proptest! {
    // id: fragment_body_emitted_verbatim
    // generator: `property_row_with_rust_fragment()`
    // predicate: `the emitted block body contains the fragment verbatim`
    #[test]
    fn fragment_body_emitted_verbatim(v0 in spec_gen::property_row_with_rust_fragment()) {
        todo_predicate!("`the emitted block body contains the fragment verbatim`");
    }
}

proptest! {
    // id: prose_predicate_stays_placeholder
    // generator: `property_row_without_fragment()`
    // predicate: `compile(row).body contains todo_predicate!` — no widening of pre-Revision behavior
    #[test]
    fn prose_predicate_stays_placeholder(v0 in spec_gen::property_row_without_fragment()) {
        todo_predicate!("`compile(row).body contains todo_predicate!` — no widening of pre-Revision behavior");
    }
}

proptest! {
    // id: fragment_values_bind_generators
    // generator: `property_row_with_two_generators()`
    // predicate: `the emitted block's args are v0, v1 — one per named generator, each a String`
    #[test]
    fn fragment_values_bind_generators(v0 in spec_gen::property_row_with_two_generators()) {
        todo_predicate!("`the emitted block's args are v0, v1 — one per named generator, each a String`");
    }
}

proptest! {
    // id: law_fragment_labeled
    // generator: `law_row_with_fragment()`
    // predicate: `error_stage == fragment_extraction`
    #[test]
    fn law_fragment_labeled(v0 in spec_gen::law_row_with_fragment()) {
        todo_predicate!("`error_stage == fragment_extraction`");
    }
}

proptest! {
    // id: hygiene_violation_labeled
    // generator: `fragment_with(banned_token: "std::fs")`
    // predicate: `error_stage == fragment_extraction ∧ message names the token`
    #[test]
    fn hygiene_violation_labeled(v0 in spec_gen::fragment_with()) {
        todo_predicate!("`error_stage == fragment_extraction ∧ message names the token`");
    }
}

proptest! {
    // id: guard_fragment_labeled
    // generator: `transition_row_with_fragment_guard()`
    // predicate: `error_stage == fragment_extraction`
    #[test]
    fn guard_fragment_labeled(v0 in spec_gen::transition_row_with_fragment_guard()) {
        todo_predicate!("`error_stage == fragment_extraction`");
    }
}

proptest! {
    // id: non_invariant_fragment_labeled
    // generator: `effect_row_with_fragment()`
    // predicate: `error_stage == fragment_extraction`
    #[test]
    fn non_invariant_fragment_labeled(v0 in spec_gen::effect_row_with_fragment()) {
        todo_predicate!("`error_stage == fragment_extraction`");
    }
}

