---- MODULE compile ----
\* Generated by `spk compile` from spec `compile` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"not_started", "extracting", "emitting", "compiled", "extract_failed", "emit_failed"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "not_started"

Next ==
  \* begin: not_started -> extracting (guard: [[compile.precondition_satisfied]])
  \/ vpc = "not_started" /\ vpc' = "extracting"
  \* extract_ok: extracting -> emitting (guard: [[compile.constraint_table_to_toml]] ∧ [[compile.model_to_tla]] ∧ [[compile.properties_to_proptest]])
  \/ vpc = "extracting" /\ vpc' = "emitting"
  \* extract_fail: extracting -> extract_failed (guard: `¬([[compile.constraint_table_to_toml]] ∧ [[compile.model_to_tla]] ∧ [[compile.properties_to_proptest]])`)
  \/ vpc = "extracting" /\ vpc' = "extract_failed"
  \* accept: emitting -> compiled (guard: [[compile.compile_preserves_ids]] ∧ [[compile.no_semantic_drift]])
  \/ vpc = "emitting" /\ vpc' = "compiled"
  \* reject: emitting -> emit_failed (guard: `¬([[compile.compile_preserves_ids]] ∧ [[compile.no_semantic_drift]])`)
  \/ vpc = "emitting" /\ vpc' = "emit_failed"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* One entry per state with an `emits` field — domain is exactly
\* the emitting states; each value is the effect-Constraint's expr.
Output ==
"emit_failed" :> "`compile.emission_failure(detail) — the emission stage failed because detail`" @@
"extract_failed" :> "`compile.extraction_failure(row_id, reason) — the extraction stage failed on row row_id because reason`"

============================================================================
