---- MODULE errors ----
\* Generated by `spk compile` from spec `errors` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"draft", "published"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "draft"

Next ==
  \* publish: draft -> published (guard: [[errors.contract_published]] — the rows exist here, extension_point-kind, and only here)
  \/ vpc = "draft" /\ vpc' = "published"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
