//! proptest scaffolding for `graph` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// Each yields a String (the generator's name; executable
/// fragments bind these directly — Revision 15).
pub mod spec_gen {
    use super::*;

    pub fn arbitrary_spec_repo() -> impl Strategy<Value = String> {
        Just("arbitrary_spec_repo".into())
    }

    pub fn hand_inserted_edge() -> impl Strategy<Value = String> {
        Just("hand_inserted_edge".into())
    }

    pub fn run_extraction_twice_against_unchanged_repo() -> impl Strategy<Value = String> {
        Just("run_extraction_twice_against_unchanged_repo".into())
    }

    pub fn chain() -> impl Strategy<Value = String> {
        Just("chain".into())
    }

    pub fn edge() -> impl Strategy<Value = String> {
        Just("edge".into())
    }

    pub fn edit_one_reference_field_without_re_extracting() -> impl Strategy<Value = String> {
        Just("edit_one_reference_field_without_re_extracting".into())
    }

    pub fn graph_artifact_with_a_manually_inserted_edge_absent_from_any_file() -> impl Strategy<Value = String> {
        Just("graph_artifact_with_a_manually_inserted_edge_absent_from_any_file".into())
    }

    pub fn file_hosting_extension_point_row_then_all_removed() -> impl Strategy<Value = String> {
        Just("file_hosting_extension_point_row_then_all_removed".into())
    }

    pub fn constraint_row_carrying_observes_pointing_at_effect() -> impl Strategy<Value = String> {
        Just("constraint_row_carrying_observes_pointing_at_effect".into())
    }

    pub fn extraction_failure_raised() -> impl Strategy<Value = String> {
        Just("extraction_failure_raised".into())
    }

}

proptest! {
    // id: every_edge_extracted
    // generator: `arbitrary_spec_repo()`
    // predicate: `count(edges(graph)) == count(reference_field_instances(repo))`
    #[test]
    fn every_edge_extracted(v0 in spec_gen::arbitrary_spec_repo()) {
        todo_predicate!("`count(edges(graph)) == count(reference_field_instances(repo))`");
    }
    // id: wrongly_typed_edge_rejected
    // generator: `hand_inserted_edge(source_kind: State, field: "guard", target_kind: Property)`
    // predicate: `check(artifact) == rejected` — `guard` targets an invariant Constraint or a State (specodelic.md Revision 12); a Property target is still rejected
    #[test]
    fn wrongly_typed_edge_rejected(v0 in spec_gen::hand_inserted_edge()) {
        todo_predicate!("`check(artifact) == rejected` — `guard` targets an invariant Constraint or a State (specodelic.md Revision 12); a Property target is still rejected");
    }
    // id: rerun_deterministic
    // generator: `run_extraction_twice_against_unchanged_repo()`
    // predicate: `artifact(run_1) == artifact(run_2)`
    #[test]
    fn rerun_deterministic(v0 in spec_gen::run_extraction_twice_against_unchanged_repo()) {
        todo_predicate!("`artifact(run_1) == artifact(run_2)`");
    }
    // id: blast_radius_transitive
    // generator: `chain(a traces_to b, b derives_from c)`
    // predicate: `c ∈ blast_radius(a)` — reachable through two hops, no direct edge required
    #[test]
    fn blast_radius_transitive(v0 in spec_gen::chain()) {
        todo_predicate!("`c ∈ blast_radius(a)` — reachable through two hops, no direct edge required");
    }
    // id: blast_radius_bidirectional
    // generator: `edge(a → b)`
    // predicate: `a ∈ blast_radius(b) ∧ b ∈ blast_radius(a)` — renaming `a` must be able to find dependent `b`, and vice versa
    #[test]
    fn blast_radius_bidirectional(v0 in spec_gen::edge()) {
        todo_predicate!("`a ∈ blast_radius(b) ∧ b ∈ blast_radius(a)` — renaming `a` must be able to find dependent `b`, and vice versa");
    }
    // id: stale_detected_on_edit
    // generator: `edit_one_reference_field_without_re_extracting()`
    // predicate: `check(artifact) == stale`
    #[test]
    fn stale_detected_on_edit(v0 in spec_gen::edit_one_reference_field_without_re_extracting()) {
        todo_predicate!("`check(artifact) == stale`");
    }
    // id: hand_authored_edge_rejected
    // generator: `graph_artifact_with_a_manually_inserted_edge_absent_from_any_file()`
    // predicate: `check(artifact) == rejected`
    #[test]
    fn hand_authored_edge_rejected(v0 in spec_gen::graph_artifact_with_a_manually_inserted_edge_absent_from_any_file()) {
        todo_predicate!("`check(artifact) == rejected`");
    }
    // id: boundary_tracks_extension_points
    // generator: `file_hosting_extension_point_row_then_all_removed()`
    // predicate: `classified(file) == true before, == false after removal — no authored residue`
    #[test]
    fn boundary_tracks_extension_points(v0 in spec_gen::file_hosting_extension_point_row_then_all_removed()) {
        todo_predicate!("`classified(file) == true before, == false after removal — no authored residue`");
    }
    // id: observes_edge_extracted
    // generator: `constraint_row_carrying_observes_pointing_at_effect()`
    // predicate: `exactly one edge, kind constraints.observes — and zero edges when the column is absent`
    #[test]
    fn observes_edge_extracted(v0 in spec_gen::constraint_row_carrying_observes_pointing_at_effect()) {
        todo_predicate!("`exactly one edge, kind constraints.observes — and zero edges when the column is absent`");
    }
    // id: extraction_failure_label_asserted
    // generator: `extraction_failure_raised()`
    // predicate: `error_label == "graph.extraction_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn extraction_failure_label_asserted(v0 in spec_gen::extraction_failure_raised()) {
        todo_predicate!("`error_label == \"graph.extraction_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
}

