-----------------------------------------
MODULE graph
-----------------------------------------
\* Generated by `spk compile` from spec `graph` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"unindexed", "extracting", "indexed", "queryable", "failed"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

Init == vpc = "unindexed"

Next ==
  \* extract: unindexed -> extracting (guard: `every file in the repo has independently reached parsed` — see [[specodelic]]'s own lifecycle)
  \/ vpc = "unindexed" /\ vpc' = "extracting"
  \* extract_ok: extracting -> indexed (guard: [[graph.total_extraction]] ∧ [[graph.edge_kind_matches_typing]])
  \/ vpc = "extracting" /\ vpc' = "indexed"
  \* extract_fail: extracting -> failed (guard: `¬extract_ok.guard`)
  \/ vpc = "extracting" /\ vpc' = "failed"
  \* publish: indexed -> queryable (guard: [[graph.deterministic_derivation]] ∧ [[graph.graph_is_derived_not_authored]])
  \/ vpc = "indexed" /\ vpc' = "queryable"
  \* invalidate: queryable -> unindexed (guard: [[graph.stale_graph_detected]])
  \/ vpc = "queryable" /\ vpc' = "unindexed"

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
