//! proptest scaffolding for `graph` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// The real element types and strategies are `verify`'s domain.
pub mod spec_gen {
    use super::*;

    pub fn arbitrary_spec_repo() -> impl Strategy<Value = GenVal> {
        Just(GenVal("arbitrary_spec_repo".into()))
    }

    pub fn hand_inserted_edge() -> impl Strategy<Value = GenVal> {
        Just(GenVal("hand_inserted_edge".into()))
    }

    pub fn run_extraction_twice_against_unchanged_repo() -> impl Strategy<Value = GenVal> {
        Just(GenVal("run_extraction_twice_against_unchanged_repo".into()))
    }

    pub fn chain() -> impl Strategy<Value = GenVal> {
        Just(GenVal("chain".into()))
    }

    pub fn edge() -> impl Strategy<Value = GenVal> {
        Just(GenVal("edge".into()))
    }

    pub fn edit_one_reference_field_without_re_extracting() -> impl Strategy<Value = GenVal> {
        Just(GenVal("edit_one_reference_field_without_re_extracting".into()))
    }

    pub fn graph_artifact_with_a_manually_inserted_edge_absent_from_any_file() -> impl Strategy<Value = GenVal> {
        Just(GenVal("graph_artifact_with_a_manually_inserted_edge_absent_from_any_file".into()))
    }

}

proptest! {
    // id: every_edge_extracted
    // generator: `arbitrary_spec_repo()`
    // predicate: `count(edges(graph)) == count(reference_field_instances(repo))`
    #[test]
    fn every_edge_extracted(v0 in spec_gen::arbitrary_spec_repo()) {
        todo_predicate!("`count(edges(graph)) == count(reference_field_instances(repo))`");
    }
}

proptest! {
    // id: wrongly_typed_edge_rejected
    // generator: `hand_inserted_edge(source_kind: State, field: "guard", target_kind: State)`
    // predicate: `check(artifact) == rejected` — `guard` never targets a State per the Reference Typing table
    #[test]
    fn wrongly_typed_edge_rejected(v0 in spec_gen::hand_inserted_edge()) {
        todo_predicate!("`check(artifact) == rejected` — `guard` never targets a State per the Reference Typing table");
    }
}

proptest! {
    // id: rerun_deterministic
    // generator: `run_extraction_twice_against_unchanged_repo()`
    // predicate: `artifact(run_1) == artifact(run_2)`
    #[test]
    fn rerun_deterministic(v0 in spec_gen::run_extraction_twice_against_unchanged_repo()) {
        todo_predicate!("`artifact(run_1) == artifact(run_2)`");
    }
}

proptest! {
    // id: blast_radius_transitive
    // generator: `chain(a traces_to b, b derives_from c)`
    // predicate: `c ∈ blast_radius(a)` — reachable through two hops, no direct edge required
    #[test]
    fn blast_radius_transitive(v0 in spec_gen::chain()) {
        todo_predicate!("`c ∈ blast_radius(a)` — reachable through two hops, no direct edge required");
    }
}

proptest! {
    // id: blast_radius_bidirectional
    // generator: `edge(a → b)`
    // predicate: `a ∈ blast_radius(b) ∧ b ∈ blast_radius(a)` — renaming `a` must be able to find dependent `b`, and vice versa
    #[test]
    fn blast_radius_bidirectional(v0 in spec_gen::edge()) {
        todo_predicate!("`a ∈ blast_radius(b) ∧ b ∈ blast_radius(a)` — renaming `a` must be able to find dependent `b`, and vice versa");
    }
}

proptest! {
    // id: stale_detected_on_edit
    // generator: `edit_one_reference_field_without_re_extracting()`
    // predicate: `check(artifact) == stale`
    #[test]
    fn stale_detected_on_edit(v0 in spec_gen::edit_one_reference_field_without_re_extracting()) {
        todo_predicate!("`check(artifact) == stale`");
    }
}

proptest! {
    // id: hand_authored_edge_rejected
    // generator: `graph_artifact_with_a_manually_inserted_edge_absent_from_any_file()`
    // predicate: `check(artifact) == rejected`
    #[test]
    fn hand_authored_edge_rejected(v0 in spec_gen::graph_artifact_with_a_manually_inserted_edge_absent_from_any_file()) {
        todo_predicate!("`check(artifact) == rejected`");
    }
}

