---- MODULE graph ----
\* Generated by `spk compile` from spec `graph` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"unindexed", "extracting", "indexed", "queryable", "failed"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "unindexed"

Next ==
  \* extract: unindexed -> extracting (guard: `[[specodelic.parsed]]` — every file in the repo has independently reached that state (see `specodelic.md`'s own lifecycle))
  \/ vpc = "unindexed" /\ vpc' = "extracting"
  \* extract_ok: extracting -> indexed (guard: [[graph.total_extraction]] ∧ [[graph.edge_kind_matches_typing]])
  \/ vpc = "extracting" /\ vpc' = "indexed"
  \* extract_fail: extracting -> failed (guard: `¬([[graph.total_extraction]] ∧ [[graph.edge_kind_matches_typing]])`)
  \/ vpc = "extracting" /\ vpc' = "failed"
  \* publish: indexed -> queryable (guard: [[graph.deterministic_derivation]] ∧ [[graph.graph_is_derived_not_authored]])
  \/ vpc = "indexed" /\ vpc' = "queryable"
  \* invalidate: queryable -> unindexed (guard: [[graph.stale_graph_detected]])
  \/ vpc = "queryable" /\ vpc' = "unindexed"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* One entry per state with an `emits` field — domain is exactly
\* the emitting states; each value is the effect-Constraint's expr.
Output ==
"failed" :> "`graph.extraction_failure(detail)`"

============================================================================
