//! proptest scaffolding for `kinds` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// The real element types and strategies are `verify`'s domain.
pub mod spec_gen {
    use super::*;

    pub fn row_belonging_to_a_sixth_section() -> impl Strategy<Value = GenVal> {
        Just(GenVal("row_belonging_to_a_sixth_section".into()))
    }

    pub fn intent_row_without() -> impl Strategy<Value = GenVal> {
        Just(GenVal("intent_row_without".into()))
    }

    pub fn constraint_row_with() -> impl Strategy<Value = GenVal> {
        Just(GenVal("constraint_row_with".into()))
    }

    pub fn state_row_with() -> impl Strategy<Value = GenVal> {
        Just(GenVal("state_row_with".into()))
    }

    pub fn transition_row_without() -> impl Strategy<Value = GenVal> {
        Just(GenVal("transition_row_without".into()))
    }

    pub fn property_row_with() -> impl Strategy<Value = GenVal> {
        Just(GenVal("property_row_with".into()))
    }

    pub fn diff_adding_subkind_value_with_no_new_Revision_heading() -> impl Strategy<Value = GenVal> {
        Just(GenVal("diff_adding_subkind_value_with_no_new_Revision_heading".into()))
    }

    pub fn arbitrary_well_formed_row_of_one_kind() -> impl Strategy<Value = GenVal> {
        Just(GenVal("arbitrary_well_formed_row_of_one_kind".into()))
    }

    pub fn arbitrary_row_of_one_kind() -> impl Strategy<Value = GenVal> {
        Just(GenVal("arbitrary_row_of_one_kind".into()))
    }

    pub fn arbitrary_id_rename() -> impl Strategy<Value = GenVal> {
        Just(GenVal("arbitrary_id_rename".into()))
    }

    pub fn kind_assignment_failure_raised() -> impl Strategy<Value = GenVal> {
        Just(GenVal("kind_assignment_failure_raised".into()))
    }

    pub fn shape_check_failure_raised() -> impl Strategy<Value = GenVal> {
        Just(GenVal("shape_check_failure_raised".into()))
    }

}

proptest! {
    // id: unknown_kind_rejected
    // generator: `row_belonging_to_a_sixth_section("Actions")`
    // predicate: `check(row) == failed`
    #[test]
    fn unknown_kind_rejected(v0 in spec_gen::row_belonging_to_a_sixth_section()) {
        todo_predicate!("`check(row) == failed`");
    }
}

proptest! {
    // id: intent_missing_statement_rejected
    // generator: `intent_row_without("statement")`
    // predicate: `check(row) == failed`
    #[test]
    fn intent_missing_statement_rejected(v0 in spec_gen::intent_row_without()) {
        todo_predicate!("`check(row) == failed`");
    }
}

proptest! {
    // id: constraint_row_extra_field_rejected
    // generator: `constraint_row_with(extra_field: "guard")`
    // predicate: `check(row) == failed`
    #[test]
    fn constraint_row_extra_field_rejected(v0 in spec_gen::constraint_row_with()) {
        todo_predicate!("`check(row) == failed`");
    }
}

proptest! {
    // id: state_row_with_extra_field_rejected
    // generator: `state_row_with(extra_field: "kind")`
    // predicate: `check(row) == failed`
    #[test]
    fn state_row_with_extra_field_rejected(v0 in spec_gen::state_row_with()) {
        todo_predicate!("`check(row) == failed`");
    }
}

proptest! {
    // id: transition_missing_guard_rejected
    // generator: `transition_row_without("guard")`
    // predicate: `check(row) == failed`
    #[test]
    fn transition_missing_guard_rejected(v0 in spec_gen::transition_row_without()) {
        todo_predicate!("`check(row) == failed`");
    }
}

proptest! {
    // id: property_row_bad_subkind_rejected
    // generator: `property_row_with(kind: "audit")`
    // predicate: `check(row) == failed`
    #[test]
    fn property_row_bad_subkind_rejected(v0 in spec_gen::property_row_with()) {
        todo_predicate!("`check(row) == failed`");
    }
}

proptest! {
    // id: subkind_addition_without_revision_rejected
    // generator: `diff_adding_subkind_value_with_no_new_Revision_heading()`
    // predicate: `check(diff) == failed`
    #[test]
    fn subkind_addition_without_revision_rejected(v0 in spec_gen::diff_adding_subkind_value_with_no_new_Revision_heading()) {
        todo_predicate!("`check(diff) == failed`");
    }
}

proptest! {
    // id: constraint_row_advisory_accepted
    // generator: `constraint_row_with(kind: "advisory")`
    // predicate: `check(row) == passed`
    #[test]
    fn constraint_row_advisory_accepted(v0 in spec_gen::constraint_row_with()) {
        todo_predicate!("`check(row) == passed`");
    }
}

proptest! {
    // id: constraint_row_effect_accepted
    // generator: `constraint_row_with(kind: "effect")`
    // predicate: `check(row) == passed`
    #[test]
    fn constraint_row_effect_accepted(v0 in spec_gen::constraint_row_with()) {
        todo_predicate!("`check(row) == passed`");
    }
}

proptest! {
    // id: state_row_emits_accepted
    // generator: `state_row_with(emits: an_effect_kind_constraint_id)`
    // predicate: `check(row) == passed`
    #[test]
    fn state_row_emits_accepted(v0 in spec_gen::state_row_with()) {
        todo_predicate!("`check(row) == passed`");
    }
}

proptest! {
    // id: state_row_without_emits_still_passes
    // generator: `state_row_with(fields: {id})` — no `emits`
    // predicate: `check(row) == passed` — `emits` is optional, not a second required field
    #[test]
    fn state_row_without_emits_still_passes(v0 in spec_gen::state_row_with()) {
        todo_predicate!("`check(row) == passed` — `emits` is optional, not a second required field");
    }
}

proptest! {
    // id: state_row_emits_wrong_kind_rejected
    // generator: `state_row_with(emits: an_invariant_kind_constraint_id)`
    // predicate: `check(row) == failed`
    #[test]
    fn state_row_emits_wrong_kind_rejected(v0 in spec_gen::state_row_with()) {
        todo_predicate!("`check(row) == failed`");
    }
}

proptest! {
    // id: constraint_row_extension_point_accepted
    // generator: `constraint_row_with(kind: "extension_point")`
    // predicate: `check(row) == passed`
    #[test]
    fn constraint_row_extension_point_accepted(v0 in spec_gen::constraint_row_with()) {
        todo_predicate!("`check(row) == passed`");
    }
}

proptest! {
    // id: well_formed_row_passes
    // generator: `arbitrary_well_formed_row_of_one_kind()`
    // predicate: `check(row) == passed`
    #[test]
    fn well_formed_row_passes(v0 in spec_gen::arbitrary_well_formed_row_of_one_kind()) {
        todo_predicate!("`check(row) == passed`");
    }
}

proptest! {
    // id: kind_shape_naturality
    // case: identity
    // generator: `arbitrary_row_of_one_kind(), arbitrary_id_rename()`
    // predicate: **identity:** `assigned_kind(rename(row,a,a)) == assigned_kind(row)`  **associativity:** `assigned_kind(rename(rename(row,a,b),b,c)) == assigned_kind(rename(row,a,c))` — renaming a row's id never changes which of the five kinds it belongs to
    #[test]
    fn kind_shape_naturality_identity(v0 in spec_gen::arbitrary_row_of_one_kind(), v1 in spec_gen::arbitrary_id_rename()) {
        todo_predicate!("**identity:** `assigned_kind(rename(row,a,a)) == assigned_kind(row)`  **associativity:** `assigned_kind(rename(rename(row,a,b),b,c)) == assigned_kind(rename(row,a,c))` — renaming a row's id never changes which of the five kinds it belongs to");
    }
}

proptest! {
    // id: kind_shape_naturality
    // case: associativity
    // generator: `arbitrary_row_of_one_kind(), arbitrary_id_rename()`
    // predicate: **identity:** `assigned_kind(rename(row,a,a)) == assigned_kind(row)`  **associativity:** `assigned_kind(rename(rename(row,a,b),b,c)) == assigned_kind(rename(row,a,c))` — renaming a row's id never changes which of the five kinds it belongs to
    #[test]
    fn kind_shape_naturality_associativity(v0 in spec_gen::arbitrary_row_of_one_kind(), v1 in spec_gen::arbitrary_id_rename()) {
        todo_predicate!("**identity:** `assigned_kind(rename(row,a,a)) == assigned_kind(row)`  **associativity:** `assigned_kind(rename(rename(row,a,b),b,c)) == assigned_kind(rename(row,a,c))` — renaming a row's id never changes which of the five kinds it belongs to");
    }
}

proptest! {
    // id: kind_assignment_failure_label_asserted
    // generator: `kind_assignment_failure_raised()`
    // predicate: `error_label == "kinds.kind_assignment_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn kind_assignment_failure_label_asserted(v0 in spec_gen::kind_assignment_failure_raised()) {
        todo_predicate!("`error_label == \"kinds.kind_assignment_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
}

proptest! {
    // id: shape_check_failure_label_asserted
    // generator: `shape_check_failure_raised()`
    // predicate: `error_label == "kinds.shape_check_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn shape_check_failure_label_asserted(v0 in spec_gen::shape_check_failure_raised()) {
        todo_predicate!("`error_label == \"kinds.shape_check_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
}

