---- MODULE kinds ----
\* Generated by `spk compile` from spec `kinds` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"unclassified", "kind_assigned", "shape_checked", "passed", "failed"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "unclassified"

Next ==
  \* begin: unclassified -> kind_assigned (guard: `row belongs to exactly one of the five sections (frontmatter / Constraints table / Model States / Model Transitions / Properties table)`)
  \/ vpc = "unclassified" /\ vpc' = "kind_assigned"
  \* assign_ok: kind_assigned -> shape_checked (guard: [[kinds.kind_enum_closed]])
  \/ vpc = "kind_assigned" /\ vpc' = "shape_checked"
  \* assign_fail: kind_assigned -> failed (guard: `¬assign_ok.guard`)
  \/ vpc = "kind_assigned" /\ vpc' = "failed"
  \* accept: shape_checked -> passed (guard: `(row.kind==Intent ∧ [[kinds.intent_row_shape]]) ∨ (row.kind==Constraint ∧ [[kinds.constraint_row_shape]]) ∨ (row.kind==State ∧ [[kinds.state_row_shape]]) ∨ (row.kind==Transition ∧ [[kinds.transition_row_shape]]) ∨ (row.kind==Property ∧ [[kinds.property_row_shape]])`)
  \/ vpc = "shape_checked" /\ vpc' = "passed"
  \* reject: shape_checked -> failed (guard: `¬accept.guard`)
  \/ vpc = "shape_checked" /\ vpc' = "failed"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
