//! proptest scaffolding for `linter.frontmatter` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// Each yields a String (the generator's name; executable
/// fragments bind these directly — Revision 15).
pub mod spec_gen {
    use super::*;

    pub fn frontmatter_without() -> impl Strategy<Value = String> {
        Just("frontmatter_without".into())
    }

    pub fn frontmatter_with_kind() -> impl Strategy<Value = String> {
        Just("frontmatter_with_kind".into())
    }

    pub fn arbitrary_valid_frontmatter() -> impl Strategy<Value = String> {
        Just("arbitrary_valid_frontmatter".into())
    }

    pub fn stem() -> impl Strategy<Value = String> {
        Just("stem".into())
    }

    pub fn frontmatter_with() -> impl Strategy<Value = String> {
        Just("frontmatter_with".into())
    }

    pub fn check_failure_raised() -> impl Strategy<Value = String> {
        Just("check_failure_raised".into())
    }

}

proptest! {
    // id: missing_id_rejected
    // generator: `frontmatter_without("id")`
    // predicate: `check(frontmatter) == failed`
    #[test]
    fn missing_id_rejected(v0 in spec_gen::frontmatter_without()) {
        todo_predicate!("`check(frontmatter) == failed`");
    }
    // id: wrong_kind_rejected
    // generator: `frontmatter_with_kind(≠ "intent")`
    // predicate: `check(frontmatter) == failed`
    #[test]
    fn wrong_kind_rejected(v0 in spec_gen::frontmatter_with_kind()) {
        todo_predicate!("`check(frontmatter) == failed`");
    }
    // id: valid_passes
    // generator: `arbitrary_valid_frontmatter()`
    // predicate: `check(frontmatter) == passed`
    #[test]
    fn valid_passes(v0 in spec_gen::arbitrary_valid_frontmatter()) {
        todo_predicate!("`check(frontmatter) == passed`");
    }
    // id: filename_mismatch
    // generator: `(id, filename)` pairs where `id ≠ stem(filename)`
    // predicate: `check(id, filename) == failed`
    #[test]
    fn filename_mismatch(v0 in spec_gen::stem()) {
        todo_predicate!("`check(id, filename) == failed`");
    }
    // id: missing_statement_rejected
    // generator: `frontmatter_without("statement")` and `frontmatter_with(statement: "")`
    // predicate: `check(frontmatter) == failed` — absent and empty are both rejections
    #[test]
    fn missing_statement_rejected(v0 in spec_gen::frontmatter_without(), v1 in spec_gen::frontmatter_with()) {
        todo_predicate!("`check(frontmatter) == failed` — absent and empty are both rejections");
    }
    // id: check_failure_label_asserted
    // generator: `check_failure_raised()`
    // predicate: `error_label == "linter.frontmatter.check_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn check_failure_label_asserted(v0 in spec_gen::check_failure_raised()) {
        todo_predicate!("`error_label == \"linter.frontmatter.check_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
}

