//! proptest scaffolding for `linter.referential_integrity` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// The real element types and strategies are `verify`'s domain.
pub mod spec_gen {
    use super::*;

    pub fn spec_file_with() -> impl Strategy<Value = GenVal> {
        Just(GenVal("spec_file_with".into()))
    }

    pub fn two_spec_files_sharing_id() -> impl Strategy<Value = GenVal> {
        Just(GenVal("two_spec_files_sharing_id".into()))
    }

    pub fn guard_field_pointing_at_a_property_row() -> impl Strategy<Value = GenVal> {
        Just(GenVal("guard_field_pointing_at_a_property_row".into()))
    }

    pub fn arbitrary_spec_repo() -> impl Strategy<Value = GenVal> {
        Just(GenVal("arbitrary_spec_repo".into()))
    }

    pub fn arbitrary_id_rename() -> impl Strategy<Value = GenVal> {
        Just(GenVal("arbitrary_id_rename".into()))
    }

    pub fn arbitrary_well_formed_repo() -> impl Strategy<Value = GenVal> {
        Just(GenVal("arbitrary_well_formed_repo".into()))
    }

    pub fn index_failure_raised() -> impl Strategy<Value = GenVal> {
        Just(GenVal("index_failure_raised".into()))
    }

    pub fn resolution_failure_raised() -> impl Strategy<Value = GenVal> {
        Just(GenVal("resolution_failure_raised".into()))
    }

}

proptest! {
    // id: duplicate_id_rejected
    // generator: `spec_file_with(duplicate_row_id: true)`
    // predicate: `check(file) == failed`
    #[test]
    fn duplicate_id_rejected(v0 in spec_gen::spec_file_with()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: cross_file_collision
    // generator: `two_spec_files_sharing_id()`
    // predicate: `check(repo) == failed`
    #[test]
    fn cross_file_collision(v0 in spec_gen::two_spec_files_sharing_id()) {
        todo_predicate!("`check(repo) == failed`");
    }
}

proptest! {
    // id: dangling_ref_rejected
    // generator: `spec_file_with(ref_to_nonexistent_id: true)`
    // predicate: `check(file) == failed`
    #[test]
    fn dangling_ref_rejected(v0 in spec_gen::spec_file_with()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: wrong_target_kind
    // generator: `guard_field_pointing_at_a_property_row()`
    // predicate: `check(file) == failed`
    #[test]
    fn wrong_target_kind(v0 in spec_gen::guard_field_pointing_at_a_property_row()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: rename_naturality
    // case: identity
    // generator: `arbitrary_spec_repo(), arbitrary_id_rename()`
    // predicate: **identity:** `resolve(rename(I,a,a)) == resolve(I)`  **associativity:** `resolve(rename(rename(I,a,b),b,c)) == resolve(rename(I,a,c))`
    #[test]
    fn rename_naturality_identity(v0 in spec_gen::arbitrary_spec_repo(), v1 in spec_gen::arbitrary_id_rename()) {
        todo_predicate!("**identity:** `resolve(rename(I,a,a)) == resolve(I)`  **associativity:** `resolve(rename(rename(I,a,b),b,c)) == resolve(rename(I,a,c))`");
    }
}

proptest! {
    // id: rename_naturality
    // case: associativity
    // generator: `arbitrary_spec_repo(), arbitrary_id_rename()`
    // predicate: **identity:** `resolve(rename(I,a,a)) == resolve(I)`  **associativity:** `resolve(rename(rename(I,a,b),b,c)) == resolve(rename(I,a,c))`
    #[test]
    fn rename_naturality_associativity(v0 in spec_gen::arbitrary_spec_repo(), v1 in spec_gen::arbitrary_id_rename()) {
        todo_predicate!("**identity:** `resolve(rename(I,a,a)) == resolve(I)`  **associativity:** `resolve(rename(rename(I,a,b),b,c)) == resolve(rename(I,a,c))`");
    }
}

proptest! {
    // id: clean_repo_passes
    // generator: `arbitrary_well_formed_repo()`
    // predicate: `check(repo) == passed`
    #[test]
    fn clean_repo_passes(v0 in spec_gen::arbitrary_well_formed_repo()) {
        todo_predicate!("`check(repo) == passed`");
    }
}

proptest! {
    // id: index_failure_label_asserted
    // generator: `index_failure_raised()`
    // predicate: `error_label == "linter.referential_integrity.index_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn index_failure_label_asserted(v0 in spec_gen::index_failure_raised()) {
        todo_predicate!("`error_label == \"linter.referential_integrity.index_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
}

proptest! {
    // id: resolution_failure_label_asserted
    // generator: `resolution_failure_raised()`
    // predicate: `error_label == "linter.referential_integrity.resolution_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn resolution_failure_label_asserted(v0 in spec_gen::resolution_failure_raised()) {
        todo_predicate!("`error_label == \"linter.referential_integrity.resolution_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
}

