//! proptest scaffolding for `linter.external_completeness` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// The real element types and strategies are `verify`'s domain.
pub mod spec_gen {
    use super::*;

    pub fn checklist_item_with_no_mapping_row() -> impl Strategy<Value = GenVal> {
        Just(GenVal("checklist_item_with_no_mapping_row".into()))
    }

    pub fn mapping_row_with() -> impl Strategy<Value = GenVal> {
        Just(GenVal("mapping_row_with".into()))
    }

    pub fn two_mapping_rows_targeting_the_same_checklist_item() -> impl Strategy<Value = GenVal> {
        Just(GenVal("two_mapping_rows_targeting_the_same_checklist_item".into()))
    }

    pub fn checklist_where_every_item_has_a_covered_or_waived_mapping() -> impl Strategy<Value = GenVal> {
        Just(GenVal("checklist_where_every_item_has_a_covered_or_waived_mapping".into()))
    }

    pub fn repo_with_no_declared_checklist() -> impl Strategy<Value = GenVal> {
        Just(GenVal("repo_with_no_declared_checklist".into()))
    }

    pub fn arbitrary_repo_with_checklist() -> impl Strategy<Value = GenVal> {
        Just(GenVal("arbitrary_repo_with_checklist".into()))
    }

    pub fn arbitrary_id_rename() -> impl Strategy<Value = GenVal> {
        Just(GenVal("arbitrary_id_rename".into()))
    }

    pub fn declared_checklist_with() -> impl Strategy<Value = GenVal> {
        Just(GenVal("declared_checklist_with".into()))
    }

}

proptest! {
    // id: unmapped_item_rejected
    // generator: `checklist_item_with_no_mapping_row()`
    // predicate: `check(repo) == failed`
    #[test]
    fn unmapped_item_rejected(v0 in spec_gen::checklist_item_with_no_mapping_row()) {
        todo_predicate!("`check(repo) == failed`");
    }
}

proptest! {
    // id: dangling_mapped_id_rejected
    // generator: `mapping_row_with(status: "covered", mapped_ids: ["nonexistent.id"])`
    // predicate: `check(repo) == failed`
    #[test]
    fn dangling_mapped_id_rejected(v0 in spec_gen::mapping_row_with()) {
        todo_predicate!("`check(repo) == failed`");
    }
}

proptest! {
    // id: unrationalized_waiver_rejected
    // generator: `mapping_row_with(status: "waived", rationale: "")`
    // predicate: `check(repo) == failed`
    #[test]
    fn unrationalized_waiver_rejected(v0 in spec_gen::mapping_row_with()) {
        todo_predicate!("`check(repo) == failed`");
    }
}

proptest! {
    // id: duplicate_claim_rejected
    // generator: `two_mapping_rows_targeting_the_same_checklist_item()`
    // predicate: `check(repo) == failed`
    #[test]
    fn duplicate_claim_rejected(v0 in spec_gen::two_mapping_rows_targeting_the_same_checklist_item()) {
        todo_predicate!("`check(repo) == failed`");
    }
}

proptest! {
    // id: fully_mapped_checklist_passes
    // generator: `checklist_where_every_item_has_a_covered_or_waived_mapping()`
    // predicate: `check(repo) == passed`
    #[test]
    fn fully_mapped_checklist_passes(v0 in spec_gen::checklist_where_every_item_has_a_covered_or_waived_mapping()) {
        todo_predicate!("`check(repo) == passed`");
    }
}

proptest! {
    // id: no_checklist_not_applicable
    // generator: `repo_with_no_declared_checklist()`
    // predicate: `check(repo) == not_applicable` — distinct from `passed`, see Notes
    #[test]
    fn no_checklist_not_applicable(v0 in spec_gen::repo_with_no_declared_checklist()) {
        todo_predicate!("`check(repo) == not_applicable` — distinct from `passed`, see Notes");
    }
}

proptest! {
    // id: mapping_naturality
    // case: naturality
    // generator: `arbitrary_repo_with_checklist(), arbitrary_id_rename()`
    // predicate: **naturality:** `mapped(rename(I)) == rename(mapped(I))` — renaming a constraint or property id updates every `mapped_ids` cell claiming it, the same as any other reference
    #[test]
    fn mapping_naturality_naturality(v0 in spec_gen::arbitrary_repo_with_checklist(), v1 in spec_gen::arbitrary_id_rename()) {
        todo_predicate!("**naturality:** `mapped(rename(I)) == rename(mapped(I))` — renaming a constraint or property id updates every `mapped_ids` cell claiming it, the same as any other reference");
    }
}

proptest! {
    // id: malformed_checklist_rejected
    // generator: `declared_checklist_with(a_nested_item, an_item_missing_its_id)`
    // predicate: `check(repo) == failed`
    #[test]
    fn malformed_checklist_rejected(v0 in spec_gen::declared_checklist_with()) {
        todo_predicate!("`check(repo) == failed`");
    }
}

