//! proptest scaffolding for `linter.graph_shape` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// Each yields a String (the generator's name; executable
/// fragments bind these directly — Revision 15).
pub mod spec_gen {
    use super::*;

    pub fn spec_repo_with() -> impl Strategy<Value = String> {
        Just("spec_repo_with".into())
    }

    pub fn spec_row_with() -> impl Strategy<Value = String> {
        Just("spec_row_with".into())
    }

    pub fn arbitrary_dag_shaped_repo() -> impl Strategy<Value = String> {
        Just("arbitrary_dag_shaped_repo".into())
    }

    pub fn arbitrary_dag_repo() -> impl Strategy<Value = String> {
        Just("arbitrary_dag_repo".into())
    }

    pub fn arbitrary_id_rename() -> impl Strategy<Value = String> {
        Just("arbitrary_id_rename".into())
    }

    pub fn check_failure_raised() -> impl Strategy<Value = String> {
        Just("check_failure_raised".into())
    }

}

proptest! {
    // id: cycle_rejected
    // generator: `spec_repo_with(traces_to_cycle: length ≥ 2)`
    // predicate: `check(repo) == failed`
    #[test]
    fn cycle_rejected(v0 in spec_gen::spec_repo_with()) {
        todo_predicate!("`check(repo) == failed`");
    }
    // id: self_ref_rejected
    // generator: `spec_row_with(traces_to == self.id)`
    // predicate: `check(repo) == failed`
    #[test]
    fn self_ref_rejected(v0 in spec_gen::spec_row_with()) {
        todo_predicate!("`check(repo) == failed`");
    }
    // id: orphan_subgraph_rejected
    // generator: `spec_repo_with(disconnected_constraint_cluster: true)`
    // predicate: `check(repo) == failed`
    #[test]
    fn orphan_subgraph_rejected(v0 in spec_gen::spec_repo_with()) {
        todo_predicate!("`check(repo) == failed`");
    }
    // id: dag_passes
    // generator: `arbitrary_dag_shaped_repo()`
    // predicate: `check(repo) == passed`
    #[test]
    fn dag_passes(v0 in spec_gen::arbitrary_dag_shaped_repo()) {
        todo_predicate!("`check(repo) == passed`");
    }
    // id: supersedes_cycle_rejected
    // generator: `spec_repo_with(supersedes_cycle: length ≥ 2)`
    // predicate: `check(repo) == failed`
    #[test]
    fn supersedes_cycle_rejected(v0 in spec_gen::spec_repo_with()) {
        todo_predicate!("`check(repo) == failed`");
    }
    // id: supersedes_dag_ignores_traces_cycle
    // generator: `spec_repo_with(traces_to_cycle: true, supersedes: acyclic)`
    // predicate: `check(repo).supersedes_dag == passed` — the two graphs are checked independently; a cycle in one must not be attributed to the other
    #[test]
    fn supersedes_dag_ignores_traces_cycle(v0 in spec_gen::spec_repo_with()) {
        todo_predicate!("`check(repo).supersedes_dag == passed` — the two graphs are checked independently; a cycle in one must not be attributed to the other");
    }
    // id: derives_from_edges_property_sourced
    // generator: `spec_repo_with(constraint_row_carrying_derives_from: true)`
    // predicate: `check(repo) == failed` — the malformed edge is typing's finding (the graph layer reports it and records no edge), so it joins no acyclic edge set; the invariant and the checker now agree on the same closed edge set (specodelic-huf)
    #[test]
    fn derives_from_edges_property_sourced(v0 in spec_gen::spec_repo_with()) {
        todo_predicate!("`check(repo) == failed` — the malformed edge is typing's finding (the graph layer reports it and records no edge), so it joins no acyclic edge set; the invariant and the checker now agree on the same closed edge set (specodelic-huf)");
    }
    // id: topo_sort_naturality
    // case: identity
    // generator: `arbitrary_dag_repo(), arbitrary_id_rename()`
    // predicate: **identity:** `topo_sort(rename(I, a, a)) == topo_sort(I)` — the rename identity case at the topo_sort observation point  **associativity:** `topo_sort(rename(rename(I, a, b), b, c)) == topo_sort(rename(I, a, c))` — the rename associativity case at the same point  **naturality:** `topo_sort(rename(I)) == rename(topo_sort(I))` — renaming a node doesn't change relative order of unrelated nodes
    #[test]
    fn topo_sort_naturality_identity(v0 in spec_gen::arbitrary_dag_repo(), v1 in spec_gen::arbitrary_id_rename()) {
        todo_predicate!("**identity:** `topo_sort(rename(I, a, a)) == topo_sort(I)` — the rename identity case at the topo_sort observation point  **associativity:** `topo_sort(rename(rename(I, a, b), b, c)) == topo_sort(rename(I, a, c))` — the rename associativity case at the same point  **naturality:** `topo_sort(rename(I)) == rename(topo_sort(I))` — renaming a node doesn't change relative order of unrelated nodes");
    }
    // id: topo_sort_naturality
    // case: associativity
    // generator: `arbitrary_dag_repo(), arbitrary_id_rename()`
    // predicate: **identity:** `topo_sort(rename(I, a, a)) == topo_sort(I)` — the rename identity case at the topo_sort observation point  **associativity:** `topo_sort(rename(rename(I, a, b), b, c)) == topo_sort(rename(I, a, c))` — the rename associativity case at the same point  **naturality:** `topo_sort(rename(I)) == rename(topo_sort(I))` — renaming a node doesn't change relative order of unrelated nodes
    #[test]
    fn topo_sort_naturality_associativity(v0 in spec_gen::arbitrary_dag_repo(), v1 in spec_gen::arbitrary_id_rename()) {
        todo_predicate!("**identity:** `topo_sort(rename(I, a, a)) == topo_sort(I)` — the rename identity case at the topo_sort observation point  **associativity:** `topo_sort(rename(rename(I, a, b), b, c)) == topo_sort(rename(I, a, c))` — the rename associativity case at the same point  **naturality:** `topo_sort(rename(I)) == rename(topo_sort(I))` — renaming a node doesn't change relative order of unrelated nodes");
    }
    // id: topo_sort_naturality
    // case: naturality
    // generator: `arbitrary_dag_repo(), arbitrary_id_rename()`
    // predicate: **identity:** `topo_sort(rename(I, a, a)) == topo_sort(I)` — the rename identity case at the topo_sort observation point  **associativity:** `topo_sort(rename(rename(I, a, b), b, c)) == topo_sort(rename(I, a, c))` — the rename associativity case at the same point  **naturality:** `topo_sort(rename(I)) == rename(topo_sort(I))` — renaming a node doesn't change relative order of unrelated nodes
    #[test]
    fn topo_sort_naturality_naturality(v0 in spec_gen::arbitrary_dag_repo(), v1 in spec_gen::arbitrary_id_rename()) {
        todo_predicate!("**identity:** `topo_sort(rename(I, a, a)) == topo_sort(I)` — the rename identity case at the topo_sort observation point  **associativity:** `topo_sort(rename(rename(I, a, b), b, c)) == topo_sort(rename(I, a, c))` — the rename associativity case at the same point  **naturality:** `topo_sort(rename(I)) == rename(topo_sort(I))` — renaming a node doesn't change relative order of unrelated nodes");
    }
    // id: check_failure_label_asserted
    // generator: `check_failure_raised()`
    // predicate: `error_label == "linter.graph_shape.check_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn check_failure_label_asserted(v0 in spec_gen::check_failure_raised()) {
        todo_predicate!("`error_label == \"linter.graph_shape.check_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
}

