//! proptest scaffolding for `linter.coverage` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// Each yields a String (the generator's name; executable
/// fragments bind these directly — Revision 15).
pub mod spec_gen {
    use super::*;

    pub fn spec_file_with() -> impl Strategy<Value = String> {
        Just("spec_file_with".into())
    }

    pub fn law_property_missing() -> impl Strategy<Value = String> {
        Just("law_property_missing".into())
    }

    pub fn arbitrary_fully_covered_spec_file() -> impl Strategy<Value = String> {
        Just("arbitrary_fully_covered_spec_file".into())
    }

    pub fn arbitrary_spec_file() -> impl Strategy<Value = String> {
        Just("arbitrary_spec_file".into())
    }

    pub fn arbitrary_id_rename() -> impl Strategy<Value = String> {
        Just("arbitrary_id_rename".into())
    }

    pub fn count_failure_raised() -> impl Strategy<Value = String> {
        Just("count_failure_raised".into())
    }

    pub fn law_case_failure_raised() -> impl Strategy<Value = String> {
        Just("law_case_failure_raised".into())
    }

    pub fn law_predicate_mentioning_cases_without_labels() -> impl Strategy<Value = String> {
        Just("law_predicate_mentioning_cases_without_labels".into())
    }

    pub fn law_property_with_extra_case() -> impl Strategy<Value = String> {
        Just("law_property_with_extra_case".into())
    }

}

proptest! {
    // id: uncovered_constraint_rejected
    // generator: `spec_file_with(constraint_with_no_deriving_property: true)`
    // predicate: `check(file) == failed`
    #[test]
    fn uncovered_constraint_rejected(v0 in spec_gen::spec_file_with()) {
        todo_predicate!("`check(file) == failed`");
    }
    // id: orphan_property_rejected
    // generator: `spec_file_with(property.derives_from_pointing_at_nonexistent_id: true)`
    // predicate: `check(file) == failed`
    #[test]
    fn orphan_property_rejected(v0 in spec_gen::spec_file_with()) {
        todo_predicate!("`check(file) == failed`");
    }
    // id: incomplete_law_rejected
    // generator: `law_property_missing("identity")`
    // predicate: `check(file) == failed`
    #[test]
    fn incomplete_law_rejected(v0 in spec_gen::law_property_missing()) {
        todo_predicate!("`check(file) == failed`");
    }
    // id: full_coverage_passes
    // generator: `arbitrary_fully_covered_spec_file()`
    // predicate: `check(file) == passed`
    #[test]
    fn full_coverage_passes(v0 in spec_gen::arbitrary_fully_covered_spec_file()) {
        todo_predicate!("`check(file) == passed`");
    }
    // id: coverage_naturality
    // case: identity
    // generator: `arbitrary_spec_file(), arbitrary_id_rename()`
    // predicate: **identity:** `coverage_ratio(coverage_ratio_placeholder_renamed_to_itself) == coverage_ratio(placeholder)` — the rename identity case, instantiated at the coverage_ratio observation point  **associativity:** `coverage_ratio(rename(rename(I, a, b), b, c)) == coverage_ratio(rename(I, a, c))` — the rename associativity case at the same observation point  **naturality:** `coverage_ratio(rename(I)) == coverage_ratio(I)` — renaming a constraint doesn't change whether it's covered
    #[test]
    fn coverage_naturality_identity(v0 in spec_gen::arbitrary_spec_file(), v1 in spec_gen::arbitrary_id_rename()) {
        todo_predicate!("**identity:** `coverage_ratio(coverage_ratio_placeholder_renamed_to_itself) == coverage_ratio(placeholder)` — the rename identity case, instantiated at the coverage_ratio observation point  **associativity:** `coverage_ratio(rename(rename(I, a, b), b, c)) == coverage_ratio(rename(I, a, c))` — the rename associativity case at the same observation point  **naturality:** `coverage_ratio(rename(I)) == coverage_ratio(I)` — renaming a constraint doesn't change whether it's covered");
    }
    // id: coverage_naturality
    // case: associativity
    // generator: `arbitrary_spec_file(), arbitrary_id_rename()`
    // predicate: **identity:** `coverage_ratio(coverage_ratio_placeholder_renamed_to_itself) == coverage_ratio(placeholder)` — the rename identity case, instantiated at the coverage_ratio observation point  **associativity:** `coverage_ratio(rename(rename(I, a, b), b, c)) == coverage_ratio(rename(I, a, c))` — the rename associativity case at the same observation point  **naturality:** `coverage_ratio(rename(I)) == coverage_ratio(I)` — renaming a constraint doesn't change whether it's covered
    #[test]
    fn coverage_naturality_associativity(v0 in spec_gen::arbitrary_spec_file(), v1 in spec_gen::arbitrary_id_rename()) {
        todo_predicate!("**identity:** `coverage_ratio(coverage_ratio_placeholder_renamed_to_itself) == coverage_ratio(placeholder)` — the rename identity case, instantiated at the coverage_ratio observation point  **associativity:** `coverage_ratio(rename(rename(I, a, b), b, c)) == coverage_ratio(rename(I, a, c))` — the rename associativity case at the same observation point  **naturality:** `coverage_ratio(rename(I)) == coverage_ratio(I)` — renaming a constraint doesn't change whether it's covered");
    }
    // id: coverage_naturality
    // case: naturality
    // generator: `arbitrary_spec_file(), arbitrary_id_rename()`
    // predicate: **identity:** `coverage_ratio(coverage_ratio_placeholder_renamed_to_itself) == coverage_ratio(placeholder)` — the rename identity case, instantiated at the coverage_ratio observation point  **associativity:** `coverage_ratio(rename(rename(I, a, b), b, c)) == coverage_ratio(rename(I, a, c))` — the rename associativity case at the same observation point  **naturality:** `coverage_ratio(rename(I)) == coverage_ratio(I)` — renaming a constraint doesn't change whether it's covered
    #[test]
    fn coverage_naturality_naturality(v0 in spec_gen::arbitrary_spec_file(), v1 in spec_gen::arbitrary_id_rename()) {
        todo_predicate!("**identity:** `coverage_ratio(coverage_ratio_placeholder_renamed_to_itself) == coverage_ratio(placeholder)` — the rename identity case, instantiated at the coverage_ratio observation point  **associativity:** `coverage_ratio(rename(rename(I, a, b), b, c)) == coverage_ratio(rename(I, a, c))` — the rename associativity case at the same observation point  **naturality:** `coverage_ratio(rename(I)) == coverage_ratio(I)` — renaming a constraint doesn't change whether it's covered");
    }
    // id: computed_derives_from_rejected
    // generator: `spec_file_with(computed_or_templated_derives_from_id: true)`
    // predicate: `check(file) == failed` — a non-literal id cannot be counted from the parsed AST alone
    #[test]
    fn computed_derives_from_rejected(v0 in spec_gen::spec_file_with()) {
        todo_predicate!("`check(file) == failed` — a non-literal id cannot be counted from the parsed AST alone");
    }
    // id: count_failure_label_asserted
    // generator: `count_failure_raised()`
    // predicate: `error_label == "linter.coverage.count_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn count_failure_label_asserted(v0 in spec_gen::count_failure_raised()) {
        todo_predicate!("`error_label == \"linter.coverage.count_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
    // id: law_case_failure_label_asserted
    // generator: `law_case_failure_raised()`
    // predicate: `error_label == "linter.coverage.law_case_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn law_case_failure_label_asserted(v0 in spec_gen::law_case_failure_raised()) {
        todo_predicate!("`error_label == \"linter.coverage.law_case_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
    // id: unlabeled_law_rejected
    // generator: `law_predicate_mentioning_cases_without_labels()`
    // predicate: `check(file) == failed` — a prose mention of a case name is not an enumeration (Revision 13 machine form)
    #[test]
    fn unlabeled_law_rejected(v0 in spec_gen::law_predicate_mentioning_cases_without_labels()) {
        todo_predicate!("`check(file) == failed` — a prose mention of a case name is not an enumeration (Revision 13 machine form)");
    }
    // id: extra_case_is_declaration
    // generator: `law_property_with_extra_case("commutativity")`
    // predicate: `compile(file) emits one block per enumerated case` — an extra named case is a first-class checkable declaration, never prose
    #[test]
    fn extra_case_is_declaration(v0 in spec_gen::law_property_with_extra_case()) {
        todo_predicate!("`compile(file) emits one block per enumerated case` — an extra named case is a first-class checkable declaration, never prose");
    }
}

