----------------------------------------------------
MODULE linterearssyntax
----------------------------------------------------
\* Generated by `spk compile` from spec `linter.ears_syntax` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"unchecked", "pattern_matching", "id_checking", "passed", "failed"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "unchecked"

Next ==
  \* begin: unchecked -> pattern_matching (guard: `file passed linter.frontmatter`)
  \/ vpc = "unchecked" /\ vpc' = "pattern_matching"
  \* pattern_ok: pattern_matching -> id_checking (guard: [[linter.ears_syntax.ears_pattern_match]] ∧ [[linter.ears_syntax.has_shall]])
  \/ vpc = "pattern_matching" /\ vpc' = "id_checking"
  \* pattern_fail: pattern_matching -> failed (guard: `¬pattern_ok.guard`)
  \/ vpc = "pattern_matching" /\ vpc' = "failed"
  \* accept: id_checking -> passed (guard: [[linter.ears_syntax.no_conjoined_id]] ∧ [[linter.ears_syntax.no_universal_in_id]])
  \/ vpc = "id_checking" /\ vpc' = "passed"
  \* reject: id_checking -> failed (guard: `¬accept.guard`)
  \/ vpc = "id_checking" /\ vpc' = "failed"

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
