----------------------------------------------------
MODULE lintermodelshape
----------------------------------------------------
\* Generated by `spk compile` from spec `linter.model_shape` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"ungrouped", "pairing_checked", "states_checked", "passed", "failed"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "ungrouped"

Next ==
  \* check_pairing: ungrouped -> pairing_checked (guard: `file passed linter.graph_shape`)
  \/ vpc = "ungrouped" /\ vpc' = "pairing_checked"
  \* pairing_ok: pairing_checked -> states_checked (guard: [[linter.model_shape.model_sections_paired]] ∧ [[linter.model_shape.every_state_used]] ∧ [[linter.model_shape.every_transition_valid]])
  \/ vpc = "pairing_checked" /\ vpc' = "states_checked"
  \* pairing_fail: pairing_checked -> failed (guard: `¬pairing_ok.guard`)
  \/ vpc = "pairing_checked" /\ vpc' = "failed"
  \* accept: states_checked -> passed (guard: [[linter.model_shape.guard_present]] ∧ [[linter.model_shape.no_bool_state_field]])
  \/ vpc = "states_checked" /\ vpc' = "passed"
  \* reject: states_checked -> failed (guard: `¬accept.guard`)
  \/ vpc = "states_checked" /\ vpc' = "failed"

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
