//! proptest scaffolding for `linter.model_shape` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// Each yields a String (the generator's name; executable
/// fragments bind these directly — Revision 15).
pub mod spec_gen {
    use super::*;

    pub fn spec_file_with() -> impl Strategy<Value = String> {
        Just("spec_file_with".into())
    }

    pub fn arbitrary_well_formed_state_machine() -> impl Strategy<Value = String> {
        Just("arbitrary_well_formed_state_machine".into())
    }

    pub fn pairing_failure_raised() -> impl Strategy<Value = String> {
        Just("pairing_failure_raised".into())
    }

    pub fn field_check_failure_raised() -> impl Strategy<Value = String> {
        Just("field_check_failure_raised".into())
    }

}

proptest! {
    // id: missing_guard_rejected
    // generator: `spec_file_with(transition_missing_guard: true)`
    // predicate: `check(file) == failed`
    #[test]
    fn missing_guard_rejected(v0 in spec_gen::spec_file_with()) {
        todo_predicate!("`check(file) == failed`");
    }
    // id: unpaired_states_rejected
    // generator: `spec_file_with(states_section_but_no_transitions: true)`
    // predicate: `check(file) == failed`
    #[test]
    fn unpaired_states_rejected(v0 in spec_gen::spec_file_with()) {
        todo_predicate!("`check(file) == failed`");
    }
    // id: unreachable_state_rejected
    // generator: `spec_file_with(declared_state_never_referenced: true)`
    // predicate: `check(file) == failed`
    #[test]
    fn unreachable_state_rejected(v0 in spec_gen::spec_file_with()) {
        todo_predicate!("`check(file) == failed`");
    }
    // id: bad_edge_rejected
    // generator: `spec_file_with(transition.to_not_in_states: true)`
    // predicate: `check(file) == failed`
    #[test]
    fn bad_edge_rejected(v0 in spec_gen::spec_file_with()) {
        todo_predicate!("`check(file) == failed`");
    }
    // id: bool_column_rejected
    // generator: `spec_file_with(state_row_having_bool_typed_column: true)`
    // predicate: `check(file) == failed`
    #[test]
    fn bool_column_rejected(v0 in spec_gen::spec_file_with()) {
        todo_predicate!("`check(file) == failed`");
    }
    // id: well_formed_model_passes
    // generator: `arbitrary_well_formed_state_machine()`
    // predicate: `check(file) == passed`
    #[test]
    fn well_formed_model_passes(v0 in spec_gen::arbitrary_well_formed_state_machine()) {
        todo_predicate!("`check(file) == passed`");
    }
    // id: pairing_failure_label_asserted
    // generator: `pairing_failure_raised()`
    // predicate: `error_label == "linter.model_shape.pairing_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn pairing_failure_label_asserted(v0 in spec_gen::pairing_failure_raised()) {
        todo_predicate!("`error_label == \"linter.model_shape.pairing_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
    // id: field_check_failure_label_asserted
    // generator: `field_check_failure_raised()`
    // predicate: `error_label == "linter.model_shape.field_check_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn field_check_failure_label_asserted(v0 in spec_gen::field_check_failure_raised()) {
        todo_predicate!("`error_label == \"linter.model_shape.field_check_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
}

