//! proptest scaffolding for `linter.failure_shape` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// The real element types and strategies are `verify`'s domain.
pub mod spec_gen {
    use super::*;

    pub fn tool_file_with_failure_terminal_and_no_emits_edge() -> impl Strategy<Value = GenVal> {
        Just(GenVal("tool_file_with_failure_terminal_and_no_emits_edge".into()))
    }

    pub fn file_with_two_error_constraints_sharing_a_variant_head() -> impl Strategy<Value = GenVal> {
        Just(GenVal("file_with_two_error_constraints_sharing_a_variant_head".into()))
    }

    pub fn failure_transition_citing_nothing_off_the_carveout_list() -> impl Strategy<Value = GenVal> {
        Just(GenVal("failure_transition_citing_nothing_off_the_carveout_list".into()))
    }

    pub fn orchestrate_stage_fail_transition() -> impl Strategy<Value = GenVal> {
        Just(GenVal("orchestrate_stage_fail_transition".into()))
    }

    pub fn failure_transition_whose_citations_differ_from_its_siblings() -> impl Strategy<Value = GenVal> {
        Just(GenVal("failure_transition_whose_citations_differ_from_its_siblings".into()))
    }

    pub fn the_repo_itself() -> impl Strategy<Value = GenVal> {
        Just(GenVal("the_repo_itself".into()))
    }

    pub fn failure_shape_violation_found() -> impl Strategy<Value = GenVal> {
        Just(GenVal("failure_shape_violation_found".into()))
    }

}

proptest! {
    // id: mute_terminal_rejected
    // generator: `tool_file_with_failure_terminal_and_no_emits_edge()`
    // predicate: `check(file) == failed` — the corpus's pre-add-error-contract shape, kept as the negative fixture
    #[test]
    fn mute_terminal_rejected(v0 in spec_gen::tool_file_with_failure_terminal_and_no_emits_edge()) {
        todo_predicate!("`check(file) == failed` — the corpus's pre-add-error-contract shape, kept as the negative fixture");
    }
}

proptest! {
    // id: label_collision_rejected
    // generator: `file_with_two_error_constraints_sharing_a_variant_head()`
    // predicate: `check(file) == failed`
    #[test]
    fn label_collision_rejected(v0 in spec_gen::file_with_two_error_constraints_sharing_a_variant_head()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: zero_citation_flagged
    // generator: `failure_transition_citing_nothing_off_the_carveout_list()`
    // predicate: `check(file) == failed` — the carve-out is a checked list, not an escape hatch
    #[test]
    fn zero_citation_flagged(v0 in spec_gen::failure_transition_citing_nothing_off_the_carveout_list()) {
        todo_predicate!("`check(file) == failed` — the carve-out is a checked list, not an escape hatch");
    }
}

proptest! {
    // id: carved_out_guard_passes
    // generator: `orchestrate_stage_fail_transition()`
    // predicate: `check(file) == passed` — the carve-out is checked, not assumed
    #[test]
    fn carved_out_guard_passes(v0 in spec_gen::orchestrate_stage_fail_transition()) {
        todo_predicate!("`check(file) == passed` — the carve-out is checked, not assumed");
    }
}

proptest! {
    // id: negation_set_mismatch_flagged
    // generator: `failure_transition_whose_citations_differ_from_its_siblings()`
    // predicate: `check(file) == failed` — citation-set inequality is graph-decidable
    #[test]
    fn negation_set_mismatch_flagged(v0 in spec_gen::failure_transition_whose_citations_differ_from_its_siblings()) {
        todo_predicate!("`check(file) == failed` — citation-set inequality is graph-decidable");
    }
}

proptest! {
    // id: clean_repo_passes
    // generator: `the_repo_itself()`
    // predicate: `check(repo) == passed` — the corpus dogfoods this checker's contract
    #[test]
    fn clean_repo_passes(v0 in spec_gen::the_repo_itself()) {
        todo_predicate!("`check(repo) == passed` — the corpus dogfoods this checker's contract");
    }
}

proptest! {
    // id: check_failure_label_asserted
    // generator: `failure_shape_violation_found()`
    // predicate: `error_label == "linter.failure_shape.check_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn check_failure_label_asserted(v0 in spec_gen::failure_shape_violation_found()) {
        todo_predicate!("`error_label == \"linter.failure_shape.check_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
}

