---- MODULE linterexternalcompleteness ----
\* Generated by `spk compile` from spec `linter.external_completeness` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"not_applicable", "loaded", "mapping_checked", "passed", "load_failed", "mapping_failed", "resolution_failed"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "not_applicable"

Next ==
  \* load: not_applicable -> loaded (guard: `repo declares a checklist` ∧ [[linter.external_completeness.checklist_well_formed]])
  \/ vpc = "not_applicable" /\ vpc' = "loaded"
  \* load_fail: not_applicable -> load_failed (guard: `repo declares a checklist` ∧ `¬([[linter.external_completeness.checklist_well_formed]])`)
  \/ vpc = "not_applicable" /\ vpc' = "load_failed"
  \* check_mapping: loaded -> mapping_checked (guard: [[linter.external_completeness.every_item_accounted]] ∧ [[linter.external_completeness.no_duplicate_claim]])
  \/ vpc = "loaded" /\ vpc' = "mapping_checked"
  \* check_fail: loaded -> mapping_failed (guard: `¬([[linter.external_completeness.every_item_accounted]] ∧ [[linter.external_completeness.no_duplicate_claim]])`)
  \/ vpc = "loaded" /\ vpc' = "mapping_failed"
  \* accept: mapping_checked -> passed (guard: [[linter.external_completeness.covered_maps_resolve]] ∧ [[linter.external_completeness.waiver_has_rationale]])
  \/ vpc = "mapping_checked" /\ vpc' = "passed"
  \* reject: mapping_checked -> resolution_failed (guard: `¬([[linter.external_completeness.covered_maps_resolve]] ∧ [[linter.external_completeness.waiver_has_rationale]])`)
  \/ vpc = "mapping_checked" /\ vpc' = "resolution_failed"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* One entry per state with an `emits` field — domain is exactly
\* the emitting states; each value is the effect-Constraint's expr.
Output ==
"load_failed" :> "`linter.external_completeness.manifest_failure(detail)`" @@
"mapping_failed" :> "`linter.external_completeness.mapping_failure(detail)`" @@
"resolution_failed" :> "`linter.external_completeness.resolution_failure(detail)`"

============================================================================
