----------------------------------------------------
MODULE lintergraphshape
----------------------------------------------------
\* Generated by `spk compile` from spec `linter.graph_shape` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"unbuilt", "built", "traversing", "passed", "failed"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "unbuilt"

Next ==
  \* build_graph: unbuilt -> built (guard: `repo passed linter.referential_integrity`)
  \/ vpc = "unbuilt" /\ vpc' = "built"
  \* traverse: built -> traversing (guard: `graph built successfully`)
  \/ vpc = "built" /\ vpc' = "traversing"
  \* accept: traversing -> passed (guard: [[linter.graph_shape.acyclic]] ∧ [[linter.graph_shape.single_root_reachable]] ∧ [[linter.graph_shape.no_self_ref]] ∧ [[linter.graph_shape.supersedes_dag]])
  \/ vpc = "traversing" /\ vpc' = "passed"
  \* reject: traversing -> failed (guard: `¬accept.guard`)
  \/ vpc = "traversing" /\ vpc' = "failed"

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
