---- MODULE lintermodelshape ----
\* Generated by `spk compile` from spec `linter.model_shape` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"ungrouped", "pairing_checked", "states_checked", "passed", "pairing_failed", "field_check_failed"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "ungrouped"

Next ==
  \* check_pairing: ungrouped -> pairing_checked (guard: `file passed linter.graph_shape`)
  \/ vpc = "ungrouped" /\ vpc' = "pairing_checked"
  \* pairing_ok: pairing_checked -> states_checked (guard: [[linter.model_shape.model_sections_paired]] ∧ [[linter.model_shape.every_state_used]] ∧ [[linter.model_shape.every_transition_valid]])
  \/ vpc = "pairing_checked" /\ vpc' = "states_checked"
  \* pairing_fail: pairing_checked -> pairing_failed (guard: `¬([[linter.model_shape.model_sections_paired]] ∧ [[linter.model_shape.every_state_used]] ∧ [[linter.model_shape.every_transition_valid]])`)
  \/ vpc = "pairing_checked" /\ vpc' = "pairing_failed"
  \* accept: states_checked -> passed (guard: [[linter.model_shape.guard_present]] ∧ [[linter.model_shape.no_bool_state_field]])
  \/ vpc = "states_checked" /\ vpc' = "passed"
  \* reject: states_checked -> field_check_failed (guard: `¬([[linter.model_shape.guard_present]] ∧ [[linter.model_shape.no_bool_state_field]])`)
  \/ vpc = "states_checked" /\ vpc' = "field_check_failed"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* One entry per state with an `emits` field — domain is exactly
\* the emitting states; each value is the effect-Constraint's expr.
Output ==
"field_check_failed" :> "`linter.model_shape.field_check_failure(detail)`" @@
"pairing_failed" :> "`linter.model_shape.pairing_failure(detail)`"

============================================================================
