//! proptest scaffolding for `linter.schema_shape` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// Each yields a String (the generator's name; executable
/// fragments bind these directly — Revision 15).
pub mod spec_gen {
    use super::*;

    pub fn constraint_row_with() -> impl Strategy<Value = String> {
        Just("constraint_row_with".into())
    }

    pub fn property_row_with() -> impl Strategy<Value = String> {
        Just("property_row_with".into())
    }

    pub fn arbitrary_file_with() -> impl Strategy<Value = String> {
        Just("arbitrary_file_with".into())
    }

    pub fn arbitrary_unicode_string() -> impl Strategy<Value = String> {
        Just("arbitrary_unicode_string".into())
    }

    pub fn spec_file_with() -> impl Strategy<Value = String> {
        Just("spec_file_with".into())
    }

    pub fn kind_check_failure_raised() -> impl Strategy<Value = String> {
        Just("kind_check_failure_raised".into())
    }

    pub fn diff_failure_raised() -> impl Strategy<Value = String> {
        Just("diff_failure_raised".into())
    }

    pub fn parser_audit_failure_raised() -> impl Strategy<Value = String> {
        Just("parser_audit_failure_raised".into())
    }

}

// id: shrunk_id_set_rejected
// generator: `(revision_n, revision_n_plus_1)` where a member was removed from a variant table, a kind value-set, or the Reference Typing table
// predicate: `check(revisions) == failed` — one generator, parametrized over which of the three id-sets it targets
#[test]
fn shrunk_id_set_rejected() {
        todo_predicate!("`check(revisions) == failed` — one generator, parametrized over which of the three id-sets it targets");
}

// id: reordered_id_set_rejected
// generator: `(revision_n, revision_n_plus_1)` where two existing members of any 𝒦-governed id-set swapped order
// predicate: `check(revisions) == failed`
#[test]
fn reordered_id_set_rejected() {
        todo_predicate!("`check(revisions) == failed`");
}

// id: silent_narrowing_rejected
// generator: `(revision_n, revision_n_plus_1)` where a Reference Typing field's target narrowed with no accompanying kind-split cited
// predicate: `check(revisions) == failed`
#[test]
fn silent_narrowing_rejected() {
        todo_predicate!("`check(revisions) == failed`");
}

proptest! {
    // id: constraint_kind_invalid_rejected
    // generator: `constraint_row_with(kind: "made_up")`
    // predicate: `check(file) == failed`
    #[test]
    fn constraint_kind_invalid_rejected(v0 in spec_gen::constraint_row_with()) {
        todo_predicate!("`check(file) == failed`");
    }
    // id: property_kind_invalid_rejected
    // generator: `property_row_with(kind: "audit")`
    // predicate: `check(file) == failed`
    #[test]
    fn property_kind_invalid_rejected(v0 in spec_gen::property_row_with()) {
        todo_predicate!("`check(file) == failed`");
    }
    // id: kind_closed_passes
    // generator: `arbitrary_file_with(only_closed_kind_values: true)`
    // predicate: `check(file) == passed`
    #[test]
    fn kind_closed_passes(v0 in spec_gen::arbitrary_file_with()) {
        todo_predicate!("`check(file) == passed`");
    }
    // id: prose_roundtrips
    // generator: `arbitrary_unicode_string()` as rationale content
    // predicate: `compile(parse(s)).rationale == s` — no normalization, no truncation
    #[test]
    fn prose_roundtrips(v0 in spec_gen::arbitrary_unicode_string()) {
        todo_predicate!("`compile(parse(s)).rationale == s` — no normalization, no truncation");
    }
}

// id: appended_id_set_member_passes
// generator: `(revision_n, revision_n_plus_1)` where only new members were added, to any of the three id-sets
// predicate: `check(revisions) == passed`
#[test]
fn appended_id_set_member_passes() {
        todo_predicate!("`check(revisions) == passed`");
}

proptest! {
    // id: constraint_kind_advisory_passes
    // generator: `constraint_row_with(kind: "advisory")`
    // predicate: `check(file) == passed`
    #[test]
    fn constraint_kind_advisory_passes(v0 in spec_gen::constraint_row_with()) {
        todo_predicate!("`check(file) == passed`");
    }
    // id: constraint_kind_effect_passes
    // generator: `constraint_row_with(kind: "effect")`
    // predicate: `check(file) == passed`
    #[test]
    fn constraint_kind_effect_passes(v0 in spec_gen::constraint_row_with()) {
        todo_predicate!("`check(file) == passed`");
    }
    // id: constraint_kind_extension_point_passes
    // generator: `constraint_row_with(kind: "extension_point")`
    // predicate: `check(file) == passed`
    #[test]
    fn constraint_kind_extension_point_passes(v0 in spec_gen::constraint_row_with()) {
        todo_predicate!("`check(file) == passed`");
    }
    // id: parser_ast_prose_free
    // generator: `spec_file_with(prose_in_rationale_and_description: arbitrary_unicode_string())`
    // predicate: `∀ parsed row: the row's parsed fields contain no fragment of the planted prose` — a planted-prose differential parse (see Notes)
    #[test]
    fn parser_ast_prose_free(v0 in spec_gen::spec_file_with(), v1 in spec_gen::arbitrary_unicode_string()) {
        todo_predicate!("`∀ parsed row: the row's parsed fields contain no fragment of the planted prose` — a planted-prose differential parse (see Notes)");
    }
    // id: kind_check_failure_label_asserted
    // generator: `kind_check_failure_raised()`
    // predicate: `error_label == "linter.schema_shape.kind_check_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn kind_check_failure_label_asserted(v0 in spec_gen::kind_check_failure_raised()) {
        todo_predicate!("`error_label == \"linter.schema_shape.kind_check_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
    // id: diff_failure_label_asserted
    // generator: `diff_failure_raised()`
    // predicate: `error_label == "linter.schema_shape.diff_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn diff_failure_label_asserted(v0 in spec_gen::diff_failure_raised()) {
        todo_predicate!("`error_label == \"linter.schema_shape.diff_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
    // id: parser_audit_failure_label_asserted
    // generator: `parser_audit_failure_raised()`
    // predicate: `error_label == "linter.schema_shape.parser_audit_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn parser_audit_failure_label_asserted(v0 in spec_gen::parser_audit_failure_raised()) {
        todo_predicate!("`error_label == \"linter.schema_shape.parser_audit_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
}

