---- MODULE linterfailureshape ----
\* Generated by `spk compile` from spec `linter.failure_shape` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"unchecked", "checking", "passed", "failed"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "unchecked"

Next ==
  \* begin: unchecked -> checking (guard: `the repo declares a specs corpus to check`)
  \/ vpc = "unchecked" /\ vpc' = "checking"
  \* accept: checking -> passed (guard: [[linter.failure_shape.terminal_states_emit]] ∧ [[linter.failure_shape.error_labels_unique]] ∧ [[linter.failure_shape.guard_negation_total]])
  \/ vpc = "checking" /\ vpc' = "passed"
  \* reject: checking -> failed (guard: `¬([[linter.failure_shape.terminal_states_emit]] ∧ [[linter.failure_shape.error_labels_unique]] ∧ [[linter.failure_shape.guard_negation_total]])`)
  \/ vpc = "checking" /\ vpc' = "failed"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* One entry per state with an `emits` field — domain is exactly
\* the emitting states; each value is the effect-Constraint's expr.
Output ==
"failed" :> "`linter.failure_shape.check_failure(detail)`"

============================================================================
