//! proptest scaffolding for `linter.ears_syntax` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// The real element types and strategies are `verify`'s domain.
pub mod spec_gen {
    use super::*;

    pub fn statement_not_matching_any_ears_pattern() -> impl Strategy<Value = GenVal> {
        Just(GenVal("statement_not_matching_any_ears_pattern".into()))
    }

    pub fn statement_matching_pattern_but_missing() -> impl Strategy<Value = GenVal> {
        Just(GenVal("statement_matching_pattern_but_missing".into()))
    }

    pub fn row_with() -> impl Strategy<Value = GenVal> {
        Just(GenVal("row_with".into()))
    }

    pub fn arbitrary_ears_compliant_statement() -> impl Strategy<Value = GenVal> {
        Just(GenVal("arbitrary_ears_compliant_statement".into()))
    }

}

proptest! {
    // id: non_ears_rejected
    // generator: `statement_not_matching_any_ears_pattern()`
    // predicate: `check(file) == failed`
    #[test]
    fn non_ears_rejected(v0 in spec_gen::statement_not_matching_any_ears_pattern()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: missing_shall_rejected
    // generator: `statement_matching_pattern_but_missing("SHALL")`
    // predicate: `check(file) == failed`
    #[test]
    fn missing_shall_rejected(v0 in spec_gen::statement_matching_pattern_but_missing()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: conjoined_id_rejected
    // generator: `row_with(id: "order.cancel_and_refund")`
    // predicate: `check(file) == failed`
    #[test]
    fn conjoined_id_rejected(v0 in spec_gen::row_with()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: universal_token_rejected
    // generator: `row_with(id: "order.always_validate")`
    // predicate: `check(file) == failed`
    #[test]
    fn universal_token_rejected(v0 in spec_gen::row_with()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: valid_ears_passes
    // generator: `arbitrary_ears_compliant_statement()`
    // predicate: `check(file) == passed`
    #[test]
    fn valid_ears_passes(v0 in spec_gen::arbitrary_ears_compliant_statement()) {
        todo_predicate!("`check(file) == passed`");
    }
}

