//! proptest scaffolding for `linter.graph_shape` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// The real element types and strategies are `verify`'s domain.
pub mod spec_gen {
    use super::*;

    pub fn spec_repo_with() -> impl Strategy<Value = GenVal> {
        Just(GenVal("spec_repo_with".into()))
    }

    pub fn spec_row_with() -> impl Strategy<Value = GenVal> {
        Just(GenVal("spec_row_with".into()))
    }

    pub fn arbitrary_dag_shaped_repo() -> impl Strategy<Value = GenVal> {
        Just(GenVal("arbitrary_dag_shaped_repo".into()))
    }

    pub fn arbitrary_dag_repo() -> impl Strategy<Value = GenVal> {
        Just(GenVal("arbitrary_dag_repo".into()))
    }

    pub fn arbitrary_id_rename() -> impl Strategy<Value = GenVal> {
        Just(GenVal("arbitrary_id_rename".into()))
    }

}

proptest! {
    // id: cycle_rejected
    // generator: `spec_repo_with(traces_to_cycle: length ≥ 2)`
    // predicate: `check(repo) == failed`
    #[test]
    fn cycle_rejected(v0 in spec_gen::spec_repo_with()) {
        todo_predicate!("`check(repo) == failed`");
    }
}

proptest! {
    // id: self_ref_rejected
    // generator: `spec_row_with(traces_to == self.id)`
    // predicate: `check(repo) == failed`
    #[test]
    fn self_ref_rejected(v0 in spec_gen::spec_row_with()) {
        todo_predicate!("`check(repo) == failed`");
    }
}

proptest! {
    // id: orphan_subgraph_rejected
    // generator: `spec_repo_with(disconnected_constraint_cluster: true)`
    // predicate: `check(repo) == failed`
    #[test]
    fn orphan_subgraph_rejected(v0 in spec_gen::spec_repo_with()) {
        todo_predicate!("`check(repo) == failed`");
    }
}

proptest! {
    // id: dag_passes
    // generator: `arbitrary_dag_shaped_repo()`
    // predicate: `check(repo) == passed`
    #[test]
    fn dag_passes(v0 in spec_gen::arbitrary_dag_shaped_repo()) {
        todo_predicate!("`check(repo) == passed`");
    }
}

proptest! {
    // id: supersedes_cycle_rejected
    // generator: `spec_repo_with(supersedes_cycle: length ≥ 2)`
    // predicate: `check(repo) == failed`
    #[test]
    fn supersedes_cycle_rejected(v0 in spec_gen::spec_repo_with()) {
        todo_predicate!("`check(repo) == failed`");
    }
}

proptest! {
    // id: supersedes_dag_ignores_traces_cycle
    // generator: `spec_repo_with(traces_to_cycle: true, supersedes: acyclic)`
    // predicate: `check(repo).supersedes_dag == passed` — the two graphs are checked independently; a cycle in one must not be attributed to the other
    #[test]
    fn supersedes_dag_ignores_traces_cycle(v0 in spec_gen::spec_repo_with()) {
        todo_predicate!("`check(repo).supersedes_dag == passed` — the two graphs are checked independently; a cycle in one must not be attributed to the other");
    }
}

proptest! {
    // id: topo_sort_naturality
    // case: naturality
    // generator: `arbitrary_dag_repo(), arbitrary_id_rename()`
    // predicate: **naturality:** `topo_sort(rename(I)) == rename(topo_sort(I))` — renaming a node doesn't change relative order of unrelated nodes
    #[test]
    fn topo_sort_naturality_naturality(v0 in spec_gen::arbitrary_dag_repo(), v1 in spec_gen::arbitrary_id_rename()) {
        todo_predicate!("**naturality:** `topo_sort(rename(I)) == rename(topo_sort(I))` — renaming a node doesn't change relative order of unrelated nodes");
    }
}

