//! proptest scaffolding for `linter.frontmatter` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// The real element types and strategies are `verify`'s domain.
pub mod spec_gen {
    use super::*;

    pub fn frontmatter_without() -> impl Strategy<Value = GenVal> {
        Just(GenVal("frontmatter_without".into()))
    }

    pub fn frontmatter_with_kind() -> impl Strategy<Value = GenVal> {
        Just(GenVal("frontmatter_with_kind".into()))
    }

    pub fn arbitrary_valid_frontmatter() -> impl Strategy<Value = GenVal> {
        Just(GenVal("arbitrary_valid_frontmatter".into()))
    }

    pub fn stem() -> impl Strategy<Value = GenVal> {
        Just(GenVal("stem".into()))
    }

    pub fn frontmatter_with() -> impl Strategy<Value = GenVal> {
        Just(GenVal("frontmatter_with".into()))
    }

}

proptest! {
    // id: missing_id_rejected
    // generator: `frontmatter_without("id")`
    // predicate: `check(frontmatter) == failed`
    #[test]
    fn missing_id_rejected(v0 in spec_gen::frontmatter_without()) {
        todo_predicate!("`check(frontmatter) == failed`");
    }
}

proptest! {
    // id: wrong_kind_rejected
    // generator: `frontmatter_with_kind(≠ "intent")`
    // predicate: `check(frontmatter) == failed`
    #[test]
    fn wrong_kind_rejected(v0 in spec_gen::frontmatter_with_kind()) {
        todo_predicate!("`check(frontmatter) == failed`");
    }
}

proptest! {
    // id: valid_passes
    // generator: `arbitrary_valid_frontmatter()`
    // predicate: `check(frontmatter) == passed`
    #[test]
    fn valid_passes(v0 in spec_gen::arbitrary_valid_frontmatter()) {
        todo_predicate!("`check(frontmatter) == passed`");
    }
}

proptest! {
    // id: filename_mismatch
    // generator: `(id, filename)` pairs where `id ≠ stem(filename)`
    // predicate: `check(id, filename) == failed`
    #[test]
    fn filename_mismatch(v0 in spec_gen::stem()) {
        todo_predicate!("`check(id, filename) == failed`");
    }
}

proptest! {
    // id: missing_statement_rejected
    // generator: `frontmatter_without("statement")` and `frontmatter_with(statement: "")`
    // predicate: `check(frontmatter) == failed` — absent and empty are both rejections
    #[test]
    fn missing_statement_rejected(v0 in spec_gen::frontmatter_without(), v1 in spec_gen::frontmatter_with()) {
        todo_predicate!("`check(frontmatter) == failed` — absent and empty are both rejections");
    }
}

