--------------------------------------------------------------
MODULE linterexternalcompleteness
--------------------------------------------------------------
\* Generated by `spk compile` from spec `linter.external_completeness` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"not_applicable", "loaded", "mapping_checked", "passed", "failed"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

Init == vpc = "not_applicable"

Next ==
  \* load: not_applicable -> loaded (guard: `repo declares a checklist` ∧ [[linter.external_completeness.checklist_well_formed]])
  \/ vpc = "not_applicable" /\ vpc' = "loaded"
  \* load_fail: not_applicable -> failed (guard: `repo declares a checklist` ∧ `¬load.guard`)
  \/ vpc = "not_applicable" /\ vpc' = "failed"
  \* check_mapping: loaded -> mapping_checked (guard: [[linter.external_completeness.every_item_accounted]] ∧ [[linter.external_completeness.no_duplicate_claim]])
  \/ vpc = "loaded" /\ vpc' = "mapping_checked"
  \* check_fail: loaded -> failed (guard: `¬check_mapping.guard`)
  \/ vpc = "loaded" /\ vpc' = "failed"
  \* accept: mapping_checked -> passed (guard: [[linter.external_completeness.covered_maps_resolve]] ∧ [[linter.external_completeness.waiver_has_rationale]])
  \/ vpc = "mapping_checked" /\ vpc' = "passed"
  \* reject: mapping_checked -> failed (guard: `¬accept.guard`)
  \/ vpc = "mapping_checked" /\ vpc' = "failed"

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
