//! proptest scaffolding for `linter.ears_syntax` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// Each yields a String (the generator's name; executable
/// fragments bind these directly — Revision 15).
pub mod spec_gen {
    use super::*;

    pub fn statement_not_matching_any_ears_pattern() -> impl Strategy<Value = String> {
        Just("statement_not_matching_any_ears_pattern".into())
    }

    pub fn statement_matching_pattern_but_missing() -> impl Strategy<Value = String> {
        Just("statement_matching_pattern_but_missing".into())
    }

    pub fn row_with() -> impl Strategy<Value = String> {
        Just("row_with".into())
    }

    pub fn arbitrary_ears_compliant_statement() -> impl Strategy<Value = String> {
        Just("arbitrary_ears_compliant_statement".into())
    }

    pub fn pattern_failure_raised() -> impl Strategy<Value = String> {
        Just("pattern_failure_raised".into())
    }

    pub fn id_check_failure_raised() -> impl Strategy<Value = String> {
        Just("id_check_failure_raised".into())
    }

}

proptest! {
    // id: non_ears_rejected
    // generator: `statement_not_matching_any_ears_pattern()`
    // predicate: `check(file) == failed`
    #[test]
    fn non_ears_rejected(v0 in spec_gen::statement_not_matching_any_ears_pattern()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: missing_shall_rejected
    // generator: `statement_matching_pattern_but_missing("SHALL")`
    // predicate: `check(file) == failed`
    #[test]
    fn missing_shall_rejected(v0 in spec_gen::statement_matching_pattern_but_missing()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: conjoined_id_rejected
    // generator: `row_with(id: "order.cancel_and_refund")`
    // predicate: `check(file) == failed`
    #[test]
    fn conjoined_id_rejected(v0 in spec_gen::row_with()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: universal_token_rejected
    // generator: `row_with(id: "order.always_validate")`
    // predicate: `check(file) == failed`
    #[test]
    fn universal_token_rejected(v0 in spec_gen::row_with()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: valid_ears_passes
    // generator: `arbitrary_ears_compliant_statement()`
    // predicate: `check(file) == passed`
    #[test]
    fn valid_ears_passes(v0 in spec_gen::arbitrary_ears_compliant_statement()) {
        todo_predicate!("`check(file) == passed`");
    }
}

proptest! {
    // id: pattern_failure_label_asserted
    // generator: `pattern_failure_raised()`
    // predicate: `error_label == "linter.ears_syntax.pattern_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn pattern_failure_label_asserted(v0 in spec_gen::pattern_failure_raised()) {
        todo_predicate!("`error_label == \"linter.ears_syntax.pattern_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
}

proptest! {
    // id: id_check_failure_label_asserted
    // generator: `id_check_failure_raised()`
    // predicate: `error_label == "linter.ears_syntax.id_check_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn id_check_failure_label_asserted(v0 in spec_gen::id_check_failure_raised()) {
        todo_predicate!("`error_label == \"linter.ears_syntax.id_check_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
}

