---- MODULE lintercoverage ----
\* Generated by `spk compile` from spec `linter.coverage` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"unchecked", "counting", "law_checking", "passed", "count_failed", "law_check_failed"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "unchecked"

Next ==
  \* begin: unchecked -> counting (guard: `file passed linter.graph_shape and linter.model_shape`)
  \/ vpc = "unchecked" /\ vpc' = "counting"
  \* count_ok: counting -> law_checking (guard: [[linter.coverage.every_constraint_covered]] ∧ [[linter.coverage.no_orphan_property]])
  \/ vpc = "counting" /\ vpc' = "law_checking"
  \* count_fail: counting -> count_failed (guard: `¬([[linter.coverage.every_constraint_covered]] ∧ [[linter.coverage.no_orphan_property]])`)
  \/ vpc = "counting" /\ vpc' = "count_failed"
  \* accept: law_checking -> passed (guard: [[linter.coverage.every_law_has_cases]])
  \/ vpc = "law_checking" /\ vpc' = "passed"
  \* reject: law_checking -> law_check_failed (guard: `¬([[linter.coverage.every_law_has_cases]])`)
  \/ vpc = "law_checking" /\ vpc' = "law_check_failed"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* One entry per state with an `emits` field — domain is exactly
\* the emitting states; each value is the effect-Constraint's expr.
Output ==
"count_failed" :> "`linter.coverage.count_failure(detail)`" @@
"law_check_failed" :> "`linter.coverage.law_case_failure(detail)`"

============================================================================
