-----------------------------------------------------
MODULE linterfrontmatter
-----------------------------------------------------
\* Generated by `spk compile` from spec `linter.frontmatter` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"unchecked", "checking", "passed", "failed"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

Init == vpc = "unchecked"

Next ==
  \* begin: unchecked -> checking (guard: `file exists and is UTF-8 markdown`)
  \/ vpc = "unchecked" /\ vpc' = "checking"
  \* accept: checking -> passed (guard: [[linter.frontmatter.has_id]] ∧ [[linter.frontmatter.has_kind]] ∧ [[linter.frontmatter.has_statement]] ∧ [[linter.frontmatter.id_matches_file]])
  \/ vpc = "checking" /\ vpc' = "passed"
  \* reject: checking -> failed (guard: `¬accept.guard`)
  \/ vpc = "checking" /\ vpc' = "failed"

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
