---- MODULE linterobservability ----
\* Generated by `spk compile` from spec `linter.observability` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"scanning", "observed", "unobserved_warned"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "scanning"

Next ==
  \* scan_all: scanning -> observed (guard: `every effect in the invocation's file set has ≥1 observer`)
  \/ vpc = "scanning" /\ vpc' = "observed"
  \* warn_unobserved: scanning -> unobserved_warned (guard: [[linter.observability.observation_universe]])
  \/ vpc = "scanning" /\ vpc' = "unobserved_warned"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
