//! proptest scaffolding for `linter.coverage` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// The real element types and strategies are `verify`'s domain.
pub mod spec_gen {
    use super::*;

    pub fn spec_file_with() -> impl Strategy<Value = GenVal> {
        Just(GenVal("spec_file_with".into()))
    }

    pub fn law_property_missing() -> impl Strategy<Value = GenVal> {
        Just(GenVal("law_property_missing".into()))
    }

    pub fn arbitrary_fully_covered_spec_file() -> impl Strategy<Value = GenVal> {
        Just(GenVal("arbitrary_fully_covered_spec_file".into()))
    }

    pub fn arbitrary_spec_file() -> impl Strategy<Value = GenVal> {
        Just(GenVal("arbitrary_spec_file".into()))
    }

    pub fn arbitrary_id_rename() -> impl Strategy<Value = GenVal> {
        Just(GenVal("arbitrary_id_rename".into()))
    }

    pub fn count_failure_raised() -> impl Strategy<Value = GenVal> {
        Just(GenVal("count_failure_raised".into()))
    }

    pub fn law_case_failure_raised() -> impl Strategy<Value = GenVal> {
        Just(GenVal("law_case_failure_raised".into()))
    }

}

proptest! {
    // id: uncovered_constraint_rejected
    // generator: `spec_file_with(constraint_with_no_deriving_property: true)`
    // predicate: `check(file) == failed`
    #[test]
    fn uncovered_constraint_rejected(v0 in spec_gen::spec_file_with()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: orphan_property_rejected
    // generator: `spec_file_with(property.derives_from_pointing_at_nonexistent_id: true)`
    // predicate: `check(file) == failed`
    #[test]
    fn orphan_property_rejected(v0 in spec_gen::spec_file_with()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: incomplete_law_rejected
    // generator: `law_property_missing("identity")`
    // predicate: `check(file) == failed`
    #[test]
    fn incomplete_law_rejected(v0 in spec_gen::law_property_missing()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: full_coverage_passes
    // generator: `arbitrary_fully_covered_spec_file()`
    // predicate: `check(file) == passed`
    #[test]
    fn full_coverage_passes(v0 in spec_gen::arbitrary_fully_covered_spec_file()) {
        todo_predicate!("`check(file) == passed`");
    }
}

proptest! {
    // id: coverage_naturality
    // case: identity
    // generator: `arbitrary_spec_file(), arbitrary_id_rename()`
    // predicate: **identity:** `coverage_ratio(coverage_ratio_placeholder_renamed_to_itself) == coverage_ratio(placeholder)` — the rename identity case, instantiated at the coverage_ratio observation point  **naturality:** `coverage_ratio(rename(I)) == coverage_ratio(I)` — renaming a constraint doesn't change whether it's covered
    #[test]
    fn coverage_naturality_identity(v0 in spec_gen::arbitrary_spec_file(), v1 in spec_gen::arbitrary_id_rename()) {
        todo_predicate!("**identity:** `coverage_ratio(coverage_ratio_placeholder_renamed_to_itself) == coverage_ratio(placeholder)` — the rename identity case, instantiated at the coverage_ratio observation point  **naturality:** `coverage_ratio(rename(I)) == coverage_ratio(I)` — renaming a constraint doesn't change whether it's covered");
    }
}

proptest! {
    // id: coverage_naturality
    // case: naturality
    // generator: `arbitrary_spec_file(), arbitrary_id_rename()`
    // predicate: **identity:** `coverage_ratio(coverage_ratio_placeholder_renamed_to_itself) == coverage_ratio(placeholder)` — the rename identity case, instantiated at the coverage_ratio observation point  **naturality:** `coverage_ratio(rename(I)) == coverage_ratio(I)` — renaming a constraint doesn't change whether it's covered
    #[test]
    fn coverage_naturality_naturality(v0 in spec_gen::arbitrary_spec_file(), v1 in spec_gen::arbitrary_id_rename()) {
        todo_predicate!("**identity:** `coverage_ratio(coverage_ratio_placeholder_renamed_to_itself) == coverage_ratio(placeholder)` — the rename identity case, instantiated at the coverage_ratio observation point  **naturality:** `coverage_ratio(rename(I)) == coverage_ratio(I)` — renaming a constraint doesn't change whether it's covered");
    }
}

proptest! {
    // id: computed_derives_from_rejected
    // generator: `spec_file_with(computed_or_templated_derives_from_id: true)`
    // predicate: `check(file) == failed` — a non-literal id cannot be counted from the parsed AST alone
    #[test]
    fn computed_derives_from_rejected(v0 in spec_gen::spec_file_with()) {
        todo_predicate!("`check(file) == failed` — a non-literal id cannot be counted from the parsed AST alone");
    }
}

proptest! {
    // id: count_failure_label_asserted
    // generator: `count_failure_raised()`
    // predicate: `error_label == "linter.coverage.count_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn count_failure_label_asserted(v0 in spec_gen::count_failure_raised()) {
        todo_predicate!("`error_label == \"linter.coverage.count_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
}

proptest! {
    // id: law_case_failure_label_asserted
    // generator: `law_case_failure_raised()`
    // predicate: `error_label == "linter.coverage.law_case_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn law_case_failure_label_asserted(v0 in spec_gen::law_case_failure_raised()) {
        todo_predicate!("`error_label == \"linter.coverage.law_case_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
}

