//! proptest scaffolding for `linter.model_shape` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// The real element types and strategies are `verify`'s domain.
pub mod spec_gen {
    use super::*;

    pub fn spec_file_with() -> impl Strategy<Value = GenVal> {
        Just(GenVal("spec_file_with".into()))
    }

    pub fn arbitrary_well_formed_state_machine() -> impl Strategy<Value = GenVal> {
        Just(GenVal("arbitrary_well_formed_state_machine".into()))
    }

    pub fn pairing_failure_raised() -> impl Strategy<Value = GenVal> {
        Just(GenVal("pairing_failure_raised".into()))
    }

    pub fn field_check_failure_raised() -> impl Strategy<Value = GenVal> {
        Just(GenVal("field_check_failure_raised".into()))
    }

}

proptest! {
    // id: missing_guard_rejected
    // generator: `spec_file_with(transition_missing_guard: true)`
    // predicate: `check(file) == failed`
    #[test]
    fn missing_guard_rejected(v0 in spec_gen::spec_file_with()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: unpaired_states_rejected
    // generator: `spec_file_with(states_section_but_no_transitions: true)`
    // predicate: `check(file) == failed`
    #[test]
    fn unpaired_states_rejected(v0 in spec_gen::spec_file_with()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: unreachable_state_rejected
    // generator: `spec_file_with(declared_state_never_referenced: true)`
    // predicate: `check(file) == failed`
    #[test]
    fn unreachable_state_rejected(v0 in spec_gen::spec_file_with()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: bad_edge_rejected
    // generator: `spec_file_with(transition.to_not_in_states: true)`
    // predicate: `check(file) == failed`
    #[test]
    fn bad_edge_rejected(v0 in spec_gen::spec_file_with()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: bool_column_rejected
    // generator: `spec_file_with(state_row_having_bool_typed_column: true)`
    // predicate: `check(file) == failed`
    #[test]
    fn bool_column_rejected(v0 in spec_gen::spec_file_with()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: well_formed_model_passes
    // generator: `arbitrary_well_formed_state_machine()`
    // predicate: `check(file) == passed`
    #[test]
    fn well_formed_model_passes(v0 in spec_gen::arbitrary_well_formed_state_machine()) {
        todo_predicate!("`check(file) == passed`");
    }
}

proptest! {
    // id: pairing_failure_label_asserted
    // generator: `pairing_failure_raised()`
    // predicate: `error_label == "linter.model_shape.pairing_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn pairing_failure_label_asserted(v0 in spec_gen::pairing_failure_raised()) {
        todo_predicate!("`error_label == \"linter.model_shape.pairing_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
}

proptest! {
    // id: field_check_failure_label_asserted
    // generator: `field_check_failure_raised()`
    // predicate: `error_label == "linter.model_shape.field_check_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn field_check_failure_label_asserted(v0 in spec_gen::field_check_failure_raised()) {
        todo_predicate!("`error_label == \"linter.model_shape.field_check_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
}

