-----------------------------------------------------
MODULE linterschemashape
-----------------------------------------------------
\* Generated by `spk compile` from spec `linter.schema_shape` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"unchecked", "kind_checking", "diffing", "parser_audited", "passed", "failed"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "unchecked"

Next ==
  \* begin: unchecked -> kind_checking (guard: `file passed linter.frontmatter`)
  \/ vpc = "unchecked" /\ vpc' = "kind_checking"
  \* kind_ok: kind_checking -> diffing (guard: [[linter.schema_shape.constraint_kind_closed]] ∧ [[linter.schema_shape.property_kind_closed]])
  \/ vpc = "kind_checking" /\ vpc' = "diffing"
  \* kind_fail: kind_checking -> failed (guard: `¬kind_ok.guard`)
  \/ vpc = "kind_checking" /\ vpc' = "failed"
  \* diff_ok: diffing -> parser_audited (guard: [[linter.schema_shape.id_set_grows_only]] ∧ [[linter.schema_shape.id_set_order_stable]])
  \/ vpc = "diffing" /\ vpc' = "parser_audited"
  \* diff_skip: diffing -> parser_audited (guard: `no prior revision exists in repo history` — nothing to diff against yet)
  \/ vpc = "diffing" /\ vpc' = "parser_audited"
  \* diff_fail: diffing -> failed (guard: `¬(diff_ok.guard ∨ diff_skip.guard)`)
  \/ vpc = "diffing" /\ vpc' = "failed"
  \* accept: parser_audited -> passed (guard: [[linter.schema_shape.no_prose_field_parsed]] ∧ [[linter.schema_shape.prose_field_passthrough]])
  \/ vpc = "parser_audited" /\ vpc' = "passed"
  \* reject: parser_audited -> failed (guard: `¬accept.guard`)
  \/ vpc = "parser_audited" /\ vpc' = "failed"

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
