//! proptest scaffolding for `linter.schema_shape` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// The real element types and strategies are `verify`'s domain.
pub mod spec_gen {
    use super::*;

    pub fn constraint_row_with() -> impl Strategy<Value = GenVal> {
        Just(GenVal("constraint_row_with".into()))
    }

    pub fn property_row_with() -> impl Strategy<Value = GenVal> {
        Just(GenVal("property_row_with".into()))
    }

    pub fn arbitrary_file_with() -> impl Strategy<Value = GenVal> {
        Just(GenVal("arbitrary_file_with".into()))
    }

    pub fn arbitrary_unicode_string() -> impl Strategy<Value = GenVal> {
        Just(GenVal("arbitrary_unicode_string".into()))
    }

    pub fn parser_audit_over_every_ast_construction_site() -> impl Strategy<Value = GenVal> {
        Just(GenVal("parser_audit_over_every_ast_construction_site".into()))
    }

}

proptest! {
    // id: shrunk_id_set_rejected
    // generator: `(revision_n, revision_n_plus_1)` where a member was removed from a variant table, a kind value-set, or the Reference Typing table
    // predicate: `check(revisions) == failed` — one generator, parametrized over which of the three id-sets it targets
    #[test]
    fn shrunk_id_set_rejected() {
        todo_predicate!("`check(revisions) == failed` — one generator, parametrized over which of the three id-sets it targets");
    }
}

proptest! {
    // id: reordered_id_set_rejected
    // generator: `(revision_n, revision_n_plus_1)` where two existing members of any 𝒦-governed id-set swapped order
    // predicate: `check(revisions) == failed`
    #[test]
    fn reordered_id_set_rejected() {
        todo_predicate!("`check(revisions) == failed`");
    }
}

proptest! {
    // id: silent_narrowing_rejected
    // generator: `(revision_n, revision_n_plus_1)` where a Reference Typing field's target narrowed with no accompanying kind-split cited
    // predicate: `check(revisions) == failed`
    #[test]
    fn silent_narrowing_rejected() {
        todo_predicate!("`check(revisions) == failed`");
    }
}

proptest! {
    // id: constraint_kind_invalid_rejected
    // generator: `constraint_row_with(kind: "made_up")`
    // predicate: `check(file) == failed`
    #[test]
    fn constraint_kind_invalid_rejected(v0 in spec_gen::constraint_row_with()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: property_kind_invalid_rejected
    // generator: `property_row_with(kind: "audit")`
    // predicate: `check(file) == failed`
    #[test]
    fn property_kind_invalid_rejected(v0 in spec_gen::property_row_with()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: kind_closed_passes
    // generator: `arbitrary_file_with(only_closed_kind_values: true)`
    // predicate: `check(file) == passed`
    #[test]
    fn kind_closed_passes(v0 in spec_gen::arbitrary_file_with()) {
        todo_predicate!("`check(file) == passed`");
    }
}

proptest! {
    // id: prose_roundtrips
    // generator: `arbitrary_unicode_string()` as rationale content
    // predicate: `compile(parse(s)).rationale == s` — no normalization, no truncation
    #[test]
    fn prose_roundtrips(v0 in spec_gen::arbitrary_unicode_string()) {
        todo_predicate!("`compile(parse(s)).rationale == s` — no normalization, no truncation");
    }
}

proptest! {
    // id: appended_id_set_member_passes
    // generator: `(revision_n, revision_n_plus_1)` where only new members were added, to any of the three id-sets
    // predicate: `check(revisions) == passed`
    #[test]
    fn appended_id_set_member_passes() {
        todo_predicate!("`check(revisions) == passed`");
    }
}

proptest! {
    // id: constraint_kind_advisory_passes
    // generator: `constraint_row_with(kind: "advisory")`
    // predicate: `check(file) == passed`
    #[test]
    fn constraint_kind_advisory_passes(v0 in spec_gen::constraint_row_with()) {
        todo_predicate!("`check(file) == passed`");
    }
}

proptest! {
    // id: constraint_kind_effect_passes
    // generator: `constraint_row_with(kind: "effect")`
    // predicate: `check(file) == passed`
    #[test]
    fn constraint_kind_effect_passes(v0 in spec_gen::constraint_row_with()) {
        todo_predicate!("`check(file) == passed`");
    }
}

proptest! {
    // id: constraint_kind_extension_point_passes
    // generator: `constraint_row_with(kind: "extension_point")`
    // predicate: `check(file) == passed`
    #[test]
    fn constraint_kind_extension_point_passes(v0 in spec_gen::constraint_row_with()) {
        todo_predicate!("`check(file) == passed`");
    }
}

proptest! {
    // id: parser_ast_never_reads_prose
    // generator: `parser_audit_over_every_ast_construction_site()`
    // predicate: `no branch condition references the text of a rationale/description field` — the check itself is an implementation audit, see Notes
    #[test]
    fn parser_ast_never_reads_prose(v0 in spec_gen::parser_audit_over_every_ast_construction_site()) {
        todo_predicate!("`no branch condition references the text of a rationale/description field` — the check itself is an implementation audit, see Notes");
    }
}

