//! proptest scaffolding for `linter.observability` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// The real element types and strategies are `verify`'s domain.
pub mod spec_gen {
    use super::*;

    pub fn effect_with_zero_observes_edges() -> impl Strategy<Value = GenVal> {
        Just(GenVal("effect_with_zero_observes_edges".into()))
    }

    pub fn effect_with_at_least_one_observes_edge() -> impl Strategy<Value = GenVal> {
        Just(GenVal("effect_with_at_least_one_observes_edge".into()))
    }

    pub fn corpus_with_unobserved_effects() -> impl Strategy<Value = GenVal> {
        Just(GenVal("corpus_with_unobserved_effects".into()))
    }

    pub fn two_files_mutually_observing_each_others_effects() -> impl Strategy<Value = GenVal> {
        Just(GenVal("two_files_mutually_observing_each_others_effects".into()))
    }

    pub fn effect_row_pointing_observes_at_itself() -> impl Strategy<Value = GenVal> {
        Just(GenVal("effect_row_pointing_observes_at_itself".into()))
    }

    pub fn observes_pointing_at_an_absent_row() -> impl Strategy<Value = GenVal> {
        Just(GenVal("observes_pointing_at_an_absent_row".into()))
    }

}

proptest! {
    // id: unobserved_effect_warned
    // generator: `effect_with_zero_observes_edges()`
    // predicate: `exit 0 ∧ a warning naming the row id and the rule id linter.observability`
    #[test]
    fn unobserved_effect_warned(v0 in spec_gen::effect_with_zero_observes_edges()) {
        todo_predicate!("`exit 0 ∧ a warning naming the row id and the rule id linter.observability`");
    }
}

proptest! {
    // id: observed_effect_silent
    // generator: `effect_with_at_least_one_observes_edge()`
    // predicate: `no observability warning`
    #[test]
    fn observed_effect_silent(v0 in spec_gen::effect_with_at_least_one_observes_edge()) {
        todo_predicate!("`no observability warning`");
    }
}

proptest! {
    // id: warning_never_fails
    // generator: `corpus_with_unobserved_effects()`
    // predicate: `exit code 0 ∧ zero Issue findings attributable to this check`
    #[test]
    fn warning_never_fails(v0 in spec_gen::corpus_with_unobserved_effects()) {
        todo_predicate!("`exit code 0 ∧ zero Issue findings attributable to this check`");
    }
}

proptest! {
    // id: mutual_observation_passes
    // generator: `two_files_mutually_observing_each_others_effects()`
    // predicate: `both effects counted as observed — no warning`
    #[test]
    fn mutual_observation_passes(v0 in spec_gen::two_files_mutually_observing_each_others_effects()) {
        todo_predicate!("`both effects counted as observed — no warning`");
    }
}

proptest! {
    // id: self_observation_still_warned
    // generator: `effect_row_pointing_observes_at_itself()`
    // predicate: `warning fires — vacuous self-observation is not an observer`
    #[test]
    fn self_observation_still_warned(v0 in spec_gen::effect_row_pointing_observes_at_itself()) {
        todo_predicate!("`warning fires — vacuous self-observation is not an observer`");
    }
}

proptest! {
    // id: dangling_observes_not_doubled
    // generator: `observes_pointing_at_an_absent_row()`
    // predicate: `exactly one total_refs finding; zero observability warnings`
    #[test]
    fn dangling_observes_not_doubled(v0 in spec_gen::observes_pointing_at_an_absent_row()) {
        todo_predicate!("`exactly one total_refs finding; zero observability warnings`");
    }
}

proptest! {
    // id: waiver_input_ignored
    // generator: `corpus_with_unobserved_effects()`
    // predicate: `the warning fires regardless of any claimed-waiver text — no waiver channel exists`
    #[test]
    fn waiver_input_ignored(v0 in spec_gen::corpus_with_unobserved_effects()) {
        todo_predicate!("`the warning fires regardless of any claimed-waiver text — no waiver channel exists`");
    }
}

