//! proptest scaffolding for `linter.external_completeness` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// Each yields a String (the generator's name; executable
/// fragments bind these directly — Revision 15).
pub mod spec_gen {
    use super::*;

    pub fn checklist_item_with_no_mapping_row() -> impl Strategy<Value = String> {
        Just("checklist_item_with_no_mapping_row".into())
    }

    pub fn mapping_row_with() -> impl Strategy<Value = String> {
        Just("mapping_row_with".into())
    }

    pub fn two_mapping_rows_targeting_the_same_checklist_item() -> impl Strategy<Value = String> {
        Just("two_mapping_rows_targeting_the_same_checklist_item".into())
    }

    pub fn checklist_where_every_item_has_a_covered_or_waived_mapping() -> impl Strategy<Value = String> {
        Just("checklist_where_every_item_has_a_covered_or_waived_mapping".into())
    }

    pub fn repo_with_no_declared_checklist() -> impl Strategy<Value = String> {
        Just("repo_with_no_declared_checklist".into())
    }

    pub fn arbitrary_repo_with_checklist() -> impl Strategy<Value = String> {
        Just("arbitrary_repo_with_checklist".into())
    }

    pub fn arbitrary_id_rename() -> impl Strategy<Value = String> {
        Just("arbitrary_id_rename".into())
    }

    pub fn declared_checklist_with() -> impl Strategy<Value = String> {
        Just("declared_checklist_with".into())
    }

    pub fn manifest_failure_raised() -> impl Strategy<Value = String> {
        Just("manifest_failure_raised".into())
    }

    pub fn mapping_failure_raised() -> impl Strategy<Value = String> {
        Just("mapping_failure_raised".into())
    }

    pub fn resolution_failure_raised() -> impl Strategy<Value = String> {
        Just("resolution_failure_raised".into())
    }

}

proptest! {
    // id: unmapped_item_rejected
    // generator: `checklist_item_with_no_mapping_row()`
    // predicate: `check(repo) == failed`
    #[test]
    fn unmapped_item_rejected(v0 in spec_gen::checklist_item_with_no_mapping_row()) {
        todo_predicate!("`check(repo) == failed`");
    }
    // id: dangling_mapped_id_rejected
    // generator: `mapping_row_with(status: "covered", mapped_ids: ["nonexistent.id"])`
    // predicate: `check(repo) == failed`
    #[test]
    fn dangling_mapped_id_rejected(v0 in spec_gen::mapping_row_with()) {
        todo_predicate!("`check(repo) == failed`");
    }
    // id: unrationalized_waiver_rejected
    // generator: `mapping_row_with(status: "waived", rationale: "")`
    // predicate: `check(repo) == failed`
    #[test]
    fn unrationalized_waiver_rejected(v0 in spec_gen::mapping_row_with()) {
        todo_predicate!("`check(repo) == failed`");
    }
    // id: duplicate_claim_rejected
    // generator: `two_mapping_rows_targeting_the_same_checklist_item()`
    // predicate: `check(repo) == failed`
    #[test]
    fn duplicate_claim_rejected(v0 in spec_gen::two_mapping_rows_targeting_the_same_checklist_item()) {
        todo_predicate!("`check(repo) == failed`");
    }
    // id: fully_mapped_checklist_passes
    // generator: `checklist_where_every_item_has_a_covered_or_waived_mapping()`
    // predicate: `check(repo) == passed`
    #[test]
    fn fully_mapped_checklist_passes(v0 in spec_gen::checklist_where_every_item_has_a_covered_or_waived_mapping()) {
        todo_predicate!("`check(repo) == passed`");
    }
    // id: no_checklist_not_applicable
    // generator: `repo_with_no_declared_checklist()`
    // predicate: `check(repo) == not_applicable` — distinct from `passed`, see Notes
    #[test]
    fn no_checklist_not_applicable(v0 in spec_gen::repo_with_no_declared_checklist()) {
        todo_predicate!("`check(repo) == not_applicable` — distinct from `passed`, see Notes");
    }
    // id: mapping_naturality
    // case: identity
    // generator: `arbitrary_repo_with_checklist(), arbitrary_id_rename()`
    // predicate: **identity:** `mapped(repo renamed to itself) == mapped(repo)` — the rename identity case instantiated at the mapped-ids observation point  **associativity:** `mapped(rename(rename(I, a, b), b, c)) == mapped(rename(I, a, c))` — the rename associativity case at the same observation point  **naturality:** `mapped(rename(I)) == rename(mapped(I))` — renaming a constraint or property id updates every `mapped_ids` cell claiming it, the same as any other reference
    #[test]
    fn mapping_naturality_identity(v0 in spec_gen::arbitrary_repo_with_checklist(), v1 in spec_gen::arbitrary_id_rename()) {
        todo_predicate!("**identity:** `mapped(repo renamed to itself) == mapped(repo)` — the rename identity case instantiated at the mapped-ids observation point  **associativity:** `mapped(rename(rename(I, a, b), b, c)) == mapped(rename(I, a, c))` — the rename associativity case at the same observation point  **naturality:** `mapped(rename(I)) == rename(mapped(I))` — renaming a constraint or property id updates every `mapped_ids` cell claiming it, the same as any other reference");
    }
    // id: mapping_naturality
    // case: associativity
    // generator: `arbitrary_repo_with_checklist(), arbitrary_id_rename()`
    // predicate: **identity:** `mapped(repo renamed to itself) == mapped(repo)` — the rename identity case instantiated at the mapped-ids observation point  **associativity:** `mapped(rename(rename(I, a, b), b, c)) == mapped(rename(I, a, c))` — the rename associativity case at the same observation point  **naturality:** `mapped(rename(I)) == rename(mapped(I))` — renaming a constraint or property id updates every `mapped_ids` cell claiming it, the same as any other reference
    #[test]
    fn mapping_naturality_associativity(v0 in spec_gen::arbitrary_repo_with_checklist(), v1 in spec_gen::arbitrary_id_rename()) {
        todo_predicate!("**identity:** `mapped(repo renamed to itself) == mapped(repo)` — the rename identity case instantiated at the mapped-ids observation point  **associativity:** `mapped(rename(rename(I, a, b), b, c)) == mapped(rename(I, a, c))` — the rename associativity case at the same observation point  **naturality:** `mapped(rename(I)) == rename(mapped(I))` — renaming a constraint or property id updates every `mapped_ids` cell claiming it, the same as any other reference");
    }
    // id: mapping_naturality
    // case: naturality
    // generator: `arbitrary_repo_with_checklist(), arbitrary_id_rename()`
    // predicate: **identity:** `mapped(repo renamed to itself) == mapped(repo)` — the rename identity case instantiated at the mapped-ids observation point  **associativity:** `mapped(rename(rename(I, a, b), b, c)) == mapped(rename(I, a, c))` — the rename associativity case at the same observation point  **naturality:** `mapped(rename(I)) == rename(mapped(I))` — renaming a constraint or property id updates every `mapped_ids` cell claiming it, the same as any other reference
    #[test]
    fn mapping_naturality_naturality(v0 in spec_gen::arbitrary_repo_with_checklist(), v1 in spec_gen::arbitrary_id_rename()) {
        todo_predicate!("**identity:** `mapped(repo renamed to itself) == mapped(repo)` — the rename identity case instantiated at the mapped-ids observation point  **associativity:** `mapped(rename(rename(I, a, b), b, c)) == mapped(rename(I, a, c))` — the rename associativity case at the same observation point  **naturality:** `mapped(rename(I)) == rename(mapped(I))` — renaming a constraint or property id updates every `mapped_ids` cell claiming it, the same as any other reference");
    }
    // id: malformed_checklist_rejected
    // generator: `declared_checklist_with(a_nested_item, an_item_missing_its_id)`
    // predicate: `check(repo) == failed`
    #[test]
    fn malformed_checklist_rejected(v0 in spec_gen::declared_checklist_with()) {
        todo_predicate!("`check(repo) == failed`");
    }
    // id: manifest_failure_label_asserted
    // generator: `manifest_failure_raised()`
    // predicate: `error_label == "linter.external_completeness.manifest_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn manifest_failure_label_asserted(v0 in spec_gen::manifest_failure_raised()) {
        todo_predicate!("`error_label == \"linter.external_completeness.manifest_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
    // id: mapping_failure_label_asserted
    // generator: `mapping_failure_raised()`
    // predicate: `error_label == "linter.external_completeness.mapping_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn mapping_failure_label_asserted(v0 in spec_gen::mapping_failure_raised()) {
        todo_predicate!("`error_label == \"linter.external_completeness.mapping_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
    // id: resolution_failure_label_asserted
    // generator: `resolution_failure_raised()`
    // predicate: `error_label == "linter.external_completeness.resolution_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn resolution_failure_label_asserted(v0 in spec_gen::resolution_failure_raised()) {
        todo_predicate!("`error_label == \"linter.external_completeness.resolution_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
}

