//! proptest scaffolding for `merge` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// Each yields a String (the generator's name; executable
/// fragments bind these directly — Revision 15).
pub mod spec_gen {
    use super::*;

    pub fn two_branches_each_independently_defining_new_id() -> impl Strategy<Value = String> {
        Just("two_branches_each_independently_defining_new_id".into())
    }

    pub fn id_defined_in_common_ancestor_unchanged_in_both_branches() -> impl Strategy<Value = String> {
        Just("id_defined_in_common_ancestor_unchanged_in_both_branches".into())
    }

    pub fn branch_A() -> impl Strategy<Value = String> {
        Just("branch_A".into())
    }

    pub fn branch_B() -> impl Strategy<Value = String> {
        Just("branch_B".into())
    }

    pub fn two_branches_touching_disjoint_namespaces_with_disjoint_blast_radii() -> impl Strategy<Value = String> {
        Just("two_branches_touching_disjoint_namespaces_with_disjoint_blast_radii".into())
    }

    pub fn both_branches_add_a_CHANGELOG_entry_claiming_the_same_next_number() -> impl Strategy<Value = String> {
        Just("both_branches_add_a_CHANGELOG_entry_claiming_the_same_next_number".into())
    }

    pub fn merge_where() -> impl Strategy<Value = String> {
        Just("merge_where".into())
    }

    pub fn _radii_were_recorded() -> impl Strategy<Value = String> {
        Just("_radii_were_recorded".into())
    }

    pub fn merge_invoked_with_the_markdown_walker_patched_to_panic() -> impl Strategy<Value = String> {
        Just("merge_invoked_with_the_markdown_walker_patched_to_panic".into())
    }

    pub fn collision_failure_raised() -> impl Strategy<Value = String> {
        Just("collision_failure_raised".into())
    }

    pub fn reverification_failure_raised() -> impl Strategy<Value = String> {
        Just("reverification_failure_raised".into())
    }

    pub fn merge_aborted_raised() -> impl Strategy<Value = String> {
        Just("merge_aborted_raised".into())
    }

}

proptest! {
    // id: collision_across_branches_rejected
    // generator: `two_branches_each_independently_defining_new_id("x")`
    // predicate: `check(merge) == failed`
    #[test]
    fn collision_across_branches_rejected(v0 in spec_gen::two_branches_each_independently_defining_new_id()) {
        todo_predicate!("`check(merge) == failed`");
    }
    // id: inherited_id_not_falsely_flagged
    // generator: `id_defined_in_common_ancestor_unchanged_in_both_branches()`
    // predicate: `check(merge) != failed`
    #[test]
    fn inherited_id_not_falsely_flagged(v0 in spec_gen::id_defined_in_common_ancestor_unchanged_in_both_branches()) {
        todo_predicate!("`check(merge) != failed`");
    }
    // id: textually_clean_semantic_conflict_flagged
    // generator: `branch_A(renames x to y), branch_B(adds a new [[x]] reference in a file branch_A never touched)`
    // predicate: `check(merge) == needs_review`
    #[test]
    fn textually_clean_semantic_conflict_flagged(v0 in spec_gen::branch_A(), v1 in spec_gen::branch_B()) {
        todo_predicate!("`check(merge) == needs_review`");
    }
}

// id: rename_replay_repairs_dangling_ref
// generator: `same scenario, after human approval`
// predicate: `post_merge_repo has zero occurrences of [[x]]; branch_B's new reference now reads [[y]]`
#[test]
fn rename_replay_repairs_dangling_ref() {
        todo_predicate!("`post_merge_repo has zero occurrences of [[x]]; branch_B's new reference now reads [[y]]`");
}

proptest! {
    // id: disjoint_blast_radii_auto_merge
    // generator: `two_branches_touching_disjoint_namespaces_with_disjoint_blast_radii()`
    // predicate: `check(merge) == merged` — no human review required
    #[test]
    fn disjoint_blast_radii_auto_merge(v0 in spec_gen::two_branches_touching_disjoint_namespaces_with_disjoint_blast_radii()) {
        todo_predicate!("`check(merge) == merged` — no human review required");
    }
    // id: duplicate_sequential_number_renumbered
    // generator: `both_branches_add_a_CHANGELOG_entry_claiming_the_same_next_number()`
    // predicate: `post_merge_repo has two distinct sequential numbers; neither is duplicated`
    #[test]
    fn duplicate_sequential_number_renumbered(v0 in spec_gen::both_branches_add_a_CHANGELOG_entry_claiming_the_same_next_number()) {
        todo_predicate!("`post_merge_repo has two distinct sequential numbers; neither is duplicated`");
    }
    // id: relint_gates_merge
    // generator: `merge_where(linter.referential_integrity or linter.graph_shape: fails against the merged tree)`
    // predicate: `check(merge) == failed` — mirrors `rename.md`'s `stray_ref_caught_by_verify`
    #[test]
    fn relint_gates_merge(v0 in spec_gen::merge_where()) {
        todo_predicate!("`check(merge) == failed` — mirrors `rename.md`'s `stray_ref_caught_by_verify`");
    }
    // id: blast_radius_recorded_before_apply
    // generator: `merge_history_where_edits_were_applied_before_both_branches'_radii_were_recorded()`
    // predicate: `check(merge) == failed` — apply never precedes the recording step, for either branch
    #[test]
    fn blast_radius_recorded_before_apply(v0 in spec_gen::_radii_were_recorded()) {
        todo_predicate!("`check(merge) == failed` — apply never precedes the recording step, for either branch");
    }
    // id: reachability_from_graph_artifact_only
    // generator: `merge_invoked_with_the_markdown_walker_patched_to_panic()`
    // predicate: `merge of an otherwise-clean diverged repo succeeds` — collision and blast-radius checks only query [[graph]]'s artifact
    #[test]
    fn reachability_from_graph_artifact_only(v0 in spec_gen::merge_invoked_with_the_markdown_walker_patched_to_panic()) {
        todo_predicate!("`merge of an otherwise-clean diverged repo succeeds` — collision and blast-radius checks only query [[graph]]'s artifact");
    }
    // id: collision_failure_label_asserted
    // generator: `collision_failure_raised()`
    // predicate: `error_label == "merge.collision_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn collision_failure_label_asserted(v0 in spec_gen::collision_failure_raised()) {
        todo_predicate!("`error_label == \"merge.collision_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
    // id: reverification_failure_label_asserted
    // generator: `reverification_failure_raised()`
    // predicate: `error_label == "merge.reverification_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn reverification_failure_label_asserted(v0 in spec_gen::reverification_failure_raised()) {
        todo_predicate!("`error_label == \"merge.reverification_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
    // id: merge_aborted_label_asserted
    // generator: `merge_aborted_raised()`
    // predicate: `error_label == "merge.merge_aborted"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn merge_aborted_label_asserted(v0 in spec_gen::merge_aborted_raised()) {
        todo_predicate!("`error_label == \"merge.merge_aborted\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
}

