-----------------------------------------
MODULE merge
-----------------------------------------
\* Generated by `spk compile` from spec `merge` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"diverged", "collision_checked", "needs_review", "rename_replayed", "ref_integrity_reverified", "merged", "failed"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "diverged"

Next ==
  \* check_collisions: diverged -> collision_checked (guard: [[merge.no_new_id_collision]] ∧ [[merge.graph_reused_not_rederived]])
  \/ vpc = "diverged" /\ vpc' = "collision_checked"
  \* collision_fail: diverged -> failed (guard: `¬check_collisions.guard`)
  \/ vpc = "diverged" /\ vpc' = "failed"
  \* flag_review: collision_checked -> needs_review (guard: [[merge.semantic_conflict_iff_blast_radius_intersects]] ∧ [[merge.blast_radii_recorded_pre_merge]])
  \/ vpc = "collision_checked" /\ vpc' = "needs_review"
  \* auto_proceed: collision_checked -> rename_replayed (guard: `¬flag_review.guard` ∧ [[merge.rename_replayed_onto_foreign_edits]])
  \/ vpc = "collision_checked" /\ vpc' = "rename_replayed"
  \* resolved: needs_review -> rename_replayed (guard: `a human has explicitly approved merging the intersecting blast radii` ∧ [[merge.rename_replayed_onto_foreign_edits]])
  \/ vpc = "needs_review" /\ vpc' = "rename_replayed"
  \* reverify: rename_replayed -> ref_integrity_reverified (guard: [[merge.post_merge_relint_required]])
  \/ vpc = "rename_replayed" /\ vpc' = "ref_integrity_reverified"
  \* reverify_fail: rename_replayed -> failed (guard: `¬reverify.guard`)
  \/ vpc = "rename_replayed" /\ vpc' = "failed"
  \* accept: ref_integrity_reverified -> merged (guard: [[merge.sequential_number_reassigned_on_conflict]])
  \/ vpc = "ref_integrity_reverified" /\ vpc' = "merged"
  \* reject: ref_integrity_reverified -> failed (guard: `¬accept.guard`)
  \/ vpc = "ref_integrity_reverified" /\ vpc' = "failed"

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
