//! proptest scaffolding for `model_check` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// Each yields a String (the generator's name; executable
/// fragments bind these directly — Revision 15).
pub mod spec_gen {
    use super::*;

    pub fn compiled_module_with_zero_runs_against_it() -> impl Strategy<Value = String> {
        Just("compiled_module_with_zero_runs_against_it".into())
    }

    pub fn run_report_with_no_stated_bound() -> impl Strategy<Value = String> {
        Just("run_report_with_no_stated_bound".into())
    }

    pub fn model_with() -> impl Strategy<Value = String> {
        Just("model_with".into())
    }

    pub fn model_with_exactly_one_violated_invariant() -> impl Strategy<Value = String> {
        Just("model_with_exactly_one_violated_invariant".into())
    }

    pub fn run_report_from_any_backend() -> impl Strategy<Value = String> {
        Just("run_report_from_any_backend".into())
    }

    pub fn arbitrary_model_with_no_violation_within_bound() -> impl Strategy<Value = String> {
        Just("arbitrary_model_with_no_violation_within_bound".into())
    }

    pub fn model_with_only_prose_invariants_exhausted_within_bound() -> impl Strategy<Value = String> {
        Just("model_with_only_prose_invariants_exhausted_within_bound".into())
    }

    pub fn compiled_model_with_one_executable_invariant() -> impl Strategy<Value = String> {
        Just("compiled_model_with_one_executable_invariant".into())
    }

    pub fn model_with_executable_invariants_no_violation() -> impl Strategy<Value = String> {
        Just("model_with_executable_invariants_no_violation".into())
    }

    pub fn model_with_panicking_invariant_fragment() -> impl Strategy<Value = String> {
        Just("model_with_panicking_invariant_fragment".into())
    }

    pub fn model_with_falsifiable_executable_invariant() -> impl Strategy<Value = String> {
        Just("model_with_falsifiable_executable_invariant".into())
    }

}

proptest! {
    // id: stale_claim_rejected
    // generator: `compiled_module_with_zero_runs_against_it()`
    // predicate: `no_counterexample(file) == undetermined` — never defaults to true
    #[test]
    fn stale_claim_rejected(v0 in spec_gen::compiled_module_with_zero_runs_against_it()) {
        todo_predicate!("`no_counterexample(file) == undetermined` — never defaults to true");
    }
    // id: bound_must_be_stated
    // generator: `run_report_with_no_stated_bound()`
    // predicate: `check(report) == invalid`
    #[test]
    fn bound_must_be_stated(v0 in spec_gen::run_report_with_no_stated_bound()) {
        todo_predicate!("`check(report) == invalid`");
    }
    // id: shortest_counterexample_reported
    // generator: `model_with(two_violating_traces_of_different_length: true)`
    // predicate: `reported_trace(check(model)) == the_shorter_of_the_two`
    #[test]
    fn shortest_counterexample_reported(v0 in spec_gen::model_with()) {
        todo_predicate!("`reported_trace(check(model)) == the_shorter_of_the_two`");
    }
    // id: violated_invariant_named
    // generator: `model_with_exactly_one_violated_invariant()`
    // predicate: `check(model).violated_invariant_id == the_expected_id`
    #[test]
    fn violated_invariant_named(v0 in spec_gen::model_with_exactly_one_violated_invariant()) {
        todo_predicate!("`check(model).violated_invariant_id == the_expected_id`");
    }
    // id: backend_named_in_report
    // generator: `run_report_from_any_backend()`
    // predicate: `check(report).backend == a named engine and version`
    #[test]
    fn backend_named_in_report(v0 in spec_gen::run_report_from_any_backend()) {
        todo_predicate!("`check(report).backend == a named engine and version`");
    }
    // id: clean_run_satisfies_verify_gate
    // generator: `arbitrary_model_with_no_violation_within_bound()`
    // predicate: `no_counterexample(file) == true`
    #[test]
    fn clean_run_satisfies_verify_gate(v0 in spec_gen::arbitrary_model_with_no_violation_within_bound()) {
        todo_predicate!("`no_counterexample(file) == true`");
    }
}

// id: stale_result_invalidated_by_edit
// generator: `(clean_run, model_edited_afterward_with_no_rerun)`
// predicate: `no_counterexample(file) == false` — until re-run
#[test]
fn stale_result_invalidated_by_edit() {
        todo_predicate!("`no_counterexample(file) == false` — until re-run");
}

proptest! {
    // id: clean_model_passes
    // generator: `arbitrary_model_with_no_violation_within_bound()`
    // predicate: `check(model) == clean`
    #[test]
    fn clean_model_passes(v0 in spec_gen::arbitrary_model_with_no_violation_within_bound()) {
        todo_predicate!("`check(model) == clean`");
    }
    // id: exploration_run_is_not_a_clean_verdict
    // generator: `model_with_only_prose_invariants_exhausted_within_bound()`
    // predicate: `check(model).outcome == exploration_only` — never read as no_counterexample
    #[test]
    fn exploration_run_is_not_a_clean_verdict(v0 in spec_gen::model_with_only_prose_invariants_exhausted_within_bound()) {
        todo_predicate!("`check(model).outcome == exploration_only` — never read as no_counterexample");
    }
    // id: fragment_invariants_checked
    // generator: `compiled_model_with_one_executable_invariant()`
    // predicate: `check(model).invariants_checked == [the_invariant_id]`
    #[test]
    fn fragment_invariants_checked(v0 in spec_gen::compiled_model_with_one_executable_invariant()) {
        todo_predicate!("`check(model).invariants_checked == [the_invariant_id]`");
    }
    // id: fragment_clean_run_is_no_counterexample
    // generator: `model_with_executable_invariants_no_violation()`
    // predicate: `check(model).outcome == no_counterexample` — the model gate's reachable leg
    #[test]
    fn fragment_clean_run_is_no_counterexample(v0 in spec_gen::model_with_executable_invariants_no_violation()) {
        todo_predicate!("`check(model).outcome == no_counterexample` — the model gate's reachable leg");
    }
    // id: panicking_fragment_violates
    // generator: `model_with_panicking_invariant_fragment()`
    // predicate: `check(model).outcome == counterexample_found ∧ violated_invariant_id == the_panicking_id`
    #[test]
    fn panicking_fragment_violates(v0 in spec_gen::model_with_panicking_invariant_fragment()) {
        todo_predicate!("`check(model).outcome == counterexample_found ∧ violated_invariant_id == the_panicking_id`");
    }
    // id: fragment_violation_traces
    // generator: `model_with_falsifiable_executable_invariant()`
    // predicate: `check(model).trace == the_reachable_state_path` — the trace leg is the existing constraint's, not a new one
    #[test]
    fn fragment_violation_traces(v0 in spec_gen::model_with_falsifiable_executable_invariant()) {
        todo_predicate!("`check(model).trace == the_reachable_state_path` — the trace leg is the existing constraint's, not a new one");
    }
}

