---- MODULE modelcheck ----
\* Generated by `spk compile` from spec `model_check` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"not_run", "running", "clean", "counterexample_found", "timed_out", "exploration_only"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "not_run"

Next ==
  \* begin: not_run -> running (guard: [[model_check.checker_invoked]])
  \/ vpc = "not_run" /\ vpc' = "running"
  \* finish_clean: running -> clean (guard: [[model_check.exhaustive_within_bound]] ∧ `no violation found within the bound`)
  \/ vpc = "running" /\ vpc' = "clean"
  \* finish_violation: running -> counterexample_found (guard: [[model_check.counterexample_is_minimal]] ∧ [[model_check.counterexample_names_violated_invariant]])
  \/ vpc = "running" /\ vpc' = "counterexample_found"
  \* finish_timeout: running -> timed_out (guard: `the stated bound was not reached before the run's time/state budget expired`)
  \/ vpc = "running" /\ vpc' = "timed_out"
  \* finish_exploration: running -> exploration_only (guard: [[model_check.exhaustive_within_bound]] ∧ `the backend executed no invariant predicates — a completed exploration is evidence the space ends within the bound, never that the model holds`)
  \/ vpc = "running" /\ vpc' = "exploration_only"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
