//! proptest scaffolding for `model_check` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// Each yields a String (the generator's name; executable
/// fragments bind these directly — Revision 15).
pub mod spec_gen {
    use super::*;

    pub fn compiled_module_with_zero_runs_against_it() -> impl Strategy<Value = String> {
        Just("compiled_module_with_zero_runs_against_it".into())
    }

    pub fn run_report_with_no_stated_bound() -> impl Strategy<Value = String> {
        Just("run_report_with_no_stated_bound".into())
    }

    pub fn model_with() -> impl Strategy<Value = String> {
        Just("model_with".into())
    }

    pub fn model_with_exactly_one_violated_invariant() -> impl Strategy<Value = String> {
        Just("model_with_exactly_one_violated_invariant".into())
    }

    pub fn run_report_from_any_backend() -> impl Strategy<Value = String> {
        Just("run_report_from_any_backend".into())
    }

    pub fn arbitrary_model_with_no_violation_within_bound() -> impl Strategy<Value = String> {
        Just("arbitrary_model_with_no_violation_within_bound".into())
    }

    pub fn model_with_only_prose_invariants_exhausted_within_bound() -> impl Strategy<Value = String> {
        Just("model_with_only_prose_invariants_exhausted_within_bound".into())
    }

    pub fn compiled_model_with_one_executable_invariant() -> impl Strategy<Value = String> {
        Just("compiled_model_with_one_executable_invariant".into())
    }

    pub fn model_with_executable_invariants_no_violation() -> impl Strategy<Value = String> {
        Just("model_with_executable_invariants_no_violation".into())
    }

    pub fn model_with_panicking_invariant_fragment() -> impl Strategy<Value = String> {
        Just("model_with_panicking_invariant_fragment".into())
    }

    pub fn model_with_falsifiable_executable_invariant() -> impl Strategy<Value = String> {
        Just("model_with_falsifiable_executable_invariant".into())
    }

    pub fn model_with_only_prose_invariants() -> impl Strategy<Value = String> {
        Just("model_with_only_prose_invariants".into())
    }

    pub fn run_report_from_current_inputs() -> impl Strategy<Value = String> {
        Just("run_report_from_current_inputs".into())
    }

    pub fn same_structured_inputs_in_different_cli_order() -> impl Strategy<Value = String> {
        Just("same_structured_inputs_in_different_cli_order".into())
    }

    pub fn two_files_same_claim_names_opposite_invariants() -> impl Strategy<Value = String> {
        Just("two_files_same_claim_names_opposite_invariants".into())
    }

    pub fn id_spec_file_plus_any_other_parsed_input() -> impl Strategy<Value = String> {
        Just("id_spec_file_plus_any_other_parsed_input".into())
    }

    pub fn several_dual_format_files_linted_together() -> impl Strategy<Value = String> {
        Just("several_dual_format_files_linted_together".into())
    }

}

proptest! {
    // id: stale_claim_rejected
    // generator: `compiled_module_with_zero_runs_against_it()`
    // predicate: `no_counterexample(file) == undetermined` — never defaults to true
    #[test]
    fn stale_claim_rejected(v0 in spec_gen::compiled_module_with_zero_runs_against_it()) {
        todo_predicate!("`no_counterexample(file) == undetermined` — never defaults to true");
    }
    // id: bound_must_be_stated
    // generator: `run_report_with_no_stated_bound()`
    // predicate: `check(report) == invalid`
    #[test]
    fn bound_must_be_stated(v0 in spec_gen::run_report_with_no_stated_bound()) {
        todo_predicate!("`check(report) == invalid`");
    }
    // id: shortest_counterexample_reported
    // generator: `model_with(two_violating_traces_of_different_length: true)`
    // predicate: `reported_trace(check(model)) == the_shorter_of_the_two`
    #[test]
    fn shortest_counterexample_reported(v0 in spec_gen::model_with()) {
        todo_predicate!("`reported_trace(check(model)) == the_shorter_of_the_two`");
    }
    // id: violated_invariant_named
    // generator: `model_with_exactly_one_violated_invariant()`
    // predicate: `check(model).violated_invariant_id == the_expected_id`
    #[test]
    fn violated_invariant_named(v0 in spec_gen::model_with_exactly_one_violated_invariant()) {
        todo_predicate!("`check(model).violated_invariant_id == the_expected_id`");
    }
    // id: backend_named_in_report
    // generator: `run_report_from_any_backend()`
    // predicate: `check(report).backend == a named engine and version`
    #[test]
    fn backend_named_in_report(v0 in spec_gen::run_report_from_any_backend()) {
        todo_predicate!("`check(report).backend == a named engine and version`");
    }
    // id: clean_run_satisfies_verify_gate
    // generator: `arbitrary_model_with_no_violation_within_bound()`
    // predicate: `no_counterexample(file) == true`
    #[test]
    fn clean_run_satisfies_verify_gate(v0 in spec_gen::arbitrary_model_with_no_violation_within_bound()) {
        todo_predicate!("`no_counterexample(file) == true`");
    }
}

// id: stale_result_invalidated_by_edit
// generator: `(clean_run, model_edited_afterward_with_no_rerun)`
// predicate: `no_counterexample(file) == false` — until re-run
#[test]
fn stale_result_invalidated_by_edit() {
        todo_predicate!("`no_counterexample(file) == false` — until re-run");
}

proptest! {
    // id: clean_model_passes
    // generator: `arbitrary_model_with_no_violation_within_bound()`
    // predicate: `check(model) == clean`
    #[test]
    fn clean_model_passes(v0 in spec_gen::arbitrary_model_with_no_violation_within_bound()) {
        todo_predicate!("`check(model) == clean`");
    }
    // id: exploration_run_is_not_a_clean_verdict
    // generator: `model_with_only_prose_invariants_exhausted_within_bound()`
    // predicate: `check(model).outcome == exploration_only` — never read as no_counterexample
    #[test]
    fn exploration_run_is_not_a_clean_verdict(v0 in spec_gen::model_with_only_prose_invariants_exhausted_within_bound()) {
        todo_predicate!("`check(model).outcome == exploration_only` — never read as no_counterexample");
    }
    // id: fragment_invariants_checked
    // generator: `compiled_model_with_one_executable_invariant()`
    // predicate: `check(model).invariants_checked == [the_invariant_id]`
    #[test]
    fn fragment_invariants_checked(v0 in spec_gen::compiled_model_with_one_executable_invariant()) {
        todo_predicate!("`check(model).invariants_checked == [the_invariant_id]`");
    }
    // id: fragment_clean_run_is_no_counterexample
    // generator: `model_with_executable_invariants_no_violation()`
    // predicate: `check(model).outcome == no_counterexample` — the model gate's reachable leg
    #[test]
    fn fragment_clean_run_is_no_counterexample(v0 in spec_gen::model_with_executable_invariants_no_violation()) {
        todo_predicate!("`check(model).outcome == no_counterexample` — the model gate's reachable leg");
    }
    // id: panicking_fragment_violates
    // generator: `model_with_panicking_invariant_fragment()`
    // predicate: `check(model).outcome == counterexample_found ∧ violated_invariant_id == the_panicking_id`
    #[test]
    fn panicking_fragment_violates(v0 in spec_gen::model_with_panicking_invariant_fragment()) {
        todo_predicate!("`check(model).outcome == counterexample_found ∧ violated_invariant_id == the_panicking_id`");
    }
    // id: fragment_violation_traces
    // generator: `model_with_falsifiable_executable_invariant()`
    // predicate: `check(model).trace == the_reachable_state_path` — the trace leg is the existing constraint's, not a new one
    #[test]
    fn fragment_violation_traces(v0 in spec_gen::model_with_falsifiable_executable_invariant()) {
        todo_predicate!("`check(model).trace == the_reachable_state_path` — the trace leg is the existing constraint's, not a new one");
    }
    // id: false_claim_is_counterexample_found
    // generator: `model_with(passing_rust_claim, counterexample_kernel_claim)`
    // predicate: `check(model) == counterexample_found naming the false claim id` — a passing Rust claim never hides it
    #[test]
    fn false_claim_is_counterexample_found(v0 in spec_gen::model_with()) {
        todo_predicate!("`check(model) == counterexample_found naming the false claim id` — a passing Rust claim never hides it");
    }
    // id: unknown_or_missing_claim_blocks_clean
    // generator: `model_with(unknown_or_missing_required_claim)`
    // predicate: `check(model) == exploration_only with reasons naming the claim ids`
    #[test]
    fn unknown_or_missing_claim_blocks_clean(v0 in spec_gen::model_with()) {
        todo_predicate!("`check(model) == exploration_only with reasons naming the claim ids`");
    }
    // id: exhausted_bound_stays_timed_out
    // generator: `model_with(all_verified_claims_but_exhausted_bound)`
    // predicate: `check(model) == timed_out` — verified claims cannot outrank an incomplete exploration
    #[test]
    fn exhausted_bound_stays_timed_out(v0 in spec_gen::model_with()) {
        todo_predicate!("`check(model) == timed_out` — verified claims cannot outrank an incomplete exploration");
    }
    // id: prose_only_is_unchecked_not_required
    // generator: `model_with_only_prose_invariants()`
    // predicate: `required_claims(model) == [] ∧ unchecked_claims(model) == those ids` — never implied verified
    #[test]
    fn prose_only_is_unchecked_not_required(v0 in spec_gen::model_with_only_prose_invariants()) {
        todo_predicate!("`required_claims(model) == [] ∧ unchecked_claims(model) == those ids` — never implied verified");
    }
    // id: report_binds_claims_and_scope_digest
    // generator: `run_report_from_current_inputs()`
    // predicate: `report.claim_schema_version == 1 ∧ expected/unchecked ids present ∧ scope_sha256 present`
    #[test]
    fn report_binds_claims_and_scope_digest(v0 in spec_gen::run_report_from_current_inputs()) {
        todo_predicate!("`report.claim_schema_version == 1 ∧ expected/unchecked ids present ∧ scope_sha256 present`");
    }
    // id: reordered_paths_and_prose_preserve_scope
    // generator: `same_structured_inputs_in_different_cli_order()`
    // predicate: `scope_sha256 unchanged` — the digest binds content, not paths
    #[test]
    fn reordered_paths_and_prose_preserve_scope(v0 in spec_gen::same_structured_inputs_in_different_cli_order()) {
        todo_predicate!("`scope_sha256 unchanged` — the digest binds content, not paths");
    }
    // id: swapped_reports_rejected_unrewritten
    // generator: `two_files_same_claim_names_opposite_invariants()`
    // predicate: `digest(a) ≠ digest(b) ∧ each run rejects the other's report without rewriting it`
    #[test]
    fn swapped_reports_rejected_unrewritten(v0 in spec_gen::two_files_same_claim_names_opposite_invariants()) {
        todo_predicate!("`digest(a) ≠ digest(b) ∧ each run rejects the other's report without rewriting it`");
    }
    // id: combined_dual_format_scope_refused
    // generator: `id_spec_file_plus_any_other_parsed_input()`
    // predicate: `check(invocation) == isolated_scope_required` before any artifact or report write
    #[test]
    fn combined_dual_format_scope_refused(v0 in spec_gen::id_spec_file_plus_any_other_parsed_input()) {
        todo_predicate!("`check(invocation) == isolated_scope_required` before any artifact or report write");
    }
    // id: multi_file_dual_format_lint_stays_valid
    // generator: `several_dual_format_files_linted_together()`
    // predicate: `check(lint) == valid` — the isolation is a command-evaluation rule, not a lint rule
    #[test]
    fn multi_file_dual_format_lint_stays_valid(v0 in spec_gen::several_dual_format_files_linted_together()) {
        todo_predicate!("`check(lint) == valid` — the isolation is a command-evaluation rule, not a lint rule");
    }
}

