----------------------------------------------
MODULE modelcheck
----------------------------------------------
\* Generated by `spk compile` from spec `model_check` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"not_run", "running", "clean", "counterexample_found", "timed_out"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

Init == vpc = "not_run"

Next ==
  \* begin: not_run -> running (guard: [[model_check.checker_invoked]])
  \/ vpc = "not_run" /\ vpc' = "running"
  \* finish_clean: running -> clean (guard: [[model_check.exhaustive_within_bound]] ∧ `no violation found within the bound`)
  \/ vpc = "running" /\ vpc' = "clean"
  \* finish_violation: running -> counterexample_found (guard: [[model_check.counterexample_is_minimal]] ∧ [[model_check.counterexample_names_violated_invariant]])
  \/ vpc = "running" /\ vpc' = "counterexample_found"
  \* finish_timeout: running -> timed_out (guard: `the stated bound was not reached before the run's time/state budget expired`)
  \/ vpc = "running" /\ vpc' = "timed_out"

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
