//! proptest scaffolding for `model_check` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// The real element types and strategies are `verify`'s domain.
pub mod spec_gen {
    use super::*;

    pub fn compiled_module_with_zero_runs_against_it() -> impl Strategy<Value = GenVal> {
        Just(GenVal("compiled_module_with_zero_runs_against_it".into()))
    }

    pub fn run_report_with_no_stated_bound() -> impl Strategy<Value = GenVal> {
        Just(GenVal("run_report_with_no_stated_bound".into()))
    }

    pub fn model_with() -> impl Strategy<Value = GenVal> {
        Just(GenVal("model_with".into()))
    }

    pub fn model_with_exactly_one_violated_invariant() -> impl Strategy<Value = GenVal> {
        Just(GenVal("model_with_exactly_one_violated_invariant".into()))
    }

    pub fn run_report_from_any_backend() -> impl Strategy<Value = GenVal> {
        Just(GenVal("run_report_from_any_backend".into()))
    }

    pub fn arbitrary_model_with_no_violation_within_bound() -> impl Strategy<Value = GenVal> {
        Just(GenVal("arbitrary_model_with_no_violation_within_bound".into()))
    }

}

proptest! {
    // id: stale_claim_rejected
    // generator: `compiled_module_with_zero_runs_against_it()`
    // predicate: `no_counterexample(file) == undetermined` — never defaults to true
    #[test]
    fn stale_claim_rejected(v0 in spec_gen::compiled_module_with_zero_runs_against_it()) {
        todo_predicate!("`no_counterexample(file) == undetermined` — never defaults to true");
    }
}

proptest! {
    // id: bound_must_be_stated
    // generator: `run_report_with_no_stated_bound()`
    // predicate: `check(report) == invalid`
    #[test]
    fn bound_must_be_stated(v0 in spec_gen::run_report_with_no_stated_bound()) {
        todo_predicate!("`check(report) == invalid`");
    }
}

proptest! {
    // id: shortest_counterexample_reported
    // generator: `model_with(two_violating_traces_of_different_length: true)`
    // predicate: `reported_trace(check(model)) == the_shorter_of_the_two`
    #[test]
    fn shortest_counterexample_reported(v0 in spec_gen::model_with()) {
        todo_predicate!("`reported_trace(check(model)) == the_shorter_of_the_two`");
    }
}

proptest! {
    // id: violated_invariant_named
    // generator: `model_with_exactly_one_violated_invariant()`
    // predicate: `check(model).violated_invariant_id == the_expected_id`
    #[test]
    fn violated_invariant_named(v0 in spec_gen::model_with_exactly_one_violated_invariant()) {
        todo_predicate!("`check(model).violated_invariant_id == the_expected_id`");
    }
}

proptest! {
    // id: backend_named_in_report
    // generator: `run_report_from_any_backend()`
    // predicate: `check(report).backend == a named engine and version`
    #[test]
    fn backend_named_in_report(v0 in spec_gen::run_report_from_any_backend()) {
        todo_predicate!("`check(report).backend == a named engine and version`");
    }
}

proptest! {
    // id: clean_run_satisfies_verify_gate
    // generator: `arbitrary_model_with_no_violation_within_bound()`
    // predicate: `no_counterexample(file) == true`
    #[test]
    fn clean_run_satisfies_verify_gate(v0 in spec_gen::arbitrary_model_with_no_violation_within_bound()) {
        todo_predicate!("`no_counterexample(file) == true`");
    }
}

proptest! {
    // id: stale_result_invalidated_by_edit
    // generator: `(clean_run, model_edited_afterward_with_no_rerun)`
    // predicate: `no_counterexample(file) == false` — until re-run
    #[test]
    fn stale_result_invalidated_by_edit() {
        todo_predicate!("`no_counterexample(file) == false` — until re-run");
    }
}

proptest! {
    // id: clean_model_passes
    // generator: `arbitrary_model_with_no_violation_within_bound()`
    // predicate: `check(model) == clean`
    #[test]
    fn clean_model_passes(v0 in spec_gen::arbitrary_model_with_no_violation_within_bound()) {
        todo_predicate!("`check(model) == clean`");
    }
}

