//! proptest scaffolding for `orchestrate` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// The real element types and strategies are `verify`'s domain.
pub mod spec_gen {
    use super::*;

    pub fn repo_where() -> impl Strategy<Value = GenVal> {
        Just(GenVal("repo_where".into()))
    }

    pub fn run_orchestrator_twice_against_unchanged_repo() -> impl Strategy<Value = GenVal> {
        Just(GenVal("run_orchestrator_twice_against_unchanged_repo".into()))
    }

    pub fn arbitrary_repo_that_independently_passes_lint_compile_model_check_verify() -> impl Strategy<Value = GenVal> {
        Just(GenVal("arbitrary_repo_that_independently_passes_lint_compile_model_check_verify".into()))
    }

}

proptest! {
    // id: upstream_failure_skips_dependents
    // generator: `repo_where(linter.frontmatter: fails)`
    // predicate: `invocation_count(linter.referential_integrity) == 0` — never run against unvalidated input
    #[test]
    fn upstream_failure_skips_dependents(v0 in spec_gen::repo_where()) {
        todo_predicate!("`invocation_count(linter.referential_integrity) == 0` — never run against unvalidated input");
    }
}

proptest! {
    // id: independent_branch_failure_isolated
    // generator: `repo_where(linter.ears_syntax: fails, linter.referential_integrity_branch: passes)`
    // predicate: `report(linter.graph_shape) == passed` — the passing branch's own outcome is unaffected
    #[test]
    fn independent_branch_failure_isolated(v0 in spec_gen::repo_where()) {
        todo_predicate!("`report(linter.graph_shape) == passed` — the passing branch's own outcome is unaffected");
    }
}

proptest! {
    // id: compile_blocked_on_partial_lint
    // generator: `repo_where(five_of_six_checkers_pass, one_still_pending)`
    // predicate: `invocation_count(compile) == 0`
    #[test]
    fn compile_blocked_on_partial_lint(v0 in spec_gen::repo_where()) {
        todo_predicate!("`invocation_count(compile) == 0`");
    }
}

proptest! {
    // id: external_completeness_failure_ignored
    // generator: `repo_where(all_seven_checkers_and_pipeline_pass, declared_checklist: fails)`
    // predicate: `orchestrate reaches succeeded`
    #[test]
    fn external_completeness_failure_ignored(v0 in spec_gen::repo_where()) {
        todo_predicate!("`orchestrate reaches succeeded`");
    }
}

proptest! {
    // id: rerun_idempotent
    // generator: `run_orchestrator_twice_against_unchanged_repo()`
    // predicate: `report(run_1) == report(run_2)`
    #[test]
    fn rerun_idempotent(v0 in spec_gen::run_orchestrator_twice_against_unchanged_repo()) {
        todo_predicate!("`report(run_1) == report(run_2)`");
    }
}

proptest! {
    // id: clean_repo_succeeds
    // generator: `arbitrary_repo_that_independently_passes_lint_compile_model_check_verify()`
    // predicate: `orchestrate reaches succeeded`
    #[test]
    fn clean_repo_succeeds(v0 in spec_gen::arbitrary_repo_that_independently_passes_lint_compile_model_check_verify()) {
        todo_predicate!("`orchestrate reaches succeeded`");
    }
}

proptest! {
    // id: coverage_failure_holds_compile
    // generator: `repo_where(linter.coverage: failed, every_other_checker_and_pipeline_stage: passed)`
    // predicate: `orchestrate halts at compile_stage` — never reaches model_check_stage, and by exactly the coverage checker's verdict, not a looser or stricter one
    #[test]
    fn coverage_failure_holds_compile(v0 in spec_gen::repo_where()) {
        todo_predicate!("`orchestrate halts at compile_stage` — never reaches model_check_stage, and by exactly the coverage checker's verdict, not a looser or stricter one");
    }
}

