//! proptest scaffolding for `packs` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// The real element types and strategies are `verify`'s domain.
pub mod spec_gen {
    use super::*;

    pub fn pack_file_parsed_then_manifest_read() -> impl Strategy<Value = GenVal> {
        Just(GenVal("pack_file_parsed_then_manifest_read".into()))
    }

    pub fn corpus_with_n_profile_files() -> impl Strategy<Value = GenVal> {
        Just(GenVal("corpus_with_n_profile_files".into()))
    }

    pub fn lint_subdirectory_with_pack_at_workspace_root() -> impl Strategy<Value = GenVal> {
        Just(GenVal("lint_subdirectory_with_pack_at_workspace_root".into()))
    }

    pub fn corpus_linted_before_and_after_mechanism() -> impl Strategy<Value = GenVal> {
        Just(GenVal("corpus_linted_before_and_after_mechanism".into()))
    }

    pub fn two_packs_declare_identical_vocabulary_and_a_file_uses_it() -> impl Strategy<Value = GenVal> {
        Just(GenVal("two_packs_declare_identical_vocabulary_and_a_file_uses_it".into()))
    }

    pub fn corpus_using_vocabulary_without_pack() -> impl Strategy<Value = GenVal> {
        Just(GenVal("corpus_using_vocabulary_without_pack".into()))
    }

    pub fn file_with_uses_edge_to_profile_id() -> impl Strategy<Value = GenVal> {
        Just(GenVal("file_with_uses_edge_to_profile_id".into()))
    }

    pub fn pack_file_linted_alone() -> impl Strategy<Value = GenVal> {
        Just(GenVal("pack_file_linted_alone".into()))
    }

    pub fn pack_pinned_to_older_revision() -> impl Strategy<Value = GenVal> {
        Just(GenVal("pack_pinned_to_older_revision".into()))
    }

    pub fn pack_enabled_without_instances() -> impl Strategy<Value = GenVal> {
        Just(GenVal("pack_enabled_without_instances".into()))
    }

    pub fn pack_removing_previously_declared_kind() -> impl Strategy<Value = GenVal> {
        Just(GenVal("pack_removing_previously_declared_kind".into()))
    }

    pub fn pack_parsed_as_standard_spec() -> impl Strategy<Value = GenVal> {
        Just(GenVal("pack_parsed_as_standard_spec".into()))
    }

    pub fn two_packs_claim_same_mechanism() -> impl Strategy<Value = GenVal> {
        Just(GenVal("two_packs_claim_same_mechanism".into()))
    }

    pub fn guide_sets_compared_across_pack_enable() -> impl Strategy<Value = GenVal> {
        Just(GenVal("guide_sets_compared_across_pack_enable".into()))
    }

    pub fn pack_model_section_parsed() -> impl Strategy<Value = GenVal> {
        Just(GenVal("pack_model_section_parsed".into()))
    }

}

proptest! {
    // id: manifest_round_trips
    // generator: `pack_file_parsed_then_manifest_read()`
    // predicate: `declared entries equal parsed manifest rows — no drift, no prose leakage`
    #[test]
    fn manifest_round_trips(v0 in spec_gen::pack_file_parsed_then_manifest_read()) {
        todo_predicate!("`declared entries equal parsed manifest rows — no drift, no prose leakage`");
    }
}

proptest! {
    // id: discovery_finds_all_packs
    // generator: `corpus_with_n_profile_files()`
    // predicate: `scan reports exactly n packs, order-independent`
    #[test]
    fn discovery_finds_all_packs(v0 in spec_gen::corpus_with_n_profile_files()) {
        todo_predicate!("`scan reports exactly n packs, order-independent`");
    }
}

proptest! {
    // id: subdir_lint_discovers_workspace_packs
    // generator: `lint_subdirectory_with_pack_at_workspace_root()`
    // predicate: `pack discovered, its vocabulary checks run, zero orphan findings`
    #[test]
    fn subdir_lint_discovers_workspace_packs(v0 in spec_gen::lint_subdirectory_with_pack_at_workspace_root()) {
        todo_predicate!("`pack discovered, its vocabulary checks run, zero orphan findings`");
    }
}

proptest! {
    // id: no_pack_no_change
    // generator: `corpus_linted_before_and_after_mechanism()`
    // predicate: `lint findings byte-identical for a corpus using no pack vocabulary`
    #[test]
    fn no_pack_no_change(v0 in spec_gen::corpus_linted_before_and_after_mechanism()) {
        todo_predicate!("`lint findings byte-identical for a corpus using no pack vocabulary`");
    }
}

proptest! {
    // id: overlapping_vocabulary_activates_both
    // generator: `two_packs_declare_identical_vocabulary_and_a_file_uses_it()`
    // predicate: `both packs' checkers run; findings attributed per pack`
    #[test]
    fn overlapping_vocabulary_activates_both(v0 in spec_gen::two_packs_declare_identical_vocabulary_and_a_file_uses_it()) {
        todo_predicate!("`both packs' checkers run; findings attributed per pack`");
    }
}

proptest! {
    // id: orphan_finding_names_pack
    // generator: `corpus_using_vocabulary_without_pack()`
    // predicate: `failure finding names the candidate pack and both remediations, exit non-zero`
    #[test]
    fn orphan_finding_names_pack(v0 in spec_gen::corpus_using_vocabulary_without_pack()) {
        todo_predicate!("`failure finding names the candidate pack and both remediations, exit non-zero`");
    }
}

proptest! {
    // id: uses_edge_typing
    // generator: `file_with_uses_edge_to_profile_id()`
    // predicate: `graph edge typed uses resolves to the profile id; wrong-kind targets violate typing`
    #[test]
    fn uses_edge_typing(v0 in spec_gen::file_with_uses_edge_to_profile_id()) {
        todo_predicate!("`graph edge typed uses resolves to the profile id; wrong-kind targets violate typing`");
    }
}

proptest! {
    // id: pack_self_activation_absent
    // generator: `pack_file_linted_alone()`
    // predicate: `its checkers report an empty checked-set; no orphan findings from the pack's own manifest rows`
    #[test]
    fn pack_self_activation_absent(v0 in spec_gen::pack_file_linted_alone()) {
        todo_predicate!("`its checkers report an empty checked-set; no orphan findings from the pack's own manifest rows`");
    }
}

proptest! {
    // id: skew_is_warning_not_failure
    // generator: `pack_pinned_to_older_revision()`
    // predicate: `exit 0 with warning-channel advisory naming the pack's base pin and the corpus revision`
    #[test]
    fn skew_is_warning_not_failure(v0 in spec_gen::pack_pinned_to_older_revision()) {
        todo_predicate!("`exit 0 with warning-channel advisory naming the pack's base pin and the corpus revision`");
    }
}

proptest! {
    // id: empty_vocabulary_honest
    // generator: `pack_enabled_without_instances()`
    // predicate: `checker reports empty checked-set; no fabricated findings`
    #[test]
    fn empty_vocabulary_honest(v0 in spec_gen::pack_enabled_without_instances()) {
        todo_predicate!("`checker reports empty checked-set; no fabricated findings`");
    }
}

proptest! {
    // id: narrowing_rejected
    // generator: `pack_removing_previously_declared_kind()`
    // predicate: `pack_shape fails naming the removed entry and the append-only law`
    #[test]
    fn narrowing_rejected(v0 in spec_gen::pack_removing_previously_declared_kind()) {
        todo_predicate!("`pack_shape fails naming the removed entry and the append-only law`");
    }
}

proptest! {
    // id: profile_file_is_four_layer
    // generator: `pack_parsed_as_standard_spec()`
    // predicate: `all four layers parse from the pack file alone — no sidecar artifact needed`
    #[test]
    fn profile_file_is_four_layer(v0 in spec_gen::pack_parsed_as_standard_spec()) {
        todo_predicate!("`all four layers parse from the pack file alone — no sidecar artifact needed`");
    }
}

proptest! {
    // id: pack_vocabulary_qualified
    // generator: `two_packs_claim_same_mechanism()`
    // predicate: `both packs' declared vocabulary resolves without cross-pack collision`
    #[test]
    fn pack_vocabulary_qualified(v0 in spec_gen::two_packs_claim_same_mechanism()) {
        todo_predicate!("`both packs' declared vocabulary resolves without cross-pack collision`");
    }
}

proptest! {
    // id: base_sets_unchanged_by_packs
    // generator: `guide_sets_compared_across_pack_enable()`
    // predicate: `INTENT_KINDS and Reference Typing sets identical with and without packs discovered`
    #[test]
    fn base_sets_unchanged_by_packs(v0 in spec_gen::guide_sets_compared_across_pack_enable()) {
        todo_predicate!("`INTENT_KINDS and Reference Typing sets identical with and without packs discovered`");
    }
}

proptest! {
    // id: lifecycle_states_parsed
    // generator: `pack_model_section_parsed()`
    // predicate: `each lifecycle state yields exactly its declared checking behavior`
    #[test]
    fn lifecycle_states_parsed(v0 in spec_gen::pack_model_section_parsed()) {
        todo_predicate!("`each lifecycle state yields exactly its declared checking behavior`");
    }
}

