---- MODULE quantfinance ----
\* Generated by `spk compile` from spec `quant.finance` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"draft", "published", "deprecated"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "draft"

Next ==
  \* publish: draft -> published (guard: `[[quant.finance.vocab_declared]] — pack_shape reports zero findings over the declared vocabulary`)
  \/ vpc = "draft" /\ vpc' = "published"
  \* deprecate: published -> deprecated (guard: `[[quant.finance.vocab_declared]] — maintainer marks the pack deprecated; findings name the deprecation, vocabulary still checks`)
  \/ vpc = "published" /\ vpc' = "deprecated"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
