//! proptest scaffolding for `quant.finance` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// Each yields a String (the generator's name; executable
/// fragments bind these directly — Revision 15).
pub mod spec_gen {
    use super::*;

    pub fn pack_file_linted_in_each_state() -> impl Strategy<Value = String> {
        Just("pack_file_linted_in_each_state".into())
    }

}

proptest! {
    // id: p_pack_shape
    // generator: `pack_file_linted_in_each_state()`
    // predicate: `pack_shape reports zero findings`
    #[test]
    fn p_pack_shape(v0 in spec_gen::pack_file_linted_in_each_state()) {
        todo_predicate!("`pack_shape reports zero findings`");
    }
}

