//! proptest scaffolding for `refactor` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// The real element types and strategies are `verify`'s domain.
pub mod spec_gen {
    use super::*;

    pub fn node_with_precomputed_blast_radius_in_graph() -> impl Strategy<Value = GenVal> {
        Just(GenVal("node_with_precomputed_blast_radius_in_graph".into()))
    }

    pub fn node_referenced_by_dependents_in_three_disjoint_top_level_namespaces() -> impl Strategy<Value = GenVal> {
        Just(GenVal("node_referenced_by_dependents_in_three_disjoint_top_level_namespaces".into()))
    }

    pub fn node_referenced_only_by_dependents_within_its_own_namespace_subtree() -> impl Strategy<Value = GenVal> {
        Just(GenVal("node_referenced_only_by_dependents_within_its_own_namespace_subtree".into()))
    }

    pub fn changeset_touching_one_of_five_constraints_owned_by_a_node_with_fan_in() -> impl Strategy<Value = GenVal> {
        Just(GenVal("changeset_touching_one_of_five_constraints_owned_by_a_node_with_fan_in".into()))
    }

    pub fn same_node_same_changeset_under_two_repo_configs_with_different_high_fan_in_values() -> impl Strategy<Value = GenVal> {
        Just(GenVal("same_node_same_changeset_under_two_repo_configs_with_different_high_fan_in_values".into()))
    }

}

proptest! {
    // id: fan_in_never_rewalked
    // generator: `node_with_precomputed_blast_radius_in_graph()`
    // predicate: `advisor_source_calls(markdown_walker) == 0` — every count comes from `graph`'s artifact
    #[test]
    fn fan_in_never_rewalked(v0 in spec_gen::node_with_precomputed_blast_radius_in_graph()) {
        todo_predicate!("`advisor_source_calls(markdown_walker) == 0` — every count comes from `graph`'s artifact");
    }
}

proptest! {
    // id: unrelated_fan_in_flagged
    // generator: `node_referenced_by_dependents_in_three_disjoint_top_level_namespaces()`
    // predicate: `check(node) == found`
    #[test]
    fn unrelated_fan_in_flagged(v0 in spec_gen::node_referenced_by_dependents_in_three_disjoint_top_level_namespaces()) {
        todo_predicate!("`check(node) == found`");
    }
}

proptest! {
    // id: related_fan_in_not_flagged
    // generator: `node_referenced_only_by_dependents_within_its_own_namespace_subtree()`
    // predicate: `check(node) == clean`
    #[test]
    fn related_fan_in_not_flagged(v0 in spec_gen::node_referenced_only_by_dependents_within_its_own_namespace_subtree()) {
        todo_predicate!("`check(node) == clean`");
    }
}

proptest! {
    // id: narrow_diff_flagged_low_fan_in
    // generator: `changeset_touching_one_of_five_constraints_owned_by_a_node_with_fan_in(1)`
    // predicate: `check(node) == found` — flagged even though fan-in alone wouldn't trigger it
    #[test]
    fn narrow_diff_flagged_low_fan_in(v0 in spec_gen::changeset_touching_one_of_five_constraints_owned_by_a_node_with_fan_in()) {
        todo_predicate!("`check(node) == found` — flagged even though fan-in alone wouldn't trigger it");
    }
}

proptest! {
    // id: emitted_finding_shape
    // generator: `found state reached for node N with dependent_count 4, 2 unrelated`
    // predicate: `emits(found) == {node_id: N, dependent_count: 4, unrelated_namespace_count: 2, suggested_split: true}`
    #[test]
    fn emitted_finding_shape() {
        todo_predicate!("`emits(found) == {node_id: N, dependent_count: 4, unrelated_namespace_count: 2, suggested_split: true}`");
    }
}

proptest! {
    // id: threshold_read_from_config
    // generator: `same_node_same_changeset_under_two_repo_configs_with_different_high_fan_in_values()`
    // predicate: `flagged(config_A) != flagged(config_B)` — the decision follows the repo's configured threshold, never a constant embedded in this file
    #[test]
    fn threshold_read_from_config(v0 in spec_gen::same_node_same_changeset_under_two_repo_configs_with_different_high_fan_in_values()) {
        todo_predicate!("`flagged(config_A) != flagged(config_B)` — the decision follows the repo's configured threshold, never a constant embedded in this file");
    }
}

