--------------------------------------------
MODULE refactor
--------------------------------------------
\* Generated by `spk compile` from spec `refactor` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"idle", "analyzing", "clean", "found"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

Init == vpc = "idle"

Next ==
  \* analyze: idle -> analyzing (guard: `[[graph]] has reached queryable` — see `graph.md`'s own lifecycle)
  \/ vpc = "idle" /\ vpc' = "analyzing"
  \* flag: analyzing -> found (guard: [[refactor.unrelated_fan_in_defined]] ∨ [[refactor.narrow_diff_heuristic]])
  \/ vpc = "analyzing" /\ vpc' = "found"
  \* clear: analyzing -> clean (guard: `¬flag.guard`)
  \/ vpc = "analyzing" /\ vpc' = "clean"

\* One entry per state with an `emits` field — domain is exactly
\* the emitting states (spec emits text quoted verbatim).
Output ==
"found" :> "advisory_finding_emitted"

============================================================================
