---- MODULE rename ----
\* Generated by `spk compile` from spec `rename` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"requested", "checked", "applying", "applied", "verifying", "passed", "validate_failed", "apply_failed", "check_failed"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "requested"

Next ==
  \* validate: requested -> checked (guard: [[rename.new_id_available]] ∧ [[rename.new_id_matches_filename]])
  \/ vpc = "requested" /\ vpc' = "checked"
  \* validate_fail: requested -> validate_failed (guard: `¬([[rename.new_id_available]] ∧ [[rename.new_id_matches_filename]])`)
  \/ vpc = "requested" /\ vpc' = "validate_failed"
  \* apply: checked -> applying (guard: [[rename.atomic_operation]])
  \/ vpc = "checked" /\ vpc' = "applying"
  \* apply_ok: applying -> applied (guard: [[rename.old_id_fully_replaced]] ∧ [[rename.kind_unchanged]] ∧ [[rename.prose_untouched_by_rename]])
  \/ vpc = "applying" /\ vpc' = "applied"
  \* apply_fail: applying -> apply_failed (guard: `¬([[rename.old_id_fully_replaced]] ∧ [[rename.kind_unchanged]] ∧ [[rename.prose_untouched_by_rename]])` — atomic_operation requires this path to roll back to the pre-rename repo, not to leave a partial edit)
  \/ vpc = "applying" /\ vpc' = "apply_failed"
  \* verify: applied -> verifying (guard: `linter.referential_integrity and linter.graph_shape are re-run against the renamed repo`)
  \/ vpc = "applied" /\ vpc' = "verifying"
  \* accept: verifying -> passed (guard: [[linter.referential_integrity.ref_resolves]] ∧ [[linter.graph_shape.acyclic]])
  \/ vpc = "verifying" /\ vpc' = "passed"
  \* reject: verifying -> check_failed (guard: `¬([[linter.referential_integrity.ref_resolves]] ∧ [[linter.graph_shape.acyclic]])`)
  \/ vpc = "verifying" /\ vpc' = "check_failed"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* One entry per state with an `emits` field — domain is exactly
\* the emitting states; each value is the effect-Constraint's expr.
Output ==
"apply_failed" :> "`rename.apply_failure(detail)`" @@
"check_failed" :> "`rename.post_check_failure(detail)`" @@
"validate_failed" :> "`rename.validation_failure(new_id, reason)`"

============================================================================
