//! proptest scaffolding for `rename` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// Each yields a String (the generator's name; executable
/// fragments bind these directly — Revision 15).
pub mod spec_gen {
    use super::*;

    pub fn arbitrary_spec_repo() -> impl Strategy<Value = String> {
        Just("arbitrary_spec_repo".into())
    }

    pub fn arbitrary_id_rename() -> impl Strategy<Value = String> {
        Just("arbitrary_id_rename".into())
    }

    pub fn rename_of_a_files_own_intent_id_without_a_matching_filename_change() -> impl Strategy<Value = String> {
        Just("rename_of_a_files_own_intent_id_without_a_matching_filename_change".into())
    }

    pub fn apply_interrupted_after_definition_row_updated_but_before_all_refs_rewritten() -> impl Strategy<Value = String> {
        Just("apply_interrupted_after_definition_row_updated_but_before_all_refs_rewritten".into())
    }

    pub fn _occurrence() -> impl Strategy<Value = String> {
        Just("_occurrence".into())
    }

    pub fn row_whose_rationale_prose_contains_the_old_id_as_a_word() -> impl Strategy<Value = String> {
        Just("row_whose_rationale_prose_contains_the_old_id_as_a_word".into())
    }

    pub fn well_formed_repo() -> impl Strategy<Value = String> {
        Just("well_formed_repo".into())
    }

    pub fn id_not_used_elsewhere() -> impl Strategy<Value = String> {
        Just("id_not_used_elsewhere".into())
    }

    pub fn rename_of_a_constraint_row_to_a_new_id() -> impl Strategy<Value = String> {
        Just("rename_of_a_constraint_row_to_a_new_id".into())
    }

    pub fn validation_failure_raised() -> impl Strategy<Value = String> {
        Just("validation_failure_raised".into())
    }

    pub fn apply_failure_raised() -> impl Strategy<Value = String> {
        Just("apply_failure_raised".into())
    }

    pub fn post_check_failure_raised() -> impl Strategy<Value = String> {
        Just("post_check_failure_raised".into())
    }

}

proptest! {
    // id: rename_naturality
    // case: identity
    // generator: `arbitrary_spec_repo(), arbitrary_id_rename()`
    // predicate: **identity:** `rename(I, a, a) == I`  **associativity:** `rename(rename(I,a,b), b,c) == rename(I,a,c)`  **naturality:** `compile(rename(I)) == rename(compile(I))`
    #[test]
    fn rename_naturality_identity(v0 in spec_gen::arbitrary_spec_repo(), v1 in spec_gen::arbitrary_id_rename()) {
        todo_predicate!("**identity:** `rename(I, a, a) == I`  **associativity:** `rename(rename(I,a,b), b,c) == rename(I,a,c)`  **naturality:** `compile(rename(I)) == rename(compile(I))`");
    }
    // id: rename_naturality
    // case: associativity
    // generator: `arbitrary_spec_repo(), arbitrary_id_rename()`
    // predicate: **identity:** `rename(I, a, a) == I`  **associativity:** `rename(rename(I,a,b), b,c) == rename(I,a,c)`  **naturality:** `compile(rename(I)) == rename(compile(I))`
    #[test]
    fn rename_naturality_associativity(v0 in spec_gen::arbitrary_spec_repo(), v1 in spec_gen::arbitrary_id_rename()) {
        todo_predicate!("**identity:** `rename(I, a, a) == I`  **associativity:** `rename(rename(I,a,b), b,c) == rename(I,a,c)`  **naturality:** `compile(rename(I)) == rename(compile(I))`");
    }
    // id: rename_naturality
    // case: naturality
    // generator: `arbitrary_spec_repo(), arbitrary_id_rename()`
    // predicate: **identity:** `rename(I, a, a) == I`  **associativity:** `rename(rename(I,a,b), b,c) == rename(I,a,c)`  **naturality:** `compile(rename(I)) == rename(compile(I))`
    #[test]
    fn rename_naturality_naturality(v0 in spec_gen::arbitrary_spec_repo(), v1 in spec_gen::arbitrary_id_rename()) {
        todo_predicate!("**identity:** `rename(I, a, a) == I`  **associativity:** `rename(rename(I,a,b), b,c) == rename(I,a,c)`  **naturality:** `compile(rename(I)) == rename(compile(I))`");
    }
}

// id: collision_rejected
// generator: `(repo_with_id: "x", new_id: "x_taken_by_other_row")`
// predicate: `check(request) == failed`
#[test]
fn collision_rejected() {
        todo_predicate!("`check(request) == failed`");
}

proptest! {
    // id: filename_mismatch_rejected
    // generator: `rename_of_a_files_own_intent_id_without_a_matching_filename_change()`
    // predicate: `check(request) == failed`
    #[test]
    fn filename_mismatch_rejected(v0 in spec_gen::rename_of_a_files_own_intent_id_without_a_matching_filename_change()) {
        todo_predicate!("`check(request) == failed`");
    }
    // id: partial_failure_rolls_back
    // generator: `apply_interrupted_after_definition_row_updated_but_before_all_refs_rewritten()`
    // predicate: `post_state(repo) == pre_state(repo)`
    #[test]
    fn partial_failure_rolls_back(v0 in spec_gen::apply_interrupted_after_definition_row_updated_but_before_all_refs_rewritten()) {
        todo_predicate!("`post_state(repo) == pre_state(repo)`");
    }
    // id: stray_ref_caught_by_verify
    // generator: `rename_that_misses_one_[[old_id]]_occurrence()`
    // predicate: `check(request) == failed` — caught at `verify`, not silently accepted
    #[test]
    fn stray_ref_caught_by_verify(v0 in spec_gen::_occurrence()) {
        todo_predicate!("`check(request) == failed` — caught at `verify`, not silently accepted");
    }
    // id: prose_mention_left_alone
    // generator: `row_whose_rationale_prose_contains_the_old_id_as_a_word()`
    // predicate: `rationale_text(post_rename_row) == rationale_text(pre_rename_row)`
    #[test]
    fn prose_mention_left_alone(v0 in spec_gen::row_whose_rationale_prose_contains_the_old_id_as_a_word()) {
        todo_predicate!("`rationale_text(post_rename_row) == rationale_text(pre_rename_row)`");
    }
    // id: clean_rename_passes
    // generator: `well_formed_repo(), id_not_used_elsewhere()`
    // predicate: `check(request) == passed`
    #[test]
    fn clean_rename_passes(v0 in spec_gen::well_formed_repo(), v1 in spec_gen::id_not_used_elsewhere()) {
        todo_predicate!("`check(request) == passed`");
    }
    // id: kind_preserved_by_rename
    // generator: `rename_of_a_constraint_row_to_a_new_id()`
    // predicate: `assigned_kind(post_rename_row) == assigned_kind(pre_rename_row)` — both the five-object kind and, where present, the row's own kind column survive the rewrite
    #[test]
    fn kind_preserved_by_rename(v0 in spec_gen::rename_of_a_constraint_row_to_a_new_id()) {
        todo_predicate!("`assigned_kind(post_rename_row) == assigned_kind(pre_rename_row)` — both the five-object kind and, where present, the row's own kind column survive the rewrite");
    }
    // id: validation_failure_label_asserted
    // generator: `validation_failure_raised()`
    // predicate: `error_label == "rename.validation_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn validation_failure_label_asserted(v0 in spec_gen::validation_failure_raised()) {
        todo_predicate!("`error_label == \"rename.validation_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
    // id: apply_failure_label_asserted
    // generator: `apply_failure_raised()`
    // predicate: `error_label == "rename.apply_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn apply_failure_label_asserted(v0 in spec_gen::apply_failure_raised()) {
        todo_predicate!("`error_label == \"rename.apply_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
    // id: post_check_failure_label_asserted
    // generator: `post_check_failure_raised()`
    // predicate: `error_label == "rename.post_check_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn post_check_failure_label_asserted(v0 in spec_gen::post_check_failure_raised()) {
        todo_predicate!("`error_label == \"rename.post_check_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
}

