------------------------------------------
MODULE rename
------------------------------------------
\* Generated by `spk compile` from spec `rename` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"requested", "checked", "applying", "applied", "verifying", "passed", "failed"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

Init == vpc = "requested"

Next ==
  \* validate: requested -> checked (guard: [[rename.new_id_available]] ∧ [[rename.new_id_matches_filename]])
  \/ vpc = "requested" /\ vpc' = "checked"
  \* validate_fail: requested -> failed (guard: `¬validate.guard`)
  \/ vpc = "requested" /\ vpc' = "failed"
  \* apply: checked -> applying (guard: [[rename.atomic_operation]])
  \/ vpc = "checked" /\ vpc' = "applying"
  \* apply_ok: applying -> applied (guard: [[rename.old_id_fully_replaced]] ∧ [[rename.kind_unchanged]] ∧ [[rename.prose_untouched_by_rename]])
  \/ vpc = "applying" /\ vpc' = "applied"
  \* apply_fail: applying -> failed (guard: `¬apply_ok.guard` — atomic_operation requires this path to roll back to the pre-rename repo, not to leave a partial edit)
  \/ vpc = "applying" /\ vpc' = "failed"
  \* verify: applied -> verifying (guard: `linter.referential_integrity and linter.graph_shape are re-run against the renamed repo`)
  \/ vpc = "applied" /\ vpc' = "verifying"
  \* accept: verifying -> passed (guard: [[linter.referential_integrity.ref_resolves]] ∧ [[linter.graph_shape.acyclic]])
  \/ vpc = "verifying" /\ vpc' = "passed"
  \* reject: verifying -> failed (guard: `¬accept.guard`)
  \/ vpc = "verifying" /\ vpc' = "failed"

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
