//! proptest scaffolding for `specodelic` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// Each yields a String (the generator's name; executable
/// fragments bind these directly — Revision 15).
pub mod spec_gen {
    use super::*;

    pub fn arbitrary_spec_file() -> impl Strategy<Value = String> {
        Just("arbitrary_spec_file".into())
    }

    pub fn arbitrary_spec_repo() -> impl Strategy<Value = String> {
        Just("arbitrary_spec_repo".into())
    }

    pub fn arbitrary_id_rename() -> impl Strategy<Value = String> {
        Just("arbitrary_id_rename".into())
    }

    pub fn guard_field_pointing_at_a_property_row() -> impl Strategy<Value = String> {
        Just("guard_field_pointing_at_a_property_row".into())
    }

    pub fn spec_repo_with() -> impl Strategy<Value = String> {
        Just("spec_repo_with".into())
    }

    pub fn spec_file_with() -> impl Strategy<Value = String> {
        Just("spec_file_with".into())
    }

    pub fn guard_field_pointing_at_an_advisory_constraint() -> impl Strategy<Value = String> {
        Just("guard_field_pointing_at_an_advisory_constraint".into())
    }

    pub fn transition_guard_citing_a_declared_state() -> impl Strategy<Value = String> {
        Just("transition_guard_citing_a_declared_state".into())
    }

    pub fn constraint_row_with() -> impl Strategy<Value = String> {
        Just("constraint_row_with".into())
    }

    pub fn schema_with() -> impl Strategy<Value = String> {
        Just("schema_with".into())
    }

    pub fn emits_field_pointing_at_an_invariant_constraint() -> impl Strategy<Value = String> {
        Just("emits_field_pointing_at_an_invariant_constraint".into())
    }

    pub fn satisfies_field_pointing_at_an_invariant_constraint() -> impl Strategy<Value = String> {
        Just("satisfies_field_pointing_at_an_invariant_constraint".into())
    }

    pub fn frontmatter_missing() -> impl Strategy<Value = String> {
        Just("frontmatter_missing".into())
    }

    pub fn transition_row_with() -> impl Strategy<Value = String> {
        Just("transition_row_with".into())
    }

    pub fn statement_outside_the_five_ears_patterns() -> impl Strategy<Value = String> {
        Just("statement_outside_the_five_ears_patterns".into())
    }

    pub fn row_id_joined_to_two_intents_via_and() -> impl Strategy<Value = String> {
        Just("row_id_joined_to_two_intents_via_and".into())
    }

    pub fn law_property_missing() -> impl Strategy<Value = String> {
        Just("law_property_missing".into())
    }

    pub fn state_appearing_in_no_transition() -> impl Strategy<Value = String> {
        Just("state_appearing_in_no_transition".into())
    }

    pub fn spec_file_without_states_or_transitions() -> impl Strategy<Value = String> {
        Just("spec_file_without_states_or_transitions".into())
    }

    pub fn model_with_a_violated_invariant() -> impl Strategy<Value = String> {
        Just("model_with_a_violated_invariant".into())
    }

    pub fn compiled_proptest_block_that_fails() -> impl Strategy<Value = String> {
        Just("compiled_proptest_block_that_fails".into())
    }

    pub fn two_specs_identical_except_rationale_prose() -> impl Strategy<Value = String> {
        Just("two_specs_identical_except_rationale_prose".into())
    }

    pub fn property_row_with() -> impl Strategy<Value = String> {
        Just("property_row_with".into())
    }

}

proptest! {
    // id: referential_integrity
    // generator: `arbitrary_spec_file()`
    // predicate: `∀ ref ∈ file: lookup(ref) ≠ None`
    #[test]
    fn referential_integrity(v0 in spec_gen::arbitrary_spec_file()) {
        todo_predicate!("`∀ ref ∈ file: lookup(ref) ≠ None`");
    }
}

proptest! {
    // id: acyclicity
    // generator: `arbitrary_spec_repo()`
    // predicate: `is_dag(traces_to_graph(repo))`
    #[test]
    fn acyclicity(v0 in spec_gen::arbitrary_spec_repo()) {
        todo_predicate!("`is_dag(traces_to_graph(repo))`");
    }
}

proptest! {
    // id: rename_naturality
    // case: identity
    // generator: `arbitrary_spec_repo(), arbitrary_id_rename()`
    // predicate: **identity:** `rename(I, a, a) == I`  **associativity:** `rename(rename(I,a,b), b,c) == rename(I,a,c)`  **naturality:** `compile(rename(I)) == rename(compile(I))`
    #[test]
    fn rename_naturality_identity(v0 in spec_gen::arbitrary_spec_repo(), v1 in spec_gen::arbitrary_id_rename()) {
        todo_predicate!("**identity:** `rename(I, a, a) == I`  **associativity:** `rename(rename(I,a,b), b,c) == rename(I,a,c)`  **naturality:** `compile(rename(I)) == rename(compile(I))`");
    }
}

proptest! {
    // id: rename_naturality
    // case: associativity
    // generator: `arbitrary_spec_repo(), arbitrary_id_rename()`
    // predicate: **identity:** `rename(I, a, a) == I`  **associativity:** `rename(rename(I,a,b), b,c) == rename(I,a,c)`  **naturality:** `compile(rename(I)) == rename(compile(I))`
    #[test]
    fn rename_naturality_associativity(v0 in spec_gen::arbitrary_spec_repo(), v1 in spec_gen::arbitrary_id_rename()) {
        todo_predicate!("**identity:** `rename(I, a, a) == I`  **associativity:** `rename(rename(I,a,b), b,c) == rename(I,a,c)`  **naturality:** `compile(rename(I)) == rename(compile(I))`");
    }
}

proptest! {
    // id: rename_naturality
    // case: naturality
    // generator: `arbitrary_spec_repo(), arbitrary_id_rename()`
    // predicate: **identity:** `rename(I, a, a) == I`  **associativity:** `rename(rename(I,a,b), b,c) == rename(I,a,c)`  **naturality:** `compile(rename(I)) == rename(compile(I))`
    #[test]
    fn rename_naturality_naturality(v0 in spec_gen::arbitrary_spec_repo(), v1 in spec_gen::arbitrary_id_rename()) {
        todo_predicate!("**identity:** `rename(I, a, a) == I`  **associativity:** `rename(rename(I,a,b), b,c) == rename(I,a,c)`  **naturality:** `compile(rename(I)) == rename(compile(I))`");
    }
}

proptest! {
    // id: filename_convention
    // generator: `(id, mismatched_filename)` pairs
    // predicate: `check(id, filename) == failed`
    #[test]
    fn filename_convention() {
        todo_predicate!("`check(id, filename) == failed`");
    }
}

proptest! {
    // id: typing_enforced
    // generator: `guard_field_pointing_at_a_property_row()`
    // predicate: `check(file) == failed`
    #[test]
    fn typing_enforced(v0 in spec_gen::guard_field_pointing_at_a_property_row()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: own_intent_reachable
    // generator: `spec_repo_with(disconnected_constraint_cluster: true)`
    // predicate: `check(repo) == failed`
    #[test]
    fn own_intent_reachable(v0 in spec_gen::spec_repo_with()) {
        todo_predicate!("`check(repo) == failed`");
    }
}

proptest! {
    // id: model_well_formed
    // generator: `spec_file_with(transition.to_not_in_states: true)`
    // predicate: `check(file) == failed`
    #[test]
    fn model_well_formed(v0 in spec_gen::spec_file_with()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: advisory_cannot_gate
    // generator: `guard_field_pointing_at_an_advisory_constraint()`
    // predicate: `check(file) == failed`
    #[test]
    fn advisory_cannot_gate(v0 in spec_gen::guard_field_pointing_at_an_advisory_constraint()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: state_guard_citation_accepted
    // generator: `transition_guard_citing_a_declared_state()`
    // predicate: `check(file) == passed` — the "has reached state X" guard pattern (Revision 12); a State target gates nothing, it records progress — but it is a legal typed citation
    #[test]
    fn state_guard_citation_accepted(v0 in spec_gen::transition_guard_citing_a_declared_state()) {
        todo_predicate!("`check(file) == passed` — the \"has reached state X\" guard pattern (Revision 12); a State target gates nothing, it records progress — but it is a legal typed citation");
    }
}

proptest! {
    // id: supersedes_cross_kind_rejected
    // generator: `constraint_row_with(supersedes: a_property_row_id)`
    // predicate: `check(file) == failed`
    #[test]
    fn supersedes_cross_kind_rejected(v0 in spec_gen::constraint_row_with()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: constraint_derives_from_rejected
    // generator: `constraint_row_with(derives_from: a_constraint_row_id)`
    // predicate: `check(file) == failed` — the Appears-on column is normative, not descriptive: `derives_from` appears on Property rows only (decided of record 2026-10-01, `specodelic-huf`; a constraint is derived FROM by properties, it does not derive), and `ref_kind_compatible` reads the column source-side the same way it already reads `supersedes`' same-kind rule
    #[test]
    fn constraint_derives_from_rejected(v0 in spec_gen::constraint_row_with()) {
        todo_predicate!("`check(file) == failed` — the Appears-on column is normative, not descriptive: `derives_from` appears on Property rows only (decided of record 2026-10-01, `specodelic-huf`; a constraint is derived FROM by properties, it does not derive), and `ref_kind_compatible` reads the column source-side the same way it already reads `supersedes`' same-kind rule");
    }
}

proptest! {
    // id: supersedes_cycle_rejected
    // generator: `spec_repo_with(supersedes_cycle: length ≥ 2)`
    // predicate: `check(repo) == failed`
    #[test]
    fn supersedes_cycle_rejected(v0 in spec_gen::spec_repo_with()) {
        todo_predicate!("`check(repo) == failed`");
    }
}

proptest! {
    // id: no_stored_superseded_flag
    // generator: `schema_with(explicit is_superseded: bool column)`
    // predicate: `check(schema) == rejected` — supersession status is derived (`superseded(x) ⟺ ∃ y. y.supersedes ∋ x`), never stored
    #[test]
    fn no_stored_superseded_flag(v0 in spec_gen::schema_with()) {
        todo_predicate!("`check(schema) == rejected` — supersession status is derived (`superseded(x) ⟺ ∃ y. y.supersedes ∋ x`), never stored");
    }
}

proptest! {
    // id: emits_cannot_target_non_effect
    // generator: `emits_field_pointing_at_an_invariant_constraint()`
    // predicate: `check(file) == failed` — same shape as `advisory_cannot_gate`, mirrored onto the other direction of the kind-split
    #[test]
    fn emits_cannot_target_non_effect(v0 in spec_gen::emits_field_pointing_at_an_invariant_constraint()) {
        todo_predicate!("`check(file) == failed` — same shape as `advisory_cannot_gate`, mirrored onto the other direction of the kind-split");
    }
}

proptest! {
    // id: satisfies_wrong_kind_rejected
    // generator: `satisfies_field_pointing_at_an_invariant_constraint()`
    // predicate: `check(file) == failed` — same shape as `advisory_cannot_gate` and `emits_cannot_target_non_effect`, mirrored onto the third kind-typed reference field
    #[test]
    fn satisfies_wrong_kind_rejected(v0 in spec_gen::satisfies_field_pointing_at_an_invariant_constraint()) {
        todo_predicate!("`check(file) == failed` — same shape as `advisory_cannot_gate` and `emits_cannot_target_non_effect`, mirrored onto the third kind-typed reference field");
    }
}

proptest! {
    // id: extension_point_needs_no_reachability_carveout
    // generator: `constraint_row_with(satisfies: an_extension_point_in_another_file, traces_to: own_file_intent)`
    // predicate: `check(row) == passed` — `satisfies` adds no reachability obligation; the row is reachable the ordinary way, through its own `traces_to`
    #[test]
    fn extension_point_needs_no_reachability_carveout(v0 in spec_gen::constraint_row_with()) {
        todo_predicate!("`check(row) == passed` — `satisfies` adds no reachability obligation; the row is reachable the ordinary way, through its own `traces_to`");
    }
}

proptest! {
    // id: frontmatter_missing_field_rejected
    // generator: `frontmatter_missing(one of id, kind, statement)`
    // predicate: `check(file) == failed`
    #[test]
    fn frontmatter_missing_field_rejected(v0 in spec_gen::frontmatter_missing()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: guardless_transition_rejected
    // generator: `transition_row_with(empty guard cell)`
    // predicate: `check(file) == failed`
    #[test]
    fn guardless_transition_rejected(v0 in spec_gen::transition_row_with()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: non_ears_statement_rejected
    // generator: `statement_outside_the_five_ears_patterns("the system should maybe work")`
    // predicate: `check(file) == failed`
    #[test]
    fn non_ears_statement_rejected(v0 in spec_gen::statement_outside_the_five_ears_patterns()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: multi_intent_join_rejected
    // generator: `row_id_joined_to_two_intents_via_and()`
    // predicate: `check(file) == failed`
    #[test]
    fn multi_intent_join_rejected(v0 in spec_gen::row_id_joined_to_two_intents_via_and()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: coverage_gap_flagged
    // generator: `spec_file_with(constraint_with_no_deriving_property: true)`
    // predicate: `lint(file) reports rule == failed`
    #[test]
    fn coverage_gap_flagged(v0 in spec_gen::spec_file_with()) {
        todo_predicate!("`lint(file) reports rule == failed`");
    }
}

proptest! {
    // id: law_missing_case_rejected
    // generator: `law_property_missing("associativity")`
    // predicate: `check(file) == failed`
    #[test]
    fn law_missing_case_rejected(v0 in spec_gen::law_property_missing()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: orphan_state_rejected
    // generator: `state_appearing_in_no_transition()`
    // predicate: `check(file) == failed`
    #[test]
    fn orphan_state_rejected(v0 in spec_gen::state_appearing_in_no_transition()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: missing_model_section_rejected
    // generator: `spec_file_without_states_or_transitions()`
    // predicate: `check(file) == failed`
    #[test]
    fn missing_model_section_rejected(v0 in spec_gen::spec_file_without_states_or_transitions()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: invariant_violation_blocks_verify
    // generator: `model_with_a_violated_invariant()`
    // predicate: `check(model_check) == failed`
    #[test]
    fn invariant_violation_blocks_verify(v0 in spec_gen::model_with_a_violated_invariant()) {
        todo_predicate!("`check(model_check) == failed`");
    }
}

proptest! {
    // id: failing_proptest_blocks_verify
    // generator: `compiled_proptest_block_that_fails()`
    // predicate: `check(verify) == failed`
    #[test]
    fn failing_proptest_blocks_verify(v0 in spec_gen::compiled_proptest_block_that_fails()) {
        todo_predicate!("`check(verify) == failed`");
    }
}

proptest! {
    // id: prose_does_not_affect_lint
    // generator: `two_specs_identical_except_rationale_prose()`
    // predicate: `lint(a) == lint(b)` — differing prose never changes a lint result
    #[test]
    fn prose_does_not_affect_lint(v0 in spec_gen::two_specs_identical_except_rationale_prose()) {
        todo_predicate!("`lint(a) == lint(b)` — differing prose never changes a lint result");
    }
}

proptest! {
    // id: silently_shrunk_id_set_rejected
    // generator: `(r, r')` where a 𝒦-governed id-set member was removed with no Revision heading
    // predicate: `check(revisions) == failed`
    #[test]
    fn silently_shrunk_id_set_rejected() {
        todo_predicate!("`check(revisions) == failed`");
    }
}

proptest! {
    // id: constraint_kind_out_of_set_rejected
    // generator: `constraint_row_with(kind: "made_up")`
    // predicate: `check(file) == failed`
    #[test]
    fn constraint_kind_out_of_set_rejected(v0 in spec_gen::constraint_row_with()) {
        todo_predicate!("`check(file) == failed`");
    }
}

proptest! {
    // id: property_kind_out_of_set_rejected
    // generator: `property_row_with(kind: "audit")`
    // predicate: `check(file) == failed`
    #[test]
    fn property_kind_out_of_set_rejected(v0 in spec_gen::property_row_with()) {
        todo_predicate!("`check(file) == failed`");
    }
}

