----------------------------------------------
MODULE specodelic
----------------------------------------------
\* Generated by `spk compile` from spec `specodelic` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"draft", "parsed", "linted", "compiled", "model_checked", "verified"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

Init == vpc = "draft"

Next ==
  \* parse: draft -> parsed (guard: [[specodelic.frontmatter_valid]] ∧ [[specodelic.id_matches_file]])
  \/ vpc = "draft" /\ vpc' = "parsed"
  \* lint: parsed -> linted (guard: `∀ checker ∈ checker_ownership: checker.state == passed` — see Checker Ownership below)
  \/ vpc = "parsed" /\ vpc' = "linted"
  \* compile: linted -> compiled (guard: [[specodelic.coverage]] ∧ [[specodelic.law_requires_cases]])
  \/ vpc = "linted" /\ vpc' = "compiled"
  \* model_check: compiled -> model_checked (guard: [[specodelic.model_present]])
  \/ vpc = "compiled" /\ vpc' = "model_checked"
  \* verify: model_checked -> verified (guard: [[specodelic.no_counterexample]] ∧ [[specodelic.properties_pass]])
  \/ vpc = "model_checked" /\ vpc' = "verified"

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
