------------------------------------------
MODULE verify
------------------------------------------
\* Generated by `spk compile` from spec `verify` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"not_run", "running", "properties_evaluated", "verified", "failed"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "not_run"

Next ==
  \* begin: not_run -> running (guard: [[verify.blocks_run_to_completion]])
  \/ vpc = "not_run" /\ vpc' = "running"
  \* evaluate: running -> properties_evaluated (guard: `every compiled proptest! block has recorded pass or fail`)
  \/ vpc = "running" /\ vpc' = "properties_evaluated"
  \* accept: properties_evaluated -> verified (guard: [[verify.both_gates_required]] ∧ [[verify.properties_pass_reflects_latest_run]] ∧ [[verify.law_cases_all_run]])
  \/ vpc = "properties_evaluated" /\ vpc' = "verified"
  \* reject: properties_evaluated -> failed (guard: `¬accept.guard`)
  \/ vpc = "properties_evaluated" /\ vpc' = "failed"

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
