//! proptest scaffolding for `verify` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// Each yields a String (the generator's name; executable
/// fragments bind these directly — Revision 15).
pub mod spec_gen {
    use super::*;

    pub fn run_that_skips_one_compiled_block() -> impl Strategy<Value = String> {
        Just("run_that_skips_one_compiled_block".into())
    }

    pub fn block_with() -> impl Strategy<Value = String> {
        Just("block_with".into())
    }

    pub fn file_with() -> impl Strategy<Value = String> {
        Just("file_with".into())
    }

    pub fn law_property_with() -> impl Strategy<Value = String> {
        Just("law_property_with".into())
    }

    pub fn verification_failure_raised() -> impl Strategy<Value = String> {
        Just("verification_failure_raised".into())
    }

    pub fn runner_with() -> impl Strategy<Value = String> {
        Just("runner_with".into())
    }

    pub fn fixture_with() -> impl Strategy<Value = String> {
        Just("fixture_with".into())
    }

    pub fn report_with() -> impl Strategy<Value = String> {
        Just("report_with".into())
    }

    pub fn report_from_a_different_structured_scope() -> impl Strategy<Value = String> {
        Just("report_from_a_different_structured_scope".into())
    }

    pub fn run_with() -> impl Strategy<Value = String> {
        Just("run_with".into())
    }

    pub fn docs_built_for_a_release() -> impl Strategy<Value = String> {
        Just("docs_built_for_a_release".into())
    }

}

proptest! {
    // id: partial_run_rejected
    // generator: `run_that_skips_one_compiled_block()`
    // predicate: `check(run) == invalid`
    #[test]
    fn partial_run_rejected(v0 in spec_gen::run_that_skips_one_compiled_block()) {
        todo_predicate!("`check(run) == invalid`");
    }
}

// id: cached_result_rejected
// generator: `(passing_run, properties_edited_afterward_with_no_rerun)`
// predicate: `properties_pass(file) == false` — until re-run
#[test]
fn cached_result_rejected() {
        todo_predicate!("`properties_pass(file) == false` — until re-run");
}

proptest! {
    // id: shrunk_counterexample_reported
    // generator: `block_with(large_random_failing_input: true, smaller_reachable_by_shrinking: true)`
    // predicate: `reported_input(check(block)) == the_smaller_one`
    #[test]
    fn shrunk_counterexample_reported(v0 in spec_gen::block_with()) {
        todo_predicate!("`reported_input(check(block)) == the_smaller_one`");
    }
    // id: single_gate_insufficient
    // generator: `file_with(properties_pass: true, no_counterexample: false)`
    // predicate: `check(file) == failed`
    #[test]
    fn single_gate_insufficient(v0 in spec_gen::file_with()) {
        todo_predicate!("`check(file) == failed`");
    }
    // id: both_gates_clean_passes
    // generator: `file_with(properties_pass: true, no_counterexample: true)`
    // predicate: `check(file) == verified`
    #[test]
    fn both_gates_clean_passes(v0 in spec_gen::file_with()) {
        todo_predicate!("`check(file) == verified`");
    }
    // id: partial_law_case_rejected
    // generator: `law_property_with(identity_case: "pass", associativity_case: "fail")`
    // predicate: `check(property) == failed`
    #[test]
    fn partial_law_case_rejected(v0 in spec_gen::law_property_with()) {
        todo_predicate!("`check(property) == failed`");
    }
}

// id: rerun_matches_prior_outcome
// generator: `(run_1, run_2)` on an unchanged compiled artifact
// predicate: `outcome(run_1) == outcome(run_2)`
#[test]
fn rerun_matches_prior_outcome() {
        todo_predicate!("`outcome(run_1) == outcome(run_2)`");
}

proptest! {
    // id: verification_failure_label_asserted
    // generator: `verification_failure_raised()`
    // predicate: `error_label == "verify.verification_failure"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)
    #[test]
    fn verification_failure_label_asserted(v0 in spec_gen::verification_failure_raised()) {
        todo_predicate!("`error_label == \"verify.verification_failure\"` — renaming the label touches the error Constraint, this property, and its note together (EDGE-002)");
    }
    // id: hang_reported_as_labeled_timeout
    // generator: `runner_with(predicate_that_never_terminates, timeout: 1)`
    // predicate: `check(run) == timeout_labeled ∧ outcome(run) ≠ failed` — a timeout is no verdict on the property: distinct from properties_failed so a legitimately long suite can be re-run with a raised bound instead of misread as a failing predicate
    #[test]
    fn hang_reported_as_labeled_timeout(v0 in spec_gen::runner_with()) {
        todo_predicate!("`check(run) == timeout_labeled ∧ outcome(run) ≠ failed` — a timeout is no verdict on the property: distinct from properties_failed so a legitimately long suite can be re-run with a raised bound instead of misread as a failing predicate");
    }
    // id: fragments_reach_verified
    // generator: `fixture_with(fragment_predicate_passing, executable_invariant_clean)`
    // predicate: `check(file) == verified` — with executable fragments (specodelic.md Revision 15) both gates are reachable: a passing executable predicate and a clean executable-invariant run verify a real file, the state the gate could never reach before this Revision
    #[test]
    fn fragments_reach_verified(v0 in spec_gen::fixture_with()) {
        todo_predicate!("`check(file) == verified` — with executable fragments (specodelic.md Revision 15) both gates are reachable: a passing executable predicate and a clean executable-invariant run verify a real file, the state the gate could never reach before this Revision");
    }
    // id: claim_complete_evidence_verifies
    // generator: `fixture_with(all_required_claims_verified, properties_pass)`
    // predicate: `check(file) == verified with the exact required and unchecked sets`
    #[test]
    fn claim_complete_evidence_verifies(v0 in spec_gen::fixture_with()) {
        todo_predicate!("`check(file) == verified with the exact required and unchecked sets`");
    }
    // id: false_claim_blocks_verified
    // generator: `file_with(properties_pass: true, counterexample_kernel_claim)`
    // predicate: `check(file) == failed naming the false claim id` — properties never cover a refuted claim
    #[test]
    fn false_claim_blocks_verified(v0 in spec_gen::file_with()) {
        todo_predicate!("`check(file) == failed naming the false claim id` — properties never cover a refuted claim");
    }
    // id: malformed_records_rejected
    // generator: `report_with(missing_or_duplicate_claim_record)`
    // predicate: `check(file) == failed with a rerun hint` — never inferred as unknown success
    #[test]
    fn malformed_records_rejected(v0 in spec_gen::report_with()) {
        todo_predicate!("`check(file) == failed with a rerun hint` — never inferred as unknown success");
    }
}

// id: stale_report_rejected_with_rerun_hint
// generator: `(clean_report, structurally_edited_inputs_afterward)`
// predicate: `check(file) == failed naming the rerun command — the report is never rewritten`
#[test]
fn stale_report_rejected_with_rerun_hint() {
        todo_predicate!("`check(file) == failed naming the rerun command — the report is never rewritten`");
}

proptest! {
    // id: swapped_scope_report_rejected
    // generator: `report_from_a_different_structured_scope()`
    // predicate: `check(file) == failed — the digest binds structured content, not paths`
    #[test]
    fn swapped_scope_report_rejected(v0 in spec_gen::report_from_a_different_structured_scope()) {
        todo_predicate!("`check(file) == failed — the digest binds structured content, not paths`");
    }
    // id: views_agree_on_blockers
    // generator: `run_with(required_unknown_claim_and_prose_invariant)`
    // predicate: `json.blockers == human.blockers == report.blockers ∧ unchecked sets agree`
    #[test]
    fn views_agree_on_blockers(v0 in spec_gen::run_with()) {
        todo_predicate!("`json.blockers == human.blockers == report.blockers ∧ unchecked sets agree`");
    }
    // id: release_docs_match_implemented_capabilities
    // generator: `docs_built_for_a_release()`
    // predicate: `version derives from Cargo metadata ∧ pending capabilities not advertised as implemented`
    #[test]
    fn release_docs_match_implemented_capabilities(v0 in spec_gen::docs_built_for_a_release()) {
        todo_predicate!("`version derives from Cargo metadata ∧ pending capabilities not advertised as implemented`");
    }
}

