#!/usr/bin/env python3
"""Tests for scripts/check_section_sync.py (stdlib unittest, no deps).

Covers the section-sync drift logic and the capability-format check:
every capability spec under openspec/specs/<cap>/spec.md MUST be a
dual-format file (frontmatter + tables) — a plain openspec regeneration
output there is a CI failure, not a silent skip (Rule-of-5 EDGE-001:
the spk lint rule cannot see frontmatter-less files, which parse-skip).

Run: python3 -m unittest discover -s scripts -p 'test_*.py'
"""

import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import check_section_sync as css  # noqa: E402


TABLES = (
    "## Constraints\n\n| id | kind | expr | traces_to |\n"
    "|----|------|------|-----------|\n"
    "| a | invariant | `x` | |\n\n"
    "## Model\n\n### States\n\n- `s1`\n\n### Transitions\n\n"
    "| id | from | to | guard |\n|----|------|----|-------|\n"
    "| t | s1 | s1 | [[spec.a]] |\n\n"
    "## Properties\n\n| id | kind | derives_from | generator | predicate |\n"
    "|----|------|--------------|-----------|------------|\n"
    "| p | unit | [[spec.a]] | `g()` | `x` |\n\n"
)


class SectionSyncTest(unittest.TestCase):
    def write(self, tree: dict[str, str]) -> Path:
        tmp = tempfile.mkdtemp()
        root = Path(tmp)
        for rel, text in tree.items():
            p = root / rel
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(text, encoding="utf-8")
        return root

    def test_drifted_requirement_text_is_flagged(self):
        root = self.write({
            "openspec/specs/cap/spec.md": (
                "---\nid: spec\nkind: intent\nstatement: \"SHALL\"\n---\n\n"
                + TABLES
                + "## ADDED Requirements\n\n### Requirement: A\nThe system SHALL a.\n\n"
                "## Requirements\n\n### Requirement: A\nThe system SHALL b.\n"
            ),
        })
        problems = css.check(root / "openspec/specs/cap/spec.md")
        self.assertEqual(len(problems), 1)
        self.assertIn("divergent requirement text: A", problems[0])

    def test_in_sync_dual_file_is_clean(self):
        root = self.write({
            "openspec/specs/cap/spec.md": (
                "---\nid: spec\nkind: intent\nstatement: \"SHALL\"\n---\n\n"
                + TABLES
                + "## ADDED Requirements\n\n### Requirement: A\nThe system SHALL a.\n\n"
                "## Requirements\n\n### Requirement: A\nThe system SHALL a.\n"
            ),
        })
        self.assertEqual(css.check(root / "openspec/specs/cap/spec.md"), [])


class CapabilityFormatTest(unittest.TestCase):
    """Rule-of-5 EDGE-001: plain capability specs must fail CI."""

    def write(self, tree: dict[str, str]) -> Path:
        tmp = tempfile.mkdtemp()
        root = Path(tmp)
        for rel, text in tree.items():
            p = root / rel
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(text, encoding="utf-8")
        return root

    def test_plain_capability_spec_is_flagged(self):
        # The exact pre-migration model-check state: a capability spec
        # regenerated by plain archive — no frontmatter, lint-invisible.
        root = self.write({
            "openspec/specs/model-check/spec.md": (
                "# model-check Specification\n\n## Purpose\nTBD\n\n"
                "## Requirements\n\n### Requirement: A\nThe system SHALL a.\n"
            ),
        })
        problems = css.check(root / "openspec/specs/model-check/spec.md")
        self.assertEqual(len(problems), 1, problems)
        self.assertIn("no frontmatter", problems[0])
        self.assertIn("dual-format", problems[0])

    def test_capability_spec_with_frontmatter_but_no_tables_is_flagged(self):
        # Half-migrated: frontmatter present, specodelic tables missing.
        root = self.write({
            "openspec/specs/cap/spec.md": (
                "---\nid: spec\nkind: intent\nstatement: \"SHALL\"\n---\n\n"
                "## Requirements\n\n### Requirement: A\nThe system SHALL a.\n"
            ),
        })
        problems = css.check(root / "openspec/specs/cap/spec.md")
        self.assertEqual(len(problems), 1, problems)
        self.assertIn("## Constraints", problems[0])

    def test_dual_format_capability_spec_is_clean(self):
        root = self.write({
            "openspec/specs/cap/spec.md": (
                "---\nid: spec\nkind: intent\nstatement: \"SHALL\"\n---\n\n"
                "## Constraints\n\n| id | kind | expr | traces_to |\n"
                "|----|------|------|-----------|\n"
                "| a | invariant | `x` | |\n\n"
                "## Model\n\n### States\n\n- `s1`\n\n### Transitions\n\n"
                "| id | from | to | guard |\n|----|------|----|-------|\n"
                "| t | s1 | s1 | [[spec.a]] |\n\n"
                "## Properties\n\n| id | kind | derives_from | generator | predicate |\n"
                "|----|------|--------------|-----------|------------|\n"
                "| p | unit | [[spec.a]] | `g()` | `x` |\n\n"
                "## Requirements\n\n### Requirement: A\nThe system SHALL a.\n"
            ),
        })
        self.assertEqual(css.check(root / "openspec/specs/cap/spec.md"), [])

    def test_non_capability_plain_markdown_is_exempt(self):
        # Only files under openspec/specs/<cap>/ are capability specs;
        # project.md, archive files, etc. stay exempt.
        root = self.write({
            "openspec/project.md": "# Project Context\n\nplain prose\n",
        })
        self.assertEqual(css.check(root / "openspec/project.md"), [])


if __name__ == "__main__":
    unittest.main()